### ISSUE TITLE
pod spec lint fails to find matching XCFramework slice for a vendored library dependency

### ISSUE THREAD

**Issue by jakubdolejs** [CocoaPods/CocoaPods#10204]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod spec lint` on a spec that contains a xcframework dependency.

## What did you expect to happen?

The lint should have passed.

## What happened instead?

The `xcodebuild` command failed with 
```
error: no such module 'VerIDCore'
import VerIDCore
       ^
```
I also noticed this note in the `pod spec lint` command output:
```
- NOTE  | [iOS] xcodebuild:  warning: [CP] Unable to find matching .xcframework slice in 'Ver-ID-Core/VerIDCore.xcframework VerIDCore framework ios-i386_x86_64-simulator ios-arm64_armv7' for the current build architectures (arm64 i386 x86_64).
```
If you download the VerIDCore dependency you'll find it contains slices for armv7, arm64, i386 and x86_64.

Also worth mentioning is that I successfully integrated the VerIDCore dependency in a project. It's only if it's set as a dependency of another podspec that the podspec's lint fails.

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
    RubyGems : 3.0.6
        Host : Mac OS X 10.15.7 (19H2)
       Xcode : 12.1 (12A7403)
         Git : git version 2.23.0
Ruby lib dir : /Users/jakub/.rvm/rubies/ruby-2.6.3/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/jakub/.rvm/gems/ruby-2.6.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate  : 1.0.4
cocoapods-dependencies : 1.3.0
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.1.0
cocoapods-trunk        : 1.5.0
cocoapods-try          : 1.2.0
```

### Podfile

```ruby
project 'VerIDUI.xcodeproj'
workspace 'VerIDUI.xcworkspace'

platform :ios, '10.3'
use_frameworks!

def veridcore
  pod 'Ver-ID-Core', '2.0.0-beta.04'
end

target 'VerIDUI' do
  veridcore
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
end

target 'Ver-ID Sample' do
  pod 'DeviceKit', '~> 4.1'
end

target 'Thumbnails' do
  veridcore
end

target 'Preview' do
  veridcore
end
```

## Project that demonstrates the issue

[Github link](https://github.com/AppliedRecognition/Ver-ID-UI-iOS/tree/version2)

**Comment by mharlowfod** [comment]
Experiencing a similar issue with BugfenderSDK dependency...

**Comment by miquelalvarado** [comment]
Experiencing the same issue with Didomi-XCFramework dependency. Did you find any workaround?

**Comment by hlineholm** [comment]
After a closer look at the xcframework bash scripts and what they do, it seems that instead of copying the `ios-x86_64-simulator` slice to `Products/Release-iphonesimulator` in derived data, the scripts try to copy the `ios-arm64` slice to `Products/Release-iphones` although while linting, `-sdk iphonesimulator` is used with `xcodebuild`. 
This results in the slice not being copied at all and even if it did, the architecture would be wrong and thus the symbols would still be missing.

**Comment by jakubdolejs** [comment]
> Experiencing the same issue with Didomi-XCFramework dependency. Did you find any workaround?

Yes. But it's so ugly that I even hesitate to call it a workaround. Details [here](https://github.com/CocoaPods/CocoaPods/issues/5801#issuecomment-318851267).

**Comment by mhdostal** [comment]
> Also worth mentioning is that I successfully integrated the VerIDCore dependency in a project. It's only if it's set as a dependency of another podspec that the podspec's lint fails.

I also am experiencing this exact issue.  I was using Xcode 12.x command line tools and can verify the above statement.  If I used the Xcode 11 command line tools I did NOT receive the error and was able to `podspec lint` successfully.

**Comment by mharlowfod** [comment]
Just and FYI, my instance of this issue (personal private pod with BugfenderSDK as a dependency) magically went away when I updated to the latest cocoapods version (I am not sure if a BugfenderSDK change came along the way, but I don't think it did).

Not saying it's fixed everywhere, but if you haven't tried in the past 3 weeks, you might kick the tires and see if there's been any improvement.

**Comment by FWJonathan** [comment]
This issue is still occurring for me with v1.10.1 when trying to include BlackBerryDynamics:
```
warning: [CP] Unable to find matching .xcframework slice in '.../BlackBerryDynamics.xcframework BlackBerryDynamics framework ios-x86_64-simulator ios-arm64' for the current build architectures (arm64 x86_64).
```

**Comment by wilmarvh** [comment]
Same issue here. I have a private pod with an xcframework dependency and the linting fails with the same. 

CocoaPods 1.10.1

**Comment by ElfSundae** [comment]
Same here when lint or push a  pod with a binary xcframework (without i386 arch) dependency.
CocoaPods 1.10.1, it fails either on Xcode 12.4 or Xcode 11.7.

**Comment by kerrmarin-lvmh** [comment]
@dnkoutso is this something I can help with? I'd be happy to submit a patch but honestly have no idea where to even start. With a bit of guidance I'd be happy to help

**Comment by lufinkey** [comment]
After doing some digging and logging, I'm able to reproduce this when building for a simulator and there is no architecture in the xcframework with the `-simulator` suffix for that architecture.

Before I make this fix though, I'm trying to figure out if you're allowed to link the `ios-arm64` slice of the xcframework against the an arm64 simulator or not? Because this may be an issue when generating the xcframework itself, basically making sure it actually has the slice with the `-simulator` suffix.

**Comment by jindalpatel** [comment]
I am also facing the same issue. `xcframework slice in '../../../../../../../../SplunkMint.xcframework SplunkMint framework ios-arm64 ios-x86_64-simulator' for the current build architectures (arm64 x86_64).` 

Cocoapod 1.10.2

**Comment by StefanMiticon** [comment]
I am just trying to push or lint this https://github.com/MappCloud/MappSDK and facing the same issue.

Cocoa pods 1.11.2
Xcode 13.1

Does someone found solution or workaround?

**Comment by lufinkey** [comment]
I think the ideal behavior for this should be to just fall back to the `ios-arm64` architecture rather than `ios-arm64-simulator`. I don't really know where that decision gets made in the code, though

**Comment by billburgess** [comment]
+1

**Comment by leninmehedy** [comment]
+1

Cocoa pods 1.11.2

Xcode 13.1
Build version 13A1030d

Facing similar issue, and haven't found a solution yet:
```
 ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | xcodebuild:  note: Build preparation complete
    - NOTE  | [iOS] xcodebuild:  note: Planning
    - NOTE  | [iOS] xcodebuild:  note: Building targets in parallel
    - NOTE  | [iOS] xcodebuild:  warning: [CP] Unable to find matching .xcframework slice in 'ios-x86_64-simulator ios-arm64' for the current build architectures (arm64 x86_64).
    - NOTE  | xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ```

**Comment by LowAmmo** [comment]
Anyone know if this might be related to #10058 ?

If so, looks like there is a PR to fix that one - #11093

**Comment by omarzl** [comment]
> Anyone know if this might be related to #10058 ?
> 
> If so, looks like there is a PR to fix that one - #11093

I dont think they are related, this one is about xcframework slice selection while #10058 issue is about Swift module include paths

**Comment by igor-makarov** [comment]
@jakubdolejs 

The `Ver-ID` pod has vendored XCFrameworks that contain frameworks and not libraries, so this is unrelated to issue #10058 mentioned above.
 
The root cause is that the XCFramework is missing an `arm64` binary for the iOS Simulator, the one running on Apple Silicon Macs.

When running `pod spec lint`, it builds the pod using the `Release` build configuration. This means, using all active architectures, which for the simulator is `arm64 x86_64`.

**The solution is to add support for arm64 simulators to the binary.**

If you're unable to do so, you can use the workaround described in https://github.com/CocoaPods/CocoaPods/issues/10104#issuecomment-700918704 to explicitly disallow arm64 simulators from using the binary. This however should be a temporary measure, because the number of developers with Apple Silicon machines is growing faster and faster.

**Comment by ElfSundae** [comment]
I met this issue before when I tried to publish a pod library that depends on another binary vendored no-arm64-simulator-arch dependency. After some digging, I successfully published my library by using an ugly _workaround_. Here I'd like to share something and hope this could help someone.

Many people mentioned below solution:

```ruby
s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
```

But it can not work at all. Configuring `EXCLUDED_ARCHS` in the `spec.pod_target_xcconfig` just excludes architectures for the pod library target, not for the app target such as the CocoaPods validator generated app target.

Then:

```ruby
s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
```

I'd like to say this is a terrible way. From the doc of [`user_target_xcconfig`](https://guides.cocoapods.org/syntax/podspec.html#user_target_xcconfig):

> This attribute is **not recommended** as Pods should not pollute the build settings of the user project and this can cause conflicts.

For instance, one pod has:

```ruby
s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
```

and another pod has:

```ruby
s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386 arm64' }
```

If the user integrate these two pod libraries, `pod install` will fail as CocoaPods can not merge the `user_target_xcconfig` configuration:

```
[!] Can't merge user_target_xcconfig for pod targets: ["FooPod", "BarPod"]. 
Singular build setting EXCLUDED_ARCHS[sdk=iphonesimulator*] has different values.
```

**The only solution for this issue is to ask the vendor to rebuild their pod library for the arm64-simulator architecture and publish the library with XCFramework format which is the only format can bundle arm64-device and arm64-simulator together.**

Before the vendor updates their library, we may modify the CocoaPods source code to skip validating when publishing our library. Below is my ugly _workaround_:

In order not to modify the global installed `pod` command, I forked https://github.com/CocoaPods/CocoaPods repo, modified the `xcodebuild` function in the `validator.rb` file to skip executing the `xcodebuild` command during validation, by appending a `-usage` CLI parameter for the `xcodebuild` command:

```diff
 def xcodebuild(action, scheme, configuration, deployment_target:)
   require 'fourflusher'
   command = %W(clean #{action} -workspace #{File.join(validation_dir, 'App.xcworkspace')} -scheme #{scheme} -configuration #{configuration})
+  command += %w(-usage)
```

Then the validator will build the app using `xcodebuild -workspace .....  -usage` which is the same as `xcodebuild -usage`. 

This modification just skips building, not the whole validation.

You may see compare between CocoaPods' `master` branch and my fork's `hack` branch at <https://github.com/CocoaPods/CocoaPods/compare/master..ElfSundae:hack>

Then anyone can use this fork to publish their library, via `bundle`:

```sh
bundle init
bundle add cocoapods --git https://github.com/ElfSundae/CocoaPods.git --branch hack

bundle exec pod repo push

rm Gemfile Gemfile.lock
```

> If you already have `Gemfile`, omit the first line `bundle init` and the last line `rm Gemfile Gemfile.lock`.

In addition, this is an example of publishing podspec using GitHub workflow: https://github.com/ElfSundae/NIM_iOS_UIKit/blob/master/.github/workflows/publish-podspec.yml

**Comment by dzmitry-antonenka** [comment]
Hello @ElfSundae , I tried to execute `bundle add cocoapods --git https://github.com/ElfSundae/CocoaPods.git --branch hack` but got this error: Unknown switches '--git, --branch'. I have Bundler version 1.17.2. Could you please support?

**Comment by ElfSundae** [comment]
@dzmitry-antonenka For bundler 1.17, you may change
```sh
bundle add cocoapods --git https://github.com/ElfSundae/CocoaPods.git --branch hack
```
to 
```sh
echo 'gem "cocoapods", "~> 1.11", :git => "https://github.com/ElfSundae/CocoaPods.git", :branch => "hack"' >> Gemfile
```
