### ISSUE TITLE
Getting unknown error on installing cocoapods on mac m1 

### ISSUE THREAD

**Issue by kishansh31** [CocoaPods/CocoaPods#10712]
Hello all,

I am trying to install cocoapods on my mac m1 system with bigSur, I am using xcode 12.5 as command tool. I am installing cocoapods on the first time.

I have also tried for arm-64 architecture support but didn't find any solution on that.

Please consider the following screenshot for the installation error: 

<img width="999" alt="Screenshot 2021-06-12 at 11 17 57 PM" src="https://user-images.githubusercontent.com/55207490/121784938-8af8d280-cbd4-11eb-9c93-fb63d165e9f8.png">

**Comment by MaximilianFlechtner** [comment]
I have the same issue, do you have any solution ?

**Comment by Ahmedhamed77** [comment]
the same error on M1

**Comment by omarzl** [comment]
This is what we are doing to setup Cocoapods in M1

1.- Xcode
Download and install Xcode, then instal the CLT
```
xcode-select --install
```

2.- Home brew
Install Homebrew according to their docs and add it to your zsh config
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zshrc
```
-> Open a new Terminal tab so the changes are reflected

3.-  Ruby
Install ruby using brew
```
brew install ruby@2.6
echo 'export PATH=/opt/homebrew/opt/ruby@2.6/bin:/opt/homebrew/lib/ruby/gems/2.6.0/bin:$PATH' >> ~/.zshrc
```
-> Open a new Terminal tab so the changes are reflected

4.-  CocoaPods
Install CocoaPods gem
```
gem install cocoapods
```

--------

We are using Ruby version 2.6 since CocoaPods Gemspec specifies it: https://github.com/CocoaPods/CocoaPods/blob/9461b346aeb8cba6df71fd4e71661688138ec21b/cocoapods.gemspec#L58

Also this lets you use Bundler if you require it, if you use ruby 3.0 it will give you problems

**Comment by dnkoutso** [comment]
Closing as dup of https://github.com/CocoaPods/CocoaPods/issues/10220
