### ISSUE TITLE
The 'Pods-xxx' target has transitive dependencies that include statically linked binaries:

### ISSUE THREAD

**Issue by passol1988** [CocoaPods/CocoaPods#10949]
when I make a swift and oc mix project,I  encountered this error:
The 'Pods-xxx' target has transitive dependencies that include statically linked binaries:

So I use  cocoapods-static-swift-framework , a cocoapods plugin that enables static frameworks for all pods to avoid error (cocoapod version 1.8.4)
But when I update cocoapods to the latest version, I encountered this error again because this plugin cannot work well 

So what can i do to avoid this error.

**Comment by dnkoutso** [comment]
Sorry, you will have to ask the plugin maintainer to update their plugin to work with the latest version of cocoapods.

The error is something that has existed in cocoapods since its creation and cocoapods currently does not support this use case. Its possible the plugin side-steps this functionality and things "happen to work" but there are no tests or guarantee they will continue to work.
