### ISSUE TITLE
I'm not able to add xcframework to the project via CocoaPods in Xcode 13

### ISSUE THREAD

**Issue by pwittchen** [CocoaPods/CocoaPods#11255]
Hi,

Im not able to build the project with xcframework provided as a CocoaPod.

My environment:
- MacBook Air M1 (basic version)
- macOS Monterey 12.1 (21C52)
- Xcode Version 13.2.1 (13C100)
- CocoaPods 1.11.2

`iOS-SDK.podspec` file:

```
Pod::Spec.new do |spec|
  spec.name         = "iOS-SDK"
  spec.version      = "0.0.1"
  spec.summary      = "..."
  spec.description  = <<-DESC
  ...
  DESC

  spec.homepage                     = "..."
  spec.authors                      = { "..." => "..." }
  spec.platform                     = :ios, "11.4"
  spec.ios.deployment_target        = "11.4"

  spec.source                       = { :path => "iOS-SDK.xcframework" }
  spec.vendored_frameworks          = "iOS-SDK.xcframework"
  spec.source_files                 = "iOS-SDK.xcframework/*/iOS_SDK.framework/Headers/*.{h,m,swift}"
  spec.preserve_paths               = "*"

  spec.requires_arc                 = true
  spec.swift_version                = "5.0"

  spec.dependency "SwiftProtobuf", "~> 1.0"
  spec.dependency "SWCompression", "~> 4.7"
  spec.dependency "RxSwift", "6.2.0"
  spec.dependency "RxCocoa", "6.2.0"
end
```

`Podfile` of the project consuming framework:

```
platform :ios, '11.4'

target 'app' do
  use_frameworks!

  pod 'iOS-SDK', :path => 'Frameworks/iOS-SDK'
end
```

Directory `Frameworks/iOS-SDK` contains `*.xcframework` directory and `*.podspec` file of the framework (listed above).

When I try to compile the app, I get the following error:

```
ld: framework not found iOS-SDK
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

However, **I'm able to build app** when I change `*.xcframework` to `*.framework` as follows in the `*.podspec` file:

```
Pod::Spec.new do |spec|
  spec.name         = "iOS-SDK"
  spec.version      = "0.0.1"
  spec.summary      = "..."
  spec.description  = <<-DESC
  ...
  DESC

  spec.homepage                     = "..."
  spec.authors                      = { "..." => "..." }
  spec.platform                     = :ios, "11.4"
  spec.ios.deployment_target        = "11.4"

  spec.source                       = { :file => "iOS-SDK.xcframework/ios-arm64/iOS_SDK.framework" }
  spec.vendored_frameworks          = "iOS-SDK.xcframework/ios-arm64/iOS_SDK.framework"
  spec.preserve_paths               = "*"

  spec.requires_arc                 = true
  spec.swift_version                = "5.0"

  spec.dependency "SwiftProtobuf", "~> 1.0"
  spec.dependency "SWCompression", "~> 4.7"
  spec.dependency "RxSwift", "6.2.0"
  spec.dependency "RxCocoa", "6.2.0"
end
```

but in such case I'm able to create a build for `ios-arm64` target only. When, I want to build project for iPhone simulator, I need to change `ios-arm64` into `ios-arm64_x86_64-simulator`, install pods again and rebuild the project.

Moreover, **I'm also able to build the project** with xcframework, when I add it manually to the app via Xcode.

Nevertheless, I would like to be able to add xcframework to the app via CocoaPods instead of adding it manually.

Can you give me some hints, how can I prepare the correct `*.podspec` file to be able to provide xcframework as a CocoaPod? Or alternatively, how can I parametrize `*.podspec` file to be able build app dynamically depending on the build target without editing the `*.podspec` file, so I could have a single `*.podspec` file both for iPhone device and simulator instead of two files?

I appreciate any help.

Regards,
Piotr

**Comment by emawby** [comment]
@pwittchen I wonder if specifying `source_files` in the podspec is causing issues when you are trying to distribute the compiled xcframework. Maybe try removing that property entirely. My spec only has a `source` property which points to the git repo and a `spec.ios.vendored_frameworks` property no `spec.source_files`.

**Comment by pwittchen** [comment]
Thanks for the reply @emawby. I removed `spec.source_files` from the `*.podspec` file and nothing changed.

**Comment by dnkoutso** [comment]
You might need to `flatten` the http download. Perhaps cocoapods is not finding the xcframework path you specified and yes you do not need `s.source_files`.

**Comment by dnkoutso** [comment]
Try something like

```ruby
s.source           = { http: 'url/to/your/zip', :flatten => false } 
```

**Comment by pwittchen** [comment]
So I need to zip xcframework first and then host it on the server or run a local server with it to use this configuration? Is it possible to provide a path to framework located on a disk?

**Comment by dnkoutso** [comment]
You do not need to that, you can consume the pod locally using `:path` in your podfile. Then it wont use `s.source` and just load things from the local paths.

**Comment by PMarsh-UB** [comment]
Hello,

I didn't want to open another issue as @pwittchen seems to have had the same issue as me but, I'm still stuck. 

I have an xcframework that I build with the following commands:

- iOS 
```
xcodebuild archive -workspace SDK.xcworkspace -scheme SDK -destination "generic/platform=iOS" -sdk iphoneos -archivePath ../builds/SDK-iOS SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES
```
- iOS Simulator
```
xcodebuild archive -workspace SDK.xcworkspace -scheme SDK -destination "generic/platform=iOS Simulator" -sdk iphonesimulator -archivePath ../builds/SDK-Sim SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES
```
- xcframework
```
xcodebuild -create-xcframework -framework ./SDK-Sim.xcarchive/Products/Library/Frameworks/SDK.framework -framework ./SDK-iOS.xcarchive/Products/Library/Frameworks/SDK.framework  -output ./SDK.xcframework
```

I can manually add the ```.xcframework``` folder to my sample project, build, and use my SDK. However, when I try with a cocoapod, I cant.

``` SDK.podspec ```:

```
Pod::Spec.new do |s|
     s.name              = 'SDK' # Name for your pod
     s.version           = '1.0.0'
     s.summary           = 'Sample Spec'
     s.homepage          = 'https://www.google.com'

     s.author            = { 'Sample' => 'sample@sample.com' }
     s.license = { :type => "MIT", :text => "MIT License" }

     s.platform          = :ios
     s.swift_version     = '5.0'
     # change the source location
     s.source            = { :http => 'file:///PATH-TO-ZIP/SDK.xcframework.zip', :flatten => false}
     s.ios.deployment_target = '15.2'
     s.vendored_frameworks = 'SDK.xcframework' 
     s.preserve_paths = '*'

     # sample dependency
     s.dependency 'Alamofire', '~> 5.6.2'
end
```

The ```.podspec``` passes pod spec lint.

```PodFile```: 

``` 
# Uncomment the next line to define a global platform for your project 
# platform :ios, '9.0'

target 'SDKExample' do
   # Comment the next line if you don't want to use dynamic frameworks
   use_frameworks!
   pod 'SDK', :path => '/PATH-TO-PODSPEC/SDK.podspec'

   # Pods for SDKExample

   target 'SDKExampleTests' do
     inherit! :search_paths

     # Pods for testing
   end

   target 'SDKExampleUITests' do
     # Pods for testing
   end

end
```

When I create the ```.xcworkspace``` with ```pod install``` my ```.xcframework``` is not added to the sample project. The ```Alamofire``` dependency is, but not the framework. Am I doing anything blatantly wrong? 

Regards,
Peter.

**Comment by pwittchen** [comment]
Just FYI: I didn't resolve it. I can add framework as a development pod with source and it works, but when I try to add xcframework I need to do it manually via XCode to make it work.

**Comment by PMarsh-UB** [comment]
Okay, that is basically where I'm at. I can add manually but, not via a CocoaPod.

**Comment by PMarsh-UB** [comment]
@dnkoutso Should I open another issue? I'm not sure what visibility this is getting as the issue is closed.

**Comment by heeween** [comment]
here is what I write in spec file. But I think it not the reason how does spec file write. Because firstly I meet the same problem 'framework not found heresdk'. The I open a blank project to test this sdk, and it is ok. So I delete the pod in my real project, run pod install. Add the pod back run pod install. And try several times It work fine. 
`Pod::Spec.new do |s|
  s.name             = 'heresdk'
  s.version          = '0.1.0'
  s.summary          = 'A short description of heresdk.'
  s.description      = 'here地图官网的静态库,xcframework形式'
  s.homepage         = 'https://github.com/贺彦文/heresdk'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { '贺彦文' => 'heyanwen' }
  s.source           = { :git => 'https://git-devops.com/iOS/framework/heresdk.git', :tag => s.version.to_s }
  s.ios.deployment_target = '9.0'
  s.vendored_frameworks = 'heresdk.xcframework'
  s.frameworks = 'UIKit','Foundation','SystemConfiguration','CoreGraphics','CoreMotion','coreTelephony','coreText','QuartzCore','WebKit'
    s.libraries = 'c++','z'

end`

**Comment by Ernest0-Production** [comment]
Has this problem been solved?

I encountered the same problem. 
Specifying the zip archive of my xcframework in source downloads the README and LICENSE file, but not the xcframework itself!

That said, the `pod spec lint` command succeeds, and in the validation process, creates a temporary App.xcworkspace in which the xcframework is actually tethered.

**Comment by pwittchen** [comment]
@Ernest0-Production I didn't solve it. It seems Cocoa Pods don't work properly with xcframework and you need to handle it without Cocoa Pods.

**Comment by Ernest0-Production** [comment]
@pwittchen Hi 👋

I finally figured out the cause and found a solution to the problem.

**The problem was not in the spec.source value, but in the way this pod was connected in the Podfile of my project.** 

After reading the `Podfile` syntax documentation again, I found out that when we specify `:path` or `:git`, **cocoapods ignores the** `spec.source` field of our .podspec file, because it considers the parameters (`:path`/`:git`) specified in the Podfile as source. 

That is, **these parameters override** (or ignore) the `spec.source` field. Cocoapods assumes that the directory specified in path or retrieved from `:git` (with/without `:branch` or `:tag` and etc) is where all our source files are located **NOT where our podspec file is.** 

✅ The correct solution is to point the path to the podspec, not to the source files. There are two ways to do this:

1. Add the podspec to your private or public CocoaPods spec repository and reference it explicitly or implicitly in the podfile:
```ruby
# implicitly
pod `MyPod`

# explicitly
pod `MyPod`, :source => 'https://www.path/to/myspec-repo'
# or
source 'https://www.path/to/myspec-repo' # for all pods
pod `MyPod`
```

2. Add the `:podspec => <path/to/podspec>` parameter. Unlike `:path`, this specifies the path to the podspec file. This can be either a local or a remote path:
```ruby
# local path
pod `MyPod`, :podspec => './MyPod.podspec' 
# remote path
pod `MyPod`, :podspec => 'https://www.example.com/MyProject/sources/MyPod.podspec'  
```

⚠️ The disadvantage of the second approach is that it is not git friendly. You will not be able to specify a branch or a tag where you want to take the podspec from.

I use both ways:
1. I publish to a spec repository so that library clients can connect to it
2. I specify `:podspec` in the podfile of my demo application which is located in the same repository and this way I have an up to date version of the podspec without having to publish it to the specs repository.

I hope my research helps you too :^)

**Comment by Ernest0-Production** [comment]
@dnkoutso It seems to me that this behavior is rather unobvious 🤔 

And the solution with `:podspec` is not flexible enough as with `:git` + `:tag` / `:branch`
Maybe cocoapods team should add the ability to specify the git repository where the podspec. is located (not the source files). 🙄

It seems that such a tweak would allow to do without creating a separate repository for specs if I have just one podspec.
