### ISSUE TITLE
Flutter Cocoapods Mac Book M1 Set up - Cocoapods installed but not working - git_version': Failed to extract git version

### ISSUE THREAD

**Issue by SportApps** [CocoaPods/CocoaPods#11351]
I am not able to run a flutter app that has CocoaPods on my Mac M1 computer.

Flutter run:

```
Warning: CocoaPods is installed but broken. Skipping pod install.
You appear to have CocoaPods installed but it is not working.
This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
This can usually be fixed by re-installing CocoaPods.
To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
ruby -v
```

`ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]`

UPDATE: I updated the ruby version with home-brew but it still gives the same error:

`ruby -v ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin20]`

Update 2.0 I tried installing CocoaPods with homebrew

```
brew install cocoapods --build-from-source
then: brew link --overwrite cocoapods
```

flutter clean...
Restarting Android Studio ...

And same error!

Update 3.0 Combination of new Ruby 3.1.2p20 with ffi

```
brew unlink cocoapods

brew uninstall cocoapods

```
Try_ing this: https://medium.com/p-society/cocoapods-on-apple-silicon-m1-computers-86e05aa10d3e_

Opening terminal using Rosetta

```
sudo arch -x86_64 gem install ffi

sudo gem install CocoaPods
```

--> Says that CocoaPods are not installed

So I try this approach:

https://stackoverflow.com/a/66842555/18936943

```
1- arch -x86_64 sudo gem install cocoapods -n /usr/local/bin

2- arch -x86_64 sudo gem install ffi

3- pod install
```

```
/usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:128:in `git_version': Failed to extract git version from `git --version` ("") (RuntimeError)
        from /usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:140:in `verify_minimum_git_version!'
        from /usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:49:in `run'
        from /usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
        from /usr/local/bin/pod:25:in `load'
        from /usr/local/bin/pod:25:in `<main>'
STILL NO SOLUTION...
```

```
Most recent flutter doctor:

timknogel@Tims-MacBook-Pro multiculturalapp % flutter doctor -v
[✓] Flutter (Channel stable, 2.10.5, on macOS 11.5.1 20G80 darwin-arm, locale en-ES)
    • Flutter version 2.10.5 at /Users/timknogel/FlutterDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (13 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/timknogel/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods.
      To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.66.2)
    • VS Code at /Users/timknogel/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
```
which ruby

/usr/bin/ruby
```
My machine: MacBook Pro (13-inch, M1, 2020) Mac OS big sur

Update 4.0 I updated Mac to Mac OS Monterey to install Roseta 2.0 https://github.com/flutter/flutter/wiki/Developing-with-Flutter-on-Apple-Silicon

```
sudo softwareupdate --install-rosetta --agree-to-license
Then I tried again:
```

`sudo gem uninstall CocoaPods`

```
brew install cocoapods 
brew link --overwrite cocoapods
```
Still same error.
`brew unlink cocoapods`

```
brew uninstall cocoapods`
sudo gem install CocoaPods`
```
Restarting IDE...

Same error.

Then I tried again with the standard ruby version and that failed again.

Flutter doctor

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 11.5.1 20G80 darwin-arm, locale en-ES)
• Flutter version 2.10.5 at /Users/timknogel/FlutterDev/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision 5464c5bac7 (11 days ago), 2022-04-18 09:55:37 -0700
• Engine revision 57d3bac3dd
• Dart version 2.16.2
• DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/timknogel/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.66.2)
    • VS Code at /Users/timknogel/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • 3253AB15-FB90-45F5-93CD-5A95FC029075 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2
      (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 100.0.4896.127
    ! Error: Failed to prepare device for development. This operation can fail if the version of the OS on the device is incompatible
      with the installed version of Xcode. You may also need to restart your mac and device in order to correctly detect compatibility.
      (code 806)

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

Flutter run -v result:

[flutter run v.txt](https://github.com/flutter/flutter/files/8602974/flutter.run.v.txt)

**Update 6.0 Git related?**

Referring to this post:
`https://github.com/CocoaPods/CocoaPods/issues/8661`

I installed git with homebrew just in case CocoaPods don't work because of the git version.

Before:

```
git --version
git version 2.32.0 (Apple Git-132)
```
1.) Install git by home-brew

After:

`brew install git`

`git --version`

git version 2.36.0
2.) change Path variables to:

zshrc File:

export PATH=$PATH:/Users/timknogel/FlutterDev/flutter/bin

export JAVA_HOME=$(/usr/libexec/java_home)

export PATHTWO="/usr/local/opt/ruby/bin:$PATH"

export PATHTHREE=/usr/local/bin

The last one is supposed to point to the git version, but I am unsure if I did it the right way... I have no idea about this path variables...

when I write in Android Studio Terminal

`git --version I get back:
`git version 2.36.0
So the terminal can consult the gitversion. Why can flutter not? I don't understand much about the PATH (es). But I am not sure if it's really related anyways, because I don't have the GIT name issue that is mentioned in the post.

3.) I tried to downgrade Cocapods to 1.10.2 but it still doesn't work.

Can somebody please help me out?I am not able to run a flutter app that has CocoaPods on my Mac M1 computer.

**Comment by dnkoutso** [comment]
Please see issue template. Flutter + CocoaPods issues are not currently accepted or investigated. Please remove Flutter and re-file issue or file an issue with Flutter repo.

**Comment by SportApps** [comment]
Hey! I don't understand, the flutter team sends me here and close my issue and here my issue is closed, too.

Great.

**Comment by dnkoutso** [comment]
Recently CocoaPods issue template was updated to denote that issues that include Flutter/ReactNative are too difficult to diagnose. See commit here: https://github.com/CocoaPods/CocoaPods/commit/dc91d3c22aedec8473594e87357d2c88f6952a8c

The best path forward is if you believe this is a cocoapods issue is to file a new issue including a sample app _without_ Flutter so you can show its indeed a cocoapods issue.

**Comment by dnkoutso** [comment]
You can use cocoapods without Flutter. Flutter uses a plugin/integration point with cocoapods.

Follow one of the cocoapods.org guides on how to setup a simple project with cocoapods.

**Comment by Alashiq** [comment]
@SportApps  did find any solution?
i faced the same problem,
i cant install cocoapods on mac m1

**Comment by stephen-fitzgerald** [comment]
I also have this issue, and have seen many comments about it online, but no solutions.  

I wiped my Mac HD reinstalled fresh OS, xcode, flutter etc and still have the issue.

Has anyone figured it out?

I'd be happy to create a non-flutter example if someone could show me how.

thanks,

Stephen

**Comment by monfresh** [comment]
When Flutter complains that Cocoapods is installed but not working, it's usually due to not having a proper Ruby development environment. Having a proper Ruby dev setup — that doesn't use the system Ruby that came preinstalled on your Mac — is a prerequisite for working with any project that depends on Ruby gems, such as Cocoapods.

Flutter can also complain due to having multiple instances of Cocoapods installed, and the `pod` executable that's first in the `PATH` is different from the one that's installed in the current active Ruby version. One common scenario is when you have Cocoapods installed both with Ruby as a gem, and with Homebrew.

One way to find out if Cocoapods is in your PATH, and where it's installed, is by running the command below:
```
which -a pod
```

If that returns any results, then try running `pod --version` to see if the `pod` executable works. If it doesn't return any results, that means you haven't set up your `PATH` properly. If you don't know how to do that, read my [step-by-step guide for installing Ruby on a Mac](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac).

The next thing you need to check is that when you are in the root of your Flutter project, you are using the correct version of Ruby. This is a common source of confusion for people who are new to Ruby. When you `cd` between different directories on your Mac, it's not guaranteed that the active Ruby version will be the same. 

You can check which version is active by running `ruby -v`. And you can find out where it's located with `which ruby`. If it says `/usr/bin/ruby`, that's the system Ruby that came preinstalled on your Mac, and you don't want that.

To make sure that each project is using the specific version of Ruby that it needs, the Ruby community agreed on a standard `.ruby-version` file that you place at the root of your project, and you populate this file with your desired Ruby version, such as `3.2.2`. This standard is recognized by all the major version managers: asdf, chruby, frum, rbenv, and rvm. 

When you have one of these version managers installed, they will automatically switch to the Ruby version defined in the `.ruby-version` file whenever you `cd` into a directory that contains a `.ruby-version` file. This assumes that the Ruby version defined in the file is already installed. If it's not already installed, these version managers make it easy to install multiple versions of Ruby at the same time.

## How to create a non-Flutter example
In order to create a non-Flutter example, you need to have a proper Ruby dev setup with a Ruby version installed using one of the version managers mentioned above. Then, you can create a non-Flutter example with these steps:

1. Create a dummy project for testing purposes and `cd` into it. I like to have a `playground` directory for testing things out:
   ```
   mkdir -p ~/playground/flutter-test && cd ~/playground/flutter-test
   ```
2. Add a .ruby-version file and populate it with one of the Ruby versions you installed with a version manager. We'll use the latest Ruby in this example: 3.2.2
    ```
    echo '3.2.2' >> .ruby-version
    ```
3. `cd` out of, and back into your test project, or switch to Ruby 3.2.2 manually. For example, if you're using `chruby` as your version manager, you would switch with `chruby 3.2.2`. The double check that 3.2.2 is the active version with `ruby -v`.
4.  Install Bundler
    ```
    gem install bundler
    ```
5. Create a Gemfile (this is the standard file for defining a Ruby project's dependencies):
    ```
    echo 'source "https://rubygems.org"' >> Gemfile
    ```
6. Add Cocoapods to it:
    ```
    bundle add cocoapods
    ```
7. Verify that Cocoapods can be used within the context of this project:
    ```
    bundle exec pod --version
    ```
