### ISSUE TITLE
Support for VisionOS 

### ISSUE THREAD

**Issue by gabrieldonadel** [CocoaPods/CocoaPods#11961]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

### PRs

- [x] Core - https://github.com/CocoaPods/Core/pull/745
- [x] CocoaPods - https://github.com/CocoaPods/CocoaPods/pull/11965
- [x] cocoapods-integration-specs - https://github.com/CocoaPods/cocoapods-integration-specs/pull/343
- [x] Xcodeproj - https://github.com/CocoaPods/Xcodeproj/pull/913

# Report

## What did you do?

- Run `pod init` inside a visionOS project

- Edit the Podfile to set visionOS as the selected platform
```
platform :visionos, '1.0'
```

- Run `pod install`

## What did you expect to happen?

CocoaPods show work just as in any other project

## What happened instead?

Invalid `Podfile` file: Unsupported platform `visionos`
<img width="981" alt="image" src="https://github.com/CocoaPods/CocoaPods/assets/11707729/efb704ae-0fd8-41c1-acac-17938c60883a">

### Stack

```
   CocoaPods : 1.12.1
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
    RubyGems : 3.4.10
        Host : macOS 13.4 (22F66)
       Xcode : 15.0 (15A5161b)
         Git : git version 2.39.2 (Apple Git-144)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.2.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :visionos, '1.0'

target 'react-native-visionOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for react-native-visionOS

  target 'react-native-visionOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by gabrieldonadel** [comment]
You may want to use `xros` also. Some internal code refer to visionOS as xros  
<img width="650" alt="image" src="https://github.com/CocoaPods/CocoaPods/assets/11707729/8608e4f1-a4c1-4c07-af34-68af430cff2e">

**Comment by renchap** [comment]
`xros` was the internal name during development, and not everything was renamed to `visionos` before the WWDC. VisionOS should be the named used everywhere now.

**Comment by marcpalmer** [comment]
My understanding is that in code terms it is staying as xros. e.g. `TARGET_OS_XROS` is, as advised by Apple engineers, the way to detect XROS at build time in ObjC code, and you must check this as well as TARGET_OS_IOS in some situations as the `TARGET_OS_IOS` is *also true* for XROS. I don't think all these are changing to VisionOS. They certainly haven't so far.

**Comment by Brett-Best** [comment]
SPM uses visionOS, https://developer.apple.com/documentation/packagedescription/platform/visionos

**Comment by gabrieldonadel** [comment]
I believe all the necessary PRs have been opened, please let me know if anything else is necessary 

- [x] Core - https://github.com/CocoaPods/Core/pull/745
- [x] CocoaPods - https://github.com/CocoaPods/CocoaPods/pull/11965
- [x] Xcodeproj - https://github.com/CocoaPods/Xcodeproj/pull/913

**Comment by dnkoutso** [comment]
@gabrieldonadel it happens kinda ad hoc with the free time of folks. No actual date. I do wish to land the SPM PRs that are open to add support for SPM dependencies into cocoapods.

It would be a good feature along side visionOS for a release as well as unblock Swift Macros (via SPM) for CocoaPods.

**Comment by abbana** [comment]
Thanks,
can you please give the procedure or at least a bit of more detail in pointing  master of CocoaPods/CocoaPods and CocoaPods/Core with bundler?

Will be highly appreciated.

**Comment by abbana** [comment]
For those who wonder how do that, hope the below will help:

After scraping from
https://bundler.io/guides/git.html
https://medium.com/@soxjke/bundler-is-a-best-friend-of-ios-developer-2fc80d9ee85f
https://stackoverflow.com/questions/71299074/in-a-rails-gemfile-how-do-i-reference-a-commit-from-a-pr
https://github.com/CocoaPods/Core/blob/master/Gemfile.lockhttps://github.com/CocoaPods/Core/commit/9320bf557741d7ae80eda4415bc6fb2b0b3a8b9c


0 - gem install bundler
1- Go to the root of the project , where the Podfile is located
2- Create Gemfile and put the below

# frozen_string_literal: true
gem 'cocoapods', git: 'https://github.com/CocoaPods/CocoaPods', ref: '400f290cb9269ea342948f629525a5542933627f'
gem 'cocoapods-core', git: 'https://github.com/CocoaPods/Core', ref: '9320bf557741d7ae80eda4415bc6fb2b0b3a8b9c'

3- execute bundle install
4- from now on use bundle exec pod install instead of pod install to install the pods


Bonus: use platform :visionos, '1.0' in Podfile , no upeercases

**Comment by mojavad** [comment]
Has this been released into Cocoapods? Still not recognising `visionos` after an update to my Cocoapods.

**Comment by futuretap** [comment]
How is this supposed to work for a target supporting both iOS and visionOS? The `platform` parameter only accepts one OS and specifying two `platform` lines fails with `The target `xyz` already has a platform set`.

**Comment by gabrieldonadel** [comment]
> How is this supposed to work for a target supporting both iOS and visionOS? The `platform` parameter only accepts one OS and specifying two `platform` lines fails with "The target xyz already has a platform set".

You can just create a different target for each platform

**Comment by futuretap** [comment]
Hm, but my main app target supports both iOS and visionOS. (Specifically, `SUPPORTED_PLATFORMS` is `iphoneos iphonesimulator xros xrsimulator`.) When I specify `MainApp_iOS ` and `MainApp_visionOS` as targets in the Podfile, how can it integrate those into my MainApp?

**Comment by Saadnajmi** [comment]
> @gabrieldonadel it happens kinda ad hoc with the free time of folks. No actual date. I do wish to land the SPM PRs that are open to add support for SPM dependencies into cocoapods.
> 
> It would be a good feature along side visionOS for a release as well as unblock Swift Macros (via SPM) for CocoaPods.

@dnkoutso Would it be possible to have a release with visionOS support sooner? That would make it easier for libraries to officially support visionOS rather than maintain a branch that targets cocoapods' master branch. I understand it's based on the free time of maintainers, I just wanted to express my desire for visionOS support sooner. 

Also, thank you to the cocoa pods team for continuing to maintain! I'm excited about SPM support in the future :D
