### ISSUE TITLE
Something went wrong running `pod install` in the `ios` directory.

### ISSUE THREAD

**Issue by erdincakdogan** [CocoaPods/CocoaPods#11973]
Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Invalid `Podfile` file: exit.

 #  -------------------------------------------
 #  
 >    use_react_native!(
 #      :path => config[:reactNativePath],
 #  -------------------------------------------

pod install --repo-update --ansi exited with non-zero code: 1

I dont know what is the problem in there. I tried to install with sudo command but didnt work.
when i run the yarn ios, this error coming.

**Comment by dnkoutso** [comment]
> WARNING: Please do not file issues for CocoaPods with projects 
that use React Native or Flutter. Please remove React Native or Flutter
in your sample app in order to properly demonstrate an issue with CocoaPods itself.
The integration between CocoaPods and React Native or Flutter 
makes it very difficult for us to diagnose and fix issues.
Issues with React Native or Flutter will be closed.
Please file React Native issues at https://github.com/facebook/react-native
and Flutter issues at https://github.com/flutter/flutter.
