### ISSUE TITLE
1.14.0 - requires new Ruby 2.7.4

### ISSUE THREAD

**Issue by khoogheem** [CocoaPods/CocoaPods#12122]
with 1.14.0 it won't install on Sonoma or other version of Mac as it requires Ruby 2.7.4 which is not part of the release notes

Would be nice be able to continue to use the standard setup on MacOS vs having to update all devices such as developers devices, build servers, etc..

**Comment by saldous** [comment]
I have the same issue, I just tried to update Cocoapods today and now it doesn't work: sudo gem install cocoapods

```
Fetching cocoapods-core-1.14.2.gem
Fetching cocoapods-downloader-2.0.gem
Fetching cocoapods-1.14.2.gem
ERROR:  Error installing cocoapods:
	**There are no versions of cocoapods-downloader (>= 2.0) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
	cocoapods-downloader requires Ruby version >= 2.7.4. The current ruby version is 2.6.10.210.**
```

**Comment by gokhanseckn** [comment]
I'm also having the same issue. I can't install Cocoapods on Sonoma.

**Comment by sudhakar-varma** [comment]
Facing same issue. I can't install Cocoapods on Sonoma.

**Comment by masterwok** [comment]
I also just ran into this issue after upgarding to Sonoma. 

I'm trying to update cocoapods so I can resolve the following [[issue](url)](https://github.com/CocoaPods/CocoaPods/issues/12012):

```
error: DT_TOOLCHAIN_DIR cannot be used to evaluate LD_RUNPATH_SEARCH_PATHS, use TOOLCHAIN_DIR instead (in target 'Pods-Runner' from project 'Pods')
error: DT_TOOLCHAIN_DIR cannot be used to evaluate LD_RUNPATH_SEARCH_PATHS, use TOOLCHAIN_DIR instead (in target 'Runner' from project 'Runner')
error: DT_TOOLCHAIN_DIR cannot be used to evaluate LD_RUNPATH_SEARCH_PATHS, use TOOLCHAIN_DIR instead (in target 'Flutter Assemble' from project 'Runner')
error: DT_TOOLCHAIN_DIR cannot be used to evaluate LIBRARY_SEARCH_PATHS, use TOOLCHAIN_DIR instead (in target 'Flutter Assemble' from project 'Runner')
```

Below is the output from attempting to upgrade on macOS 14.1:

```
> sudo gem install cocoapods
ERROR:  Error installing cocoapods:
        There are no versions of cocoapods-downloader (>= 2.0) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
        cocoapods-downloader requires Ruby version >= 2.7.4. The current ruby version is 2.6.10.210.
```

```
> ruby --version
ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin23]
```

```
> brew install ruby
Warning: ruby 3.2.2_1 is already installed and up-to-date.
To reinstall 3.2.2_1, run:
  brew reinstall ruby
```

**Comment by MinhLuongNeo** [comment]
You just need to install the older pod version:
sudo gem install cocoapods -v 1.13.0

Bonus:
You may also need to unistall cocoapod before reinstalling:
sudo gem uninstall cocoapods

**Comment by masterwok** [comment]
@MinhLuongNeo why use an older pod version since updating to latest resolves the issue and is possible on Sonoma?

**Comment by saldous** [comment]
Why was the requirement changed and not documented?

**Comment by sochalewski** [comment]
According to [the official guides](https://guides.cocoapods.org/using/getting-started.html#getting-started) _CocoaPods (…) will be installable with the default Ruby available on macOS. You can use a Ruby Version manager, however we recommend that you use the standard Ruby available on macOS (…)._ Unfortunately it's no longer true since 1.14.1. I hope this will be fixed in the future.

cc @amorde to draw attention 🙏

**Comment by saldous** [comment]
When will you fix this??

**Comment by monfresh** [comment]
Unfortunately, the official advice to install cocoapods with `sudo` using the default Ruby available on macOS is not the best practice recommended by the Ruby community. It is much safer and more reliable to install a separate version of Ruby using a Ruby installation tool/version manager such as ruby-install, rbenv, asdf, or rvm. Here are a few articles that explain why using the system Ruby is a bad idea:

https://www.moncefbelyamani.com/why-you-shouldn-t-use-the-system-ruby-to-install-gems-on-a-mac/ (mine)
https://dontusesystemruby.com/#/ (not mine)

The version of Ruby that comes with macOS is 2.6.10, which reached end of life almost 2 years ago. I'm not speaking for the Cocoapods team, but it's perfectly reasonable for them to stop supporting such old versions. Even Ruby 2.7 reached end of life earlier this year. However, I agree that the fact that this breaking change is not documented in the Cocoapods changelog or in the cocoapods-downloader changelog is not great.

Also, it's not guaranteed that Apple will continue to preinstall Ruby on macOS. A while back, they said that they might stop preinstalling certain scripting languages, and they removed Python in Monterey (macOS 12.3).

So, I highly recommend that people learn how to use a Ruby version manager. My personal preference is chruby with ruby-install, and I've written a [step-by-step guide for installing Ruby on a Mac](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/). I hope it helps!

**Comment by saldous** [comment]
@monfresh 
I tried following the guide, it's incredible complicated and involved... and I got all the way through ok and at the end I still get errors. and Ruby on Mac app is incredibly expensive for a solo dev.

Cocoapods team that introduced this breaking change and didn't document it needs a slap on the wrist and to fix it back to the default MacOS Ruby version, as per their docs, and better plan for such a change in the future.

😡😡😡

**Comment by amorde** [comment]
Hey folks - apologies for the mishap here. I thought the last few releases of macOS were on 2.7 but apparently even macOS Sonoma still only includes 2.6.

I was rushing to release 1.14 so that we could ship the fix for https://github.com/CocoaPods/CocoaPods/issues/12081 and was having issues supporting both newer versions of Ruby & external dependencies and the older 2.6 Ruby versions. At the time it was blocking me from releasing. There's a chance I could figure out a path to re-adding 2.6, but for now I've updated the release notes of 1.14.0 to include a note about dropping support for 2.6.

As @monfresh mentioned, even 2.7.4 is EOL. Supporting older versions along with newer versions of Ruby can be quite challenging when external dependencies have specific Ruby version requirements.

> Cocoapods team that introduced this breaking change and didn't document it needs a slap on the wrist and to fix it back to the default MacOS Ruby version, as per their docs, and better plan for such a change in the future.

Respectful reminder that we do this in our free time and have full time jobs. CocoaPods is receiving very little contributions at the moment, and all of our time is going into keeping the lights on so people relying on it can still use it. If you rely on CocoaPods perhaps it would be worth investing some time into making your dev setup more robust by decoupling yourself from system ruby and using bundler so you don't need to wait for a specific CocoaPods release to pull in a bug fix.

**Comment by saldous** [comment]
@amorde thank you, sorry for the rant, I appreciate all the Cocoapods team do. Note: you should also update this on your website: https://guides.cocoapods.org/using/getting-started.html#installation
<img width="978" alt="image" src="https://github.com/CocoaPods/CocoaPods/assets/3334306/533ec53a-20dc-4398-9772-f2c552340e8d">

**Comment by markhu** [comment]
This combo seems to be a workaround for now.

```
activesupport (6.1.7.6)
cocoapods (1.13.0)
```

**Comment by amorde** [comment]
Those docs should 100% be updated given where we are today.  Especially since Apple plans to remove Ruby from macOS entirely at some point in the future

**Comment by amorde** [comment]
Fixed 1.14.3. Let me know if there are still issues running on system Ruby.

**Comment by elvsp1n** [comment]
Try upgrading ruby before installing cocoapods with:
```
brew install ruby
echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.zshrc
echo 'export LDFLAGS="-L/usr/local/opt/ruby/lib"' >> ~/.zshrc 
echo 'export CPPFLAGS="-I/usr/local/opt/ruby/include"' >> ~/.zshrc
. ~/.zshrc
ruby -v
sudo gem install cocoapods
# Optional
# At the moment of writing, there seems to be an update for the gems, apply it with the following
sudo gem update --system 3.5.9
```
Cheers,
EE

**Comment by frankpape** [comment]
I'm not sure if the above response is outdated, or if there's something different about my configuration, but with a fresh install of homebrew on a fresh install of MacOS 14.3, `brew install ruby` does not install to `/usr/local/opt/ruby/` but rather `/opt/homebrew/opt/ruby/`, so those paths will need to be updated.

**Comment by monfresh** [comment]
On an Apple Silicon Mac, Homebrew installs things in `/opt/homebrew`, but on Intel Macs (or if you use Rosetta on an Apple Silicon Mac), it will use `/usr/local`.

Also, setting env vars like `LDFLAGS` and `CPPFLAGS` globally in your ~/.zshrc is highly discouraged because those flags can affect installation of various development tools. It's also absolutely not necessary when you have a proper Ruby development environment.

I personally recommend installing Ruby with a version manager, and not with Homebrew because Homebrew limits you to one Ruby version at a time, and you can only install specific versions. I've written in detail about [the various ways you can install Ruby on a Mac](https://www.moncefbelyamani.com/the-definitive-guide-to-installing-ruby-gems-on-a-mac/), and here's my [step by step guide for installing Ruby on a Mac](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/) with a version manager.

Finally, you should [never use sudo to install gems](https://www.moncefbelyamani.com/why-you-should-never-use-sudo-to-install-ruby-gems/). I've been working with Ruby for 12+ years, and not once have I ever had to use `sudo` to install a Ruby gem.
