### ISSUE TITLE
can't download Cocoapods

### ISSUE THREAD

**Issue by elroi8** [CocoaPods/CocoaPods#12327]
Part of the work for my project I need to install cocoapods
Unfortunately, I run into a problem that every time I put in the terminal the command - "sudo gem install cocoapods"
" and pressing the password nothing happens after that

I have a Mac computer with the newest version of iOS. I have tried until now to solve it by forums on the Internet, Apple's support center, and with the help of chatGPT, but nothing helped.

please help me

**Comment by elroi8** [comment]
@monfresh 
I did the guide and this is the message I got-



elroiadmin@lrwys-MacBook-Air ~ % gem install cocoapods

ERROR:  Error installing cocoapods:
	The last version of activesupport (>= 5.0, < 8) to support your Ruby & RubyGems was 6.1.7.7. Try installing it with `gem install activesupport -v 6.1.7.7` and then running the current command again
	activesupport requires Ruby version >= 2.7.0. The current ruby version is 2.6.10.210.
elroiadmin@lrwys-MacBook-Air ~ % x

**Comment by monfresh** [comment]
@elroi8 Make sure you follow the entire guide and don't skip any steps. You're still using the system Ruby because it says "The current ruby version is 2.6.10.210."

If you followed the guide carefully, when you quit and relaunch your terminal, if you run `ruby -v`, it should say `3.3.0`. If not, try switching manually like this:

```
chruby 3.3.0
```

Then run `ruby -v` to confirm that you're using version 3.3.0.

I also recommend carefully reading the sections called [How to install different versions of Ruby and switch between them](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/#how-to-install-different-versions-of-ruby-and-switch-between-them) and [Recommended way to automatically switch to the correct version](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/#recommended-way-to-automatically-switch-to-the-correct-version).

**Comment by MANIKANDAN1709** [comment]
I Also faced the same issue I am currently using the macOS  ```14.4.1 (23E224)``` version and ruby ```2.6.10p210``` (2022-04-12 revision 67958) [universal.arm64e-darwin23] which comes by default with MacOS.When I try to install Cocopods using both the sudo and  sudo-less methods, the installation fails due to some dependencies of Cocopods that require the higher version.So I upgraded the Ruby version with the help of ```rbenv``` and solved the issue.

Step 1: install ```rbenv``` using Home Brew.

```brew install rbenv ruby-build```

Step 2: Setting PATH for rbenv in ```~/.zshrc```
```
#Setting PATH for rbenv
eval "$(rbenv init - zsh)"
```
Step 3 : Set the default Ruby version for this machine
```rbenv global 3.1.2: ```

Step 4:  Restart the terminal, check the ruby version and install Cocopods.

**Comment by elroi8** [comment]
Thank you very much, I finally overcame the problem by using the latest technology instead of the cocoapods‫ב-8 באפר׳ 2024, בשעה 6:22, ‏‏MANIKANDAN SAMINATHAN ***@***.***> כתב/ה:‬﻿
I Also faced the same issue I am currently using the macOS  14.4.1 (23E224) version and ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin23] which comes by default with MacOS.When I try to install Cocopods using both the sudo and  sudo-less methods, the installation fails due to some dependencies of Cocopods that require the higher version.So I upgraded the Ruby version with the help of rbenv and solved the issue.
Step 1: install rbenv using Home Brew.
brew install rbenv ruby-build
Step 2: Setting PATH for rbenv in ~/.zshrc
#Setting PATH for rbenv
eval "$(rbenv init - zsh)"

Step 3 : Set the default Ruby version for this machine
rbenv global 3.1.2: 
Step 4:  Restart the terminal, check the ruby version and install Cocopods.
