### ISSUE TITLE
REXML version 3.2.x DoS vulnerability

### ISSUE THREAD

**Issue by dinhnhat0401** [CocoaPods/CocoaPods#12530]
# Report

## What did you do?

ℹ Please replace these two lines with what you did.  

bundle install

```
gem "rexml", ">= 3.3.2"
```

## What did you expect to happen?

it should be able to resolve. => Need to upgrade dependency for Rexml to 3.3.x

## What happened instead?

```
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
Could not find compatible versions

Because cocoapods >= 1.13.0 depends on xcodeproj >= 1.23.0, < 2.0
  and xcodeproj >= 1.20.0 depends on rexml ~> 3.2.4,
  cocoapods >= 1.13.0 requires rexml ~> 3.2.4.
So, because Gemfile depends on cocoapods ~> 1.15.2
  and Gemfile depends on rexml >= 3.3.2,
  version solving has failed.
```

## CocoaPods Environment

pod 1.15.2

## Project that demonstrates the issue

not relevance

**Comment by monfresh** [comment]
In order to be able to update rexml to greater than or equal to 3.3.2, all of the project's dependencies must be satisfied. As explained in the Bundler error message, the current combination of dependencies does not allow rexml to be greater than 3.2.x. 

The `rexml` dependency comes from `xcodeproj`, so it's the maintainers of `xcodeproj` that need to release a new version that allows `rexml` to be greater than 3.2.x. And in fact, they just released version 1.25.0 today that requires rexml 3.3.2 or greater: https://rubygems.org/gems/xcodeproj/versions/1.25.0

So, to update rexml in your project, you can comment out the `rexml` line in your Gemfile, then run `bundle update xcodeproj`, which should bump it up to version 1.25.0, and it should also update rexml to >= 3.3.2

Here's an article that can help you better understand how Ruby gems and Bundler work to resolve dependencies:

https://www.rubyonmac.dev/cocoapods-rexml-parse-exception
