### ISSUE TITLE
source_files does not find files specified with .. in relative path

### ISSUE THREAD

**Issue by MaxGabriel** [CocoaPods/CocoaPods#1259]
#### Summary

The `source_files` attribute does not match relative paths using `..`, e.g. `../Classes/ExampleLib.{m,h}`
#### Report
- What did you do?

Ran `pod install` on a Podspec that located its `source_files` using a relative path, `"../Classes/ExampleLib.{m,h}"`.
- What did you expect to happen?

`pod install` installed the source files into the Xcode project
- What happened instead?

`pod install` didn't install the source files, though it did create Pods targets, dummy files, xcconfig files, etc.
#### Details

Initially @dstumm had this issue when using the path `../GraphicServices.framework` for the `vendored_frameworks` attribute, and I replicated the issue in the [Cocoapods Example Library](https://github.com/CocoaPods/CocoaPodsExampleLibrary) for the regular `source_files` attribute. The [example project replicating the issue is here](https://github.com/MaxGabriel/RelativePathInCocoapods). (You'll need to `pod install` from within the `Example/` directory to replicate).
#### Stack

Cocoapods: I replicated this issue on 0.22.3 and 0.23.0.rc1
Ruby: ruby 1.9.3p327 (2012-11-10 revision 37606) [x86_64-darwin12.3.0]
RubyGems: 1.8.25
OS: OS X 10.8.4 Build 12E55
Xcode: 4.6.3 (4H1503)
#### Podfile

``` ruby
Pod::Spec.new do |s|
  s.name         =  'ExampleLib'
  s.version      =  '1.0'
  s.license      =  { :type => 'MIT', :file => '../LICENSE' }
  s.homepage     =  'http://github.com/orta/ExampleLib'
  s.authors      =  { 'orta' => 'orta.therox@gmail.com' }
  s.source       =  { :git => 'https://github.com/orta/ExampleLib.git', :tag => s.version.to_s }

  s.summary      =  'Just a simple podspec, no working code.'
  s.description  =  'Just a simple podspec for 2 files.'

  s.source_files = "../Classes/ExampleLib.{m,h}"
end
```
#### Contents of `pod lib lint`

``` sh
 -> ExampleLib (1.0)
    - WARN  | The description is shorter than the summary.
    - ERROR | The `source_files` pattern did not match any file.

[!] ExampleLib did not pass validation.
```

**Comment by Usipov** [comment]
You can save much time to many developers if you add some kind of a warning about this unintuitive behaviour
> the parent directory isn't supported

**Comment by sirghi** [comment]
Here is a use-case I hope you'll find valid:
We're developing a framework to be distributed as a binary. We have the main (private) repo containing a framework project with the source code, and a folder inside it is organized as a submodule which points to a public repo, which contains the built framework, a demo app, and the podspec so that consumers would point to the public repo to use it.

To ease development/testing, I want to just change the line in the podspec saying `s.vendored_frameworks = ...` to `s.source_files = '../Source/*.swift'` to reference the sources from the parent directory (and repository).

So please, please fix this.

**Comment by sweetwilma** [comment]
Ran into this same issue today. Would really like to have this working, without excuses of how it "should" be done.

**Comment by apecoraro** [comment]
Another use case - we have two different podspec files, one for iOS, one for macOS, and thus two different pod repo root directories, but the code for them is the same. Would rather not have to duplicate the code.

**Comment by llOldmenll** [comment]
Was any workaround found so far?

**Comment by zengyun-hacker** [comment]
I met the same situation here too. I have a base framework relied by both two pods, if cocoapods supports parent directory, the file tree will be more elegant

**Comment by AsteriskZuo** [comment]
This need is normal and should not be shut off or ignored.
For example: my code runs on multiple platforms, Android, ios, MAC, Win, etc. I need to put my c++ code in the root directory, not my PodSpec.

**Comment by avently** [comment]
Found this issue after hours trying yo figure out how to make relative path to resources work. But looks like so easy thing is not implemented for years, even symlinks. It's bad. However, there is a solution that I found (not sure how easy would be to you to adapt it to `source_files` instead of `resources`, but you could try at least). I just made another podspec file and placed it at a level higher, then connected it into Podfile as a different pod.
`Podfile:`
```
target 'ios' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'main', :path => '../main'
  pod 'resources', :path => '..'
end
```
I added `pod 'resources', :path => '..'` here.

And `resources.podspec` on a level higher (parent dir where all code located)
```
Pod::Spec.new do |spec|
    spec.name                     = 'resources'
    spec.version                  = '1.0.0'
    spec.homepage                 = 'https://example.com'
    spec.source                   = { :http=> ''}
    spec.authors                  = ''
    spec.license                  = ''
    spec.summary                  = 'Shared resources'
    spec.ios.deployment_target = '14.1'
    spec.resources = ['common/src/commonMain/resources/**']
end
```

This allows to copy resources from where I have it to the resulting iOS app. Without changing sources root, copying, etc.

For devs of Cocoapods:
This feature is really needed. If I had to spend a couple of hours here, multiply it to hunders (or thousands) of developers who have similar experience, you'll notice the problem.

**Comment by PeteClubSeven** [comment]
There is a great irony that https://cocoapods.org/about actually says "Get on with building your app, not duplicating code". In that spirit it should be clear that this should be supported. I'm developing a multi-platform FFI plugin using Flutter and it absolutely baffles me that I can't do something as simple as reference multi-platform source code in a parent directory.
