### ISSUE TITLE
Resource bundle Info.plist

### ISSUE THREAD

**Issue by 0xced** [CocoaPods/CocoaPods#1264]
Congrats on the new resource bundle thing, it’s awesome. :sunglasses: 

I think it’s just missing one thing: the `Info.plist` file. Like all bundles, a resource bundle should also have an Info.plist. Unless I’m missing it, I don’t see a way to specify it in a podspec.

Note that you can’t add the Info.plist as a resource since it must be processed by Xcode to replace variables, such as

``` xml
<key>CFBundleName</key>
<string>${PRODUCT_NAME}</string>
```

It must be added as the `INFOPLIST_FILE` build setting in order to be processed.

How could we add that, something like this ?

``` ruby
spec.resource_bundle = {
    'LibraryName' => {
        :resources => 'LibraryName/Resources/*.png',
        :info_plist => 'LibraryName/Resources/LibraryName-Info.plist'
    }
}
```

**Comment by DarkDust** [comment]
We'd also like to either specify an Info.plist for a resource bundle or modify the resource bundle's xcconfig (which doesn't exist yet). The way resource bundles are treated right now is just too limited; we can just specify files and that's it.

The underlying issue we really want to solve is that one of our projects cannot be built on our build server any more since we switched to CocoaPods. The reason is that the build server specifies a custom `CODE_SIGN_IDENTITY` as argument to `xcodebuild` so normal developers can build with their certificates but official builds are signed with our public certificate. However, when you're overwriting this setting, `xcodebuild` tries to sign all targets which fails for the resource bundle. The solution is to either specify `CODE_SIGNING_ALLOWED=NO` for the resource bundle target or provide a minimal `Info.plist`. Neither is currently possible with CocoaPods.

**Comment by segiddins** [comment]
@DarkDust both are possible using your podfile's post install hook.

**Comment by DarkDust** [comment]
@segiddins …which I would have to do in every project that uses the pod. The right place to fix this is the pod spec, IMHO. We've worked around this by providing the resource bundle manually and using `resources` instead of `resource_bundles`. I just fail to see the point of `resource_bundles` at the moment as it offers no value over `resources` that I'm aware of.

**Comment by 0xced** [comment]
> @0xced Can you provide usage case examples for the Info.plist file in a resource bundle?

I’m a bit late on this one, but if you want to use xcassets in a resource bundle, you **must** have an Info.plist (with a bundle identifier) else you won’t be able to use your assets at all.

**Comment by mrtj** [comment]
Another use case of Info.plist in resource bundle is to define the bundle identifier (`CFBundleIdentifier`) that can be used for cached loading of the bundle with `+[NSBundle bundleWithIdentifier:]`

**Comment by rwtemple** [comment]
I'm having the same problem as 0xced, I need the Info.plist in order to get the assets working

**Comment by spitfire2903** [comment]
I'm having troubles with localizations. I have a main project, and others development projects that are pods. Also I have to use the 'use_framework' flag to compile my project. The only way the localizations worked is changing the auto generated Info.plist of the development projects. How cocoapods generate this Info.plist? I need to add the 'CFBundleLocalizations' key in the development pod.
