### ISSUE TITLE
Don't flat directory recursively when used "header_mappings_dir" config in specification

### ISSUE THREAD

**Issue by larrytin** [CocoaPods/CocoaPods#1437]
See https://github.com/CocoaPods/Specs/blob/master/jre_emul/0.8.6.1/jre_emul.podspec

When use 
```ruby
jre.header_mappings_dir = 'dist/include' 
and remove these two lines 
jre.preserve_paths = 'dist/include/**/*.h' 
jre.xcconfig = { 'GCC_WARN_MISSING_PARENTHESES' => 'NO', 'HEADER_SEARCH_PATHS' => '"${PODS_ROOT}/jre_emul/dist/include"' }
```

It will flat header search paths "dist/include" as "dist/include dist/include/java dist/include/java/lang ...", so causing "Cannot find interface declaration for NSobject" compilation error.

**Comment by segiddins** [comment]
@neonichu want to fix this?

**Comment by jcanizales** [comment]
For those finding themselves trapped by this problem like I did, a workaround is explained here: https://groups.google.com/forum/#!searchin/cocoapods/header$20directories$20recursively/cocoapods/6V4qL571wgQ/e1v3OO2IzKMJ

**Comment by toddreed** [comment]
I think @jbmorley's comment that "there might be some merit to a podspec option to only include the top-level directory" is a massive understatement. I'd argue this should actually be the default and the current behaviour should be an option. Given that CocoaPods' raison d'être is to integrate multiple projects, it should default to doing this in a way that avoids conflicts. But the default behaviour of including every single directory in the include search path does the opposite.

The real-life example that I'm currently struggling with is including the [Eigen C++ library](http://eigen.tuxfamily.org/index.php?title=Main_Page) (for which I have a Podspec in a private repository). Eigen happens to have header files named `Block.h` and `Complex.h` (which Eigen itself only includes via #include "" with explicit paths). Both of these happen to be names of system headers that get included via `#include <block.h>`  and `#include <complex.h>` when including `<Foundation/Foundation.h>`. Consequently, just about everything fails to compile because `#include <Foundation/Foundation.h>` causes `#include <block.h>` to include Eigen's `Block.h` instead of the system's `block.h`. (Another example I recall reading about was including two Pods that both had a `config.h` file.)

My opinion is that almost all of CocoaPods' defaults related to header files are the wrong choice:

- Only top-level include directories should be added the path.
- The Podspec option `header_dir` should be mandatory or default to the project name. This effectively creates a header namespace for each project.
- `USER_HEADER_SEARCH_PATHS` should be updated instead of `HEADER_SEARCH_PATHS` to avoid conflicts with system headers. (A user library or third-party library is not a system library, so it should not be included via `#include <>` but rather `#include ""`.)

**Comment by ronen** [comment]
> The real-life example that I'm currently struggling with is including the Eigen C++ library (for which I have a Podspec in a private repository)

@toddreed  I'm in the midst of struggling with Eigen C++ myself, likewise for a private repo.  Did you ever get it to work?  Any hints?   Thanks  [This is arguably off-topic for this issue, feel free to respond by email.]

**Comment by jcanizales** [comment]
My current workaround, which would work for any library, is the uber hack of renaming the conflicting headers and editing the lines where they are included, in [my prepare_command](https://github.com/grpc/grpc/blob/master/gRPC.podspec#L48).

**Comment by toddreed** [comment]
Ronen,

Here is my custom Podspec that I’m using:

> Pod::Spec.new do |s|
>   s.name        = "io.rsi.eigen"
>   s.version     = "3.2.4"
>   s.summary     = "Eigen is a C++ template library for linear algebra: matrices, vectors, numerical solvers, and related algorithms."
>   s.homepage    = "http://eigen.tuxfamily.org/"
>   s.license     = { :type => "Mozilla Public License v2", :file => "COPYING.README" }
>   s.author      = "Benoît Jacob", "Gaël Guennebaud"
>   s.source      = { :hg => "https://bitbucket.org/eigen/eigen", :revision => "3.2.4" }
>   s.preserve_paths = 'Eigen/*', 'Eigen/**/*'
>   s.ios.deployment_target = "8.0"
>   s.osx.deployment_target = "10.10"
> 
>   s.compiler_flags = '-DEIGEN_MPL2_ONLY'
> 
>   s.xcconfig = {
>     'CLANG_CXX_LANGUAGE_STANDARD' => 'c++14',
>     'CLANG_CXX_LIBRARY' => 'libc++',
>     'USER_HEADER_SEARCH_PATHS' => '"${PODS_ROOT}/io.rsi.eigen"'
>   }
> end


I think what got this working for me was to set USER_HEADER_SEARCH_PATHS instead of HEADER_SEARCH_PATHS. (Also, I originally called this spec Eigen in my private repo, but then later someone added an Eigen Podspec to the public Podspec repository, which led to warnings when running pod. This led me to adopt the practice of prefixing all my private Podspecs with io.rsi (i.e. a reverse domain, à la Java’s package naming convention).)

Hope this helps.

— Todd

**Comment by ronen** [comment]
Thanks!  I'll give it a shot.

-r


Todd Reed wrote:

**Comment by schwa423** [comment]
I have a similar problem when compiling a C++ codebase that has a "time.h" file that includes the system "time.h".  Or it tries to, but can't because CocoaPods sets up the header search paths so that it includes itself.

I just tried toddreed's suggestion.  Unfortunately, it doesn't seem to work with a .podspec.json... when I add an "xcconfig" section like so:

  "xcconfig": {
    "CLANG_CXX_LANGUAGE_STANDARD": "c++14",
    "CLANG_CXX_LIBRARY": "libc++",
    "HEADER_SEARCH_PATHS": "${PODS_ROOT}/MyPodName/include"
  },

... instead of using the paths that I gave it, instead defines a new "User-Defined Variable" in XCode, and adds it to the end of the search paths:

PODS_MYPODNAME_HEADER_SEARCH_PATHS = ${PODS_ROOT}/MyPodName/include

As a result, the library's version of "time.h" continues to include itself.

I suppose I have two courses of action to try:
- change to a Ruby podspec
- use "sed" in my "prepare_command" to strip "PODS_MYPODNAME_" out from the .xcconfig

**Comment by jcanizales** [comment]
Hi Josh,

since you're fighting the same library as I was, you can do [the same thing I did](https://github.com/grpc/grpc/blob/master/gRPC.podspec#L48): use the `prepare_command` of your podspec to rename `time.h` as `grpc_time.h` and `string.h` as `grpc_string.h`.

**Comment by schwa423** [comment]
Well, that's a lucky coincidence :-)  Thanks!

**Comment by jogu** [comment]
This is causing me massive pain too, trying to write a pod spec for mupdf - this has a fitz/math.h file, and also headers that #include <math.h>.

The stumbling block is CocoaPods seems to insist on adding the fitz/ directory into HEADER_SEARCH_PATHS meaning the #include <math.h> picks up the wrong math.h. (The fitz/ header doesn't need to be on the include path at all, as the parent directory is and everyone that wants that math.h uses #include "fitz/math.h").

It would be great if this behaviour of adding the subdirs to the include path could be made optional when header_mappings_dir has been set.

I'm going to try the above workarounds, but I believe neither of them work when using :path to refer to the pod spec which makes testing harder.

**Comment by jogu** [comment]
I used an alternative workaround which I think is working:

    s.preserve_paths = "include/*", "include/**/*"
    s.xcconfig = {
       'USE_HEADERMAP' => 'NO',
       'HEADER_SEARCH_PATHS' => '"$(PODS_ROOT)/Target Support Files/Pods"',
       'USER_HEADER_SEARCH_PATHS' => '"${PODS_ROOT}/MuPDF/include"',
    }

I'm not 100% sure if the USE_HEADERMAP and HEADER_SEARCH_PATHS changes are still necessary (I've run into another issue which I need to solve before I can fully test...).

**Comment by nicolasnoble** [comment]
Is there any actual action that happens on the bug, or is this issue going to be only for people to list their workarounds on it ?

**Comment by segiddins** [comment]
We plan to fix it, but anyone is free to submit a pull request!

**Comment by ashoemaker** [comment]
Using `header_mappings_dir` to preserve the directory structure of headers for a third-party library, and unable to prevent CocoaPods from adding a header search path for all the intermediate directories.

This flattens the header namespace, leading to unexpected collisions. For example, what should only be include-able via `#include <library/subfolder/stdint.h>` now aliases the system-provided `#include <stdint.h>`.

Any idea how to prevent `library/subfolder` from getting added as a header search path? Thanks.

**Comment by segiddins** [comment]
@ashoemaker that's why this issue is open ;) PRs to fix it are welcome!

**Comment by jogu** [comment]
@ashoemaker See http://stackoverflow.com/a/31234707/292166 for an example of a full pod spec that works around this.
