### ISSUE TITLE
Error: can't modify frozen String

### ISSUE THREAD

**Issue by franciscomxs** [CocoaPods/CocoaPods#1444]
I am using cocoapods with rubymotion. If i add the gem to the project, it raises this error.

There is a part of my project: https://gist.github.com/franciscomxs/6855012

 The error appears when i add the gem, even if i don't really use it.

I have tried with a clean install of ruby 2.0 and 1.9.3.

**Comment by 0wnrepo** [comment]
I have this issue. 

### Report

* Installed cocoapods beta with -pre. Uninstalled it because my pod install didn't work link_with issue.

* What happened instead? It broke.

```
me-Mac-mini:acmacos stefan$ pod install
[!] Unable to load a specification for the plugin `/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-deintegrate-1.0.0.beta.1`
Updating local specs repositories

CocoaPods 1.0.0.beta.4 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
[!] Unable to load a specification for the plugin `/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-deintegrate-1.0.0.beta.1`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]
    RubyGems : 2.5.1
        Host : Mac OS X 10.10.2 (14C109)
       Xcode : 6.4 (6E35b)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5bd27d68d932d15fedbfa19dbba5d4125a06ecb1
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :osx, '0.9'
inhibit_all_warnings!

xcodeproj 'x'
link_with 'x'

pod 'Typhoon', '~> 3.0.2'
pod 'PLCrashReporter', '~>1.2.0'

target 'xTests', :exclusive => true do
  pod 'OCMock'
end
```

### Error

```
RuntimeError - can't modify frozen String
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:405:in `block (2 levels) in handle_resolver_error'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:402:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:402:in `block in handle_resolver_error'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:376:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:376:in `handle_resolver_error'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:69:in `rescue in resolve'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:57:in `resolve'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=can%27t+modify+frozen+String&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!
```

**Comment by segiddins** [comment]
@0wnrepo that's a separate issue that has been fixed in Molinillo already. Run `gem install molinillo` and in future please don't comment on closed issues.

**Comment by 864764448** [comment]
Excuse me, how to solve this problem？

**Comment by koraktor** [comment]
@864764448 I was able to fix this with `gem install --pre cocoapods`.

**Comment by SamuelZhaoY** [comment]
I had the similar issue on my side:

`FrozenError - can't modify frozen String
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/validator.rb:335:in `rescue in perform_extensive_analysis'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/validator.rb:301:in `perform_extensive_analysis'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/validator.rb:87:in `validate'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command/spec/lint.rb:70:in `block in run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command/spec/lint.rb:57:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command/spec/lint.rb:57:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=can%27t+modify+frozen+String&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Error: can't modify frozen String
   https://github.com/CocoaPods/CocoaPods/issues/1444 [closed] [7 comments]
   06 May 2016
`

The podspecs is in correct format, one week ago the specs are still passing.  Just wonder is there any environment issue which cause this error?

**Comment by lizishiye** [comment]
Have you solved this problem?

**Comment by FrankQj** [comment]
@SamuelZhaoY   Has your problem been solved?  And how?

**Comment by onezens** [comment]
> @SamuelZhaoY Has your problem been solved? And how?

I Fix it by `gem install cocoapods `

**Comment by ziedagoubi** [comment]
facing same issue here too

**Comment by chika-kasymov** [comment]
@ziedagoubi JFYI for me it was the broken `.pbxproj` file after GIT merge. After resolving issues with the Xcode project file the Cocoapods installation succeeded.

**Comment by ziedagoubi** [comment]
@chika-kasymov yes it appears to me too that it was caused by .pbxproj after git rebase :) 
thank you anyway

**Comment by banuharshavardhan** [comment]
@chika-kasymov , how to resolve `.pbxproj` , I'm not seeing any conflicts in that file, but it's not opening in Xcode, saying `The project ‘<NAME>’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.
Path: /Users/bjakkamputi/Desktop/Repositories/<NAME>/<NAME>.xcodeproj`

**Comment by chika-kasymov** [comment]
> @chika-kasymov , how to resolve `.pbxproj` , I'm not seeing any conflicts in that file, but it's not opening in Xcode, saying `The project ‘<NAME>’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts. Path: /Users/bjakkamputi/Desktop/Repositories/<NAME>/<NAME>.xcodeproj`

It's hard to tell without seeing the file. In my experience, such things happen after an invalid merge. For example, an extra or missing symbols like `)`, `}`, `;` and similar. If you did merge or automerge, then just try to redo it manually again but being more careful.

**Comment by banuharshavardhan** [comment]
Thank you so much @chika-kasymov , it worked. I have missed one opening flower brace `{`.
