### ISSUE TITLE
Local Podspecs doesn't get updated

### ISSUE THREAD

**Issue by rivera-ernesto** [CocoaPods/CocoaPods#1623]
I noticed that modified local podspecs (`:path => '../Local/Path'` in Podfile) stored in `Pods/Local Podspecs` don't get properly updated by `$ pod install`.

CocoaPods should either:
- Check for newer versions of the local podspec and overwrite them in `Pods/Local Podspecs`.
- Sym link local podspecs so they are always up to date.

**Comment by afshin-hoseini** [comment]
I faced this issue and found my own solution since others didn't help me.
In demo project's navigation under `Pods/Products`, right click the `.framework` files and select show in finder. Then remove them. After that build the library project and then perform `pod update` for demo project. Then quit the xcode and reopen it and perform clean and then build.
