### ISSUE TITLE
Copy only changed Resources 

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#1886]
You'll have to excuse my ignorance upfront. 

So the longest part of my compile cycle is the copy Resources phase in the build cycle, in theory this only needs to be ran when the file has been updated. I realize we need to take dev pods, and people being silly into account and always check but that doesn't mean it has to take 4-5 seconds each time.

![2014-03-13 14_49_00](https://f.cloud.github.com/assets/49038/2413612/277a779e-aae0-11e3-8709-b2d33a5eeaeb.gif)

Could it potentially check a timestamp against one already in the app binary or something?

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
