### ISSUE TITLE
`vendored_frameworks` should automatically get embedded appropriately.

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/CocoaPods#1993]
From @alloy originally submitted to CocoaPods/Core#58

--

This means that the framework should:

- [ ] Automatically get copied into the app bundle in the Frameworks dir.
- [x] Automatically configure the application to load frameworks from the Frameworks dir, if they use `@rpath`.
- [ ] For iOS frameworks, simulator slices need to be removed when creating an Archive build, because otherwise App Store will reject the binary.
- [x] Ensure that embedded frameworks are code-signed if necessary.
- [ ] Allow transitive dependencies upon vendored frameworks, by correctly setting `FRAMEWORK_SEARCH_PATH` for user targets (see [this comment](https://github.com/CocoaPods/CocoaPods/pull/3604#issuecomment-107400685))

Currently you have to do the following:

```ruby
  s.osx.vendored_framework = "PLCrashReporter-1.2-rc2/Mac OS X Framework/CrashReporter.framework"
  s.osx.resource = "PLCrashReporter-1.2-rc2/Mac OS X Framework/CrashReporter.framework"
  s.osx.xcconfig = { 'LD_RUNPATH_SEARCH_PATHS' => '@loader_path/../Frameworks' }
```

--

Related to:

- https://github.com/CocoaPods/CocoaPods/issues/1992
- https://github.com/CocoaPods/CocoaPods/issues/1824
- #3015 (same problem on iOS 8 and above)

**Comment by steipete** [comment]
@orta directed me to this issue. We're hitting a similar problem, where we now have a complete, pre-built dynamic framework on PSPDFKit and I can't figure out how to write a podspec for it. Basically all there should be in the spec is this:

` s.ios.vendored_framework = "PSPDFKit.framework`

The framework defines resources, headers and dependencies implicitly, so all cocoapod should do here is to copy it over (and strip irrelevant architectures).

**Comment by neonichu** [comment]
@steipete Yah, it's not really supported, yet :cry: - you can try the workaround mentioned by Fabio above, but I am unsure if it'll work for iOS at all.

**Comment by jaishankar** [comment]
Can anyone help me with this error - In my private podspec, I am trying to specify my framework file
I use 
s.ios.vendored_frameworks = 'MY_REPO/PATH_TO_FRAMEWORK/MyFramework.framework'

When I try to validate ths Spec, all I am getting is  
- ERROR | [iOS] The `vendored_frameworks` pattern did not match any file.

Do I miss anything here?

**Comment by priteshshah1983** [comment]
Did anyone get this working on iOS? I'm having the same issue.

**Comment by sbhklr** [comment]
For iOS, the workaround by @fabiopelosin doesn't work for me. When embedding vendored frameworks using the s.resource attribute they will end up being embedded in the pod framework which isn't within the desired `Frameworks` path of the app. This will lead to issues when code signing the app during submission to app store.

**Comment by segiddins** [comment]
@priteshshah1983 @sbhklr probably the best way to get this to work would just be to implement proper dynamic framework support for vendored frameworks -- a PR for that would be much appreciated :)

**Comment by ldi13** [comment]
Hi eveyone,
Anything new since the past month, if we want to create a podspec embedding a vendored framework ?
I also experiment the same error with my podspec if I declare a vendored framework: 

 - ERROR | [iOS] The `vendored_frameworks` pattern did not match any file.

With all the replies mentioned above, it's not quite clear if the problem was solved by anyone...

Thank you.

**Comment by mrackwitz** [comment]
@ldi13: #3832 addresses _this issue here_, which appears on runtime, because `dyld` will complain about a missing binary.
But that's both not related to _your issue_. Could you please check whether the path to the specified vendored framework, you're specifying, isn't really just wrong. If that's the case, please open a new issue with more details.

**Comment by ldi13** [comment]
@mrackwitz Hello Marius, thanks for your reply, actually, my path was wrong.
I was specifying the following path : 
s.ios.vendored_frameworks = "${HOME}/frameworks/MyFramework.framework"

I changed the path and copy my framework directly into the Pods root:
s.ios.vendored_frameworks = "MyFramework.framework"

The warning is gone.
I guess it's not possible to specify an absolute path, the embedded vendored framework has to be shiped with the podspec.

If you have any other inputs regarding the way to specify a vendored framework, it would be great :-)
Thank you very much for the support.

**Comment by AnthonyMDev** [comment]
So, with this implemented, does that mean that I can now have transitive dependencies on static libraries that have been turned into Cocoapods through use of vendored frameworks.

I'm thinking of Fabric/Crashlytics here.

**Comment by segiddins** [comment]
No, Fabric/Crashlytics would need to transition their pods to vendoring dynamic frameworks instead of static libraries.

**Comment by mhuusko5** [comment]
Is "transitive dependencies on static libraries" not possible at all, or just as of this latest bug chunk of fixes?

On that note, trying to figure out what to do in the interim as a lot of 3rd parties (Fabric, Firebase, Spotify, Rdio, etc-ad-infinitum) aren't shipping as dylibs... hack of just adding `s.xcconfig = { 'FRAMEWORK_SEARCH_PATHS' => '"${PODS_ROOT}/FMK_NAME"' }` doesn't seem to work with frameworks enabled..

**Comment by mhuusko5** [comment]
Ooo that sucks. Good to know, thanks! Will have to start rallying for dynamic framework distribution..

**Comment by fluidsonic** [comment]
Our app uses `use_frameworks!` (aka dynamic frameworks) for development & testing and `use_frameworks!(false)` (aka static libraries) when submitting to the App Store (due to lack of iOS 7 support).
We've split our app into a lot of parts/modules (using separate Pods for each) which are linked together by CocoaPods. These modules in turn use several static library Pods as transitive dependencies and they work for us even when all Pods are built as dynamic frameworks. But it requires various workarounds and there are some limitations.

Some Pods we're using as transitive dependencies are: Crashlytics, GoogleAnalytics, LayerKit

Some workarounds we're using:
- modify CocoaPods's generated `xcconfig` files using `post_install` hook
- modify build configuration settings of the Pods which in turn depend on another static Pod using `post_install` hook
- `-undefined dynamic_lookup` linker flag FTW
- disable CocoaPods's static transitive dependency checker using `pre_install` hook
- rewrite some Podspecs (e.g. GoogleAnalytics) to convert static libraries into static frameworks


So if you're not afraid of a lot hacky workarounds then using some static Pods as transitive dependencies should work.

**Comment by mhuusko5** [comment]
Very interesting!

Unfortunately in this case, the pod that relies on another static pod, is written in Swift.. so dynamic it must be.

**Comment by fluidsonic** [comment]
Our whole app and all its parts (which are Pods) are Swift and thus dynamic. Many of these dynamic Pods depend on static Pods.

**Comment by segiddins** [comment]
This is not the correct issue to have this discussion on.

**Comment by mhuusko5** [comment]
Mind pointing to the one that is? There's a lot of "vendored_frameworks" related issues.. a bit hard to navigate..

**Comment by fluidsonic** [comment]
#2926 looks like a good fit

**Comment by malhal** [comment]
I have a framework I'd like to include in my pod, so that an app can link against it, but I don't need it embedded in the app bundle because it is installed on the device. It seems the new behaviour of vendored_frameworks is copying the bundle into the bundle. Is there a way to have it not do that?

**Comment by AnthonyMDev** [comment]
@malhal It's installed on the device? You mean it's an Apple framework? For Apple frameworks, you just use the `s.frameworks` property.

If it's not an Apple framework, then can you explain what you mean by "it is installed on the device"?

**Comment by malhal** [comment]
It's my own framework I distribute via a Cydia deb which installs it in \Library\Frameworks. I have some developers that would like to build apps that link against it and it must run with the version on the device.

**Comment by segiddins** [comment]
Please stop commenting on long-closed issues -- this isn't the proper place to have a discussion. Either open a new issue or ask on a more appropriate forum such as stack overflow. Thanks!

**Comment by hardikAtEryushion** [comment]
Hello,

Here my question is as i have uploaded zip to github repository and than what is the vendored_frameworks value i have to set so i can get framework from that.

Here i am totally confuse about is there embed zip and got framework from zip.
