### ISSUE TITLE
Feature Request: Add a post project integration hook for after pod integration with the project

### ISSUE THREAD

**Issue by redshirtrob** [CocoaPods/CocoaPods#2119]
I would like to be able to run some code after CocoaPods finishes integrating with my project, i.e. after a `pod update`.  My primary use-case is to fix up any integration issues.

Please see the workarounds for [Issue 731](https://github.com/CocoaPods/CocoaPods/issues/731).  Note that the workaround leaves the project file somewhat messed up.  It's rather easy to fix the problems with the generated pod file, but the existing hooks get called before the integration happens.

**Comment by Rajveer86** [comment]
I would like this to be reopened as I need to remove some of the integrated build phases from some of my targets, and can't do this is post_install. Would this be possible?

**Comment by orta** [comment]
Did you look at the plugin post/pre install hooks?

**Comment by Rajveer86** [comment]
Yes as mentioned, the post_install hook is performed before integration and doesn't suit my needs.

**Comment by csknns** [comment]
I faced with the same problem recently. I created a post integrate hook by replacing at run-time the implementation of integrate_user_project in the Podfile, so that it will run the original method and then my script. I have Podfile an example 
[here](7a8faa6497770c6d93ecf610ae35903a), simply add your code in post_integrate_method.
