### ISSUE TITLE
Distribute via Homebrew

### ISSUE THREAD

**Issue by keith** [CocoaPods/CocoaPods#2238]
It seems like we should start distributing CocoaPods via homebrew. Distributing via RubyGems is really just an implementation detail. I'm not suggesting we try to have updates reviewed each time we want to release, instead I'm suggesting we create our own [homebrew tap](https://github.com/Homebrew/homebrew/wiki/brew-tap) and distribute our own formula there. An example of how this can be done, and scripted, for a Ruby based project can be found [here](https://github.com/thoughtbot/liftoff).

This would also help us with dealing with issues around Ruby installations, system Ruby and sudo or not.

**Comment by mikemcquaid** [comment]
@Keithbsmiley Homebrew maintainer here. I'd like to work with you on getting this part of Homebrew core. Let me know the best place to discuss this and let's try and get there.

I've had people ask us why this isn't already part of Homebrew core and I'd like to provide this option for them to install it, even if it's not officially sanctioned.

**Comment by Keithbsmiley** [comment]
@mikemcquaid gladly. My formula works now, I can go ahead and submit a PR for the current version?

**Comment by mikemcquaid** [comment]
@Keithbsmiley The only problem I see with your formula as-is is it's not using any upstream source files. Can we instead try and work on a formula that generates the same output as your formula from the original sources somehow? Thanks!

**Comment by mikemcquaid** [comment]
(and then we can provide a "binary" package if that's a slow process)

**Comment by Keithbsmiley** [comment]
Meaning that the formula would pull from this repo instead of my fork?

**Comment by mikemcquaid** [comment]
Yup.

**Comment by syxchina** [comment]
@keith 
brew tap Keithbsmiley/formulae && brew install cocoapods
thanks

**Comment by aguynamedben** [comment]
+1, homebrew is the de facto standard for devs installing dependencies. Knowledge of Ruby's package management should not be necessary. The current instructions for CocoaPods installation also advise `sudo gem install`, which is you ask people in the Ruby community is not great...

**Comment by keith** [comment]
My GitHub username changed. It seems like GitHub is redirecting repo URLs for the time being but I recommend that in the future you do:

```
brew tap keith/formulae && brew install cocoapods
```

Of course this wouldn't be an issue if this was in the official repo :trollface:

**Comment by mikemcquaid** [comment]
`brew install keith/formulae/cocoapods` will do this in a one-liner.

**Comment by heypaulmcgrath** [comment]
Thanks, Mike!

**Comment by hfossli** [comment]
Come on! Really? Cocoapods is for people who make apps.. `[sudo] gem install cocoapods` have at times been troublesome to me. And I would hesitate from using a GUI for doing something which isn't as fully transparent as `$ brew install cocoapods`. Are we moving away from using `$ pod install` from terminal as well? I really don't get this. 

I definitely would love to use `brew` rather than an app or `gem`.

**Comment by neonichu** [comment]
There's a cask for the app, which still comes with the `pod` binstub, it is just a distribution method:

```bash
$ brew cask install cocoapods
```

**Comment by alloy** [comment]
@hfossli The app is foremost a container for the CLI tools, it contains all dependencies, up-to-date versions thereof (Ruby, OpenSSL, etc), and requires nothing else to be installed (up-to-date `gem`, `brew`, or properly configured CLI build chain). After you’ve installed it, you will normally still use `pod install` from the Terminal.

**Comment by mikemcquaid** [comment]
> There's a cask for the app, which still comes with the pod binstub, it is just a distribution method:

@neonichu I'd recommend people use `brew install Caskroom/cask/cocoapods` instead which will auto-install `brew cask` if people don't already have it installed (or know/care what it is)

**Comment by neonichu** [comment]
@mikemcquaid ah great, didn't know about that, thanks :+1:

**Comment by neonichu** [comment]
BTW, maybe it makes sense to mention the cask installation method on the website, along with `gem install`?

**Comment by keith** [comment]
Obviously we know my position on this, but making a GUI to be a container for the dependencies seems like reinventing the wheel.

Regardless my homebrew tap is still up to date for anyone who wants to use it:

```
brew install keith/formulae/cocoapods
```

**Comment by neonichu** [comment]
@keith One can easily also argue the reverse :) App bundles, not homebrew formulas, are the prevalent distribution method on OS X after all.

**Comment by keith** [comment]
Not for command line tools.

**Comment by hfossli** [comment]
I second that

**Comment by hfossli** [comment]
Why did i second that. No need to second facts 😀 I don't know of any / use any command line tool installed via GUI except those bundled with xcode.

**Comment by alloy** [comment]
I know of a whole lot of prebuilt command-line tools that come in installer packages. Those install in a single place and can easily ‘break’. Not so with the app, you can place it anywhere and it keeps working.

This is for the people that don’t want anything to do with installing any CLI toolchains etc, they just want it to work. Home-brew doesn’t help with that, as it is not pre-installed.

So now there’s two ways to install that we mention, on other side of the spectrum, that’s good. If you want your own option, that’s perfectly fine, but they don’t all need to be offered in the same place and overload the user who just wants the simple option.

**Comment by alloy** [comment]
This thread has become a large conflation of several issues, which isn’t really productive. We’re not going to advertise homebrew as an installation option among the two we already have. Less options is better for first time users and the homebrew option requires you to first install homebrew, so it’s simply a more complicated route.

I’d also argue that people that want to install through homebrew would probably just check with `brew search`, no? I personally never go to a project’s website to see if they support homebrew, I just try it.

So to be clear, I’m not against having the option for homebrew users to be able to install through homebrew in the way that @keith imagined _at all_ and as such I think we should focus on just having it work _at all_.

@mikemcquaid I’m really confused as to why @keith’s formula is not in the core repo? [This thread](https://github.com/Homebrew/homebrew/pull/40807), to me, reads as “because there is a cask we won’t accept this formula in core, even though it annoys us”. Can you elaborate on what exactly is the reason that’s keeping you from accepting @keith’s formula?

**Comment by mikemcquaid** [comment]
> @mikemcquaid I’m really confused as to why @keith’s formula is not in the core repo? This thread, to me, reads as “because there is a cask we won’t accept this formula in core, even though it annoys us”. Can you elaborate on what exactly is the reason that’s keeping you from accepting @keith’s formula?

The reason that's keeping it is that @keith's formula requires his forked version of CocoaPods rather than building from the main repo (https://github.com/keith/homebrew-formulae/blob/34d115e244a53ecf5e9126307c8ef0c12a135eb9/Formula/cocoapods.rb#L5). I would rather have a CocoaPods formula in Homebrew core but for that to happen CocoaPods needs to be willing to accept @keith's changes into the main repository. See the conversation in https://github.com/CocoaPods/CocoaPods/pull/3010.

I suspect I'm going to get criticised for Homebrew being inflexible here but I'd just like to point out it's extremely rare for Homebrew maintainers to be actively working with upstream projects to try and get them included in Homebrew, even more-so when it's a project they don't use. I think `brew install cocoapods` would be great for both projects which is why I've tried to work towards it but I'm getting pretty mixed-messages from CocoaPods land.

**Comment by alloy** [comment]
>  I would rather have a CocoaPods formula in Homebrew core but for that to happen CocoaPods needs to be willing to accept @keith's changes into the main repository. See the conversation in #3010.

So if I’m correct, the issue is that for the homebrew distribution method, a specialised tarball has to be crafted, which is what @keith’s script does?

(I did not understand up till now that there was more work required than just a formula.)

So, let’s say that @keith would be willing to maintain this, what is the technical reason for the build scripts to be inside the main repo?

> I suspect I'm going to get criticised for Homebrew being inflexible here but I'd just like to point out it's extremely rare for Homebrew maintainers to be actively working with upstream projects to try and get them included in Homebrew, even more-so when it's a project they don't use.

I don’t know why you’d suspect that, it is much appreciated.

**Comment by mikemcquaid** [comment]
@alloy The short answer: the issue isn't the tarball necessarily but that the tarball is created and published manually by @keith and in his repo rather than anywhere official under the CocoaPods org and part of the official release process. Although @keith's work here has been great we in Homebrew-land don't like these type of things because e.g. if @keith is on vacation/hit by a bus and CocoaPods publish a new release then his fork won't be updated, his tarball won't be published and Homebrew has to explain to disappointed users why we don't have the latest CocoaPods. I'd be totally OK with something that lived outside the main repo as long as publishing it became not just on @keith and part of the official release process (e.g. it gets published when you publish the new gem).

**Comment by neonichu** [comment]
@mikemcquaid I probably partially caused the confusion about this with [this comment](https://github.com/cocoapods/cocoapods/pull/3010#issuecomment-112511222) which was missing a bunch of context from private discussions, apologies for that.

Just to recap: 
- We didn't really want to have all the additional scripts in the main CP repo, that was the reason for not merging #3010 
- It was our understanding that if it's not in the main repo, the formula wouldn't be officially accepted, that's why we opted for the cask

Hope that clears the situation up :)

**Comment by alloy** [comment]
@mikemcquaid I see. This makes a lot of sense, thanks for that clarification.

> I'd be totally OK with something that lived outside the main repo as long as publishing it became not just on @keith and part of the official release process (e.g. it gets published when you publish the new gem).

Gotcha 👌

@keith Would you be up for maintaining the scripts inside the [Rainforest](https://github.com/CocoaPods/Rainforest) release process?

**Comment by mikemcquaid** [comment]
@neonichu Really appreciate the apology, thanks :heart:. No worries about the confusion; I caused a fair bit myself too! For me/us it's not so much about the repo as the organisation and it being done by a team rather than an individual. Hope that clears things up a bit!

**Comment by alloy** [comment]
Just a quick in-between recap, so that we ensure we’re all still on the same page:

* It looks like we’re on track to making CocoaPods available in homebrew core for each release, which is great news for homebrew users :+1: :100:

* (As discussed in private) I’m unconvinced the cask distribution method makes much sense. It looks like more effort for us to maintain it than for people to just download the archive and place the app wherever they prefer, especially as it also does not help in updating etc, we still do that through Sparkle.

* Us pushing releases to homebrew does *not* necessarily mean we’ll advertise it as an installation option on the installation page, which is supposed to be as simple as possible. The two are not mutually exclusive. Some discussion is here https://github.com/CocoaPods/cocoapods.org/pull/187.

**Comment by keith** [comment]
I'd be happy to support this in the rainforest repo assuming I can get it set up there.

**Comment by patsplat** [comment]
+1 to everyone.  nice pragmatic thread.

**Comment by her** [comment]
`brew install cocoapods` 

I'm pretty confused here, after reading this entire thread it seemed like cocoa pods would be added to homebrew?? 

what kept cocoapods from doing this? Mike himself from homebrew even offered a hand!

**Comment by keith** [comment]
I haven't gotten to making this work in the rainforest infrastructure. I've continued using my homebrew tap in the meantime. Any help would be appreciated.

**Comment by segiddins** [comment]
@her we've never gotten a PR adding this functionality to rainforest. If you'd like to do that, we'd be happy to merge it, but as stated many many times in this thread, adding this functionality (vs maintaining it) is not a focus for the core team.

**Comment by her** [comment]
Thanks @keith @segiddins for the quick replies. so then for brew users:

`brew install keith/formulae/cocoapods` 

should work @keith? 

https://github.com/CocoaPods/Rainforest is where brew needs to be added then ?

@segiddins I understand :) thanks for replying to me. Though I do want to push and say, it would be *awesome* functionality 🙃

**Comment by keith** [comment]
Yep that command works. And yes that's where support needs to be added.

**Comment by mikemcquaid** [comment]
I've shipped `brew install cocoapods`: https://github.com/Homebrew/homebrew-core/pull/507

**Comment by her** [comment]
This is fantastic 😍 great news 👏🏻

**Comment by orta** [comment]
This looks perfect to me 👍 - I'm happy closing this, we should look into updating that as a part of our deploy process. Great work @mikemcquaid  - you're doing a kick-ass job at running home-brew,

**Comment by mikemcquaid** [comment]
Cheers @orta.

**Comment by orta** [comment]
Quick Q, just to make sure: could this conflict with the CocoaPods Mac App's `brew cask`? 
As we have both `brew cask install cocoapods` and `brew install cocoapods`

**Comment by mikemcquaid** [comment]
@orta Yes, they may conflict if you install them both at once. We're working on addressing conflicts like this between the projects better and it may be a GSoC project.

**Comment by keith** [comment]
Thanks @mikemcquaid awesome stuff!

**Comment by mderazon** [comment]
Sorry for spamming everyone, but does anyone know if it's possible to install with `--pre` flag via homebrew ?
(Install beta versions)

Tried something like 
```
$ brew install cocoapods@1.2.0.beta.3
```
But it didn't find anything

**Comment by MikeMcQuaid** [comment]
@mderazon `brew install --devel cocoapods`

**Comment by ryanbooker** [comment]
This no longer appears to work… How does one acquire the --pre version now?

**Comment by brodybits** [comment]
`/usr/local/bin/brew install cocoapods` works for me (I use complete path to `/usr/local/bin/brew` since I also have a version of Homebrew installed in my home directory)

**Comment by rob-nash** [comment]
OH MY GOD I CAN'T BELIEVE COCOAPODS IS NOW AVAILABLE VIA HOMEBREW

The sudo less install hurt so much. Soooooo much.

THANK YOU

**Comment by MentalGear** [comment]
> Please make this more visible in your guides
This

**Comment by codemaestro** [comment]
Even cooler only a few months later. Both of these work:

1. `$ brew install cocoapods`

1. `$ brew install --cask cocoapods`

I tried 1. first and was told that "cocoapods was going to  be treated like a formula". So I uninstalled it and reinstalled using 2.

However, being new to `brew`, I can't find any info as to why I would rather install as a `cask` or as a `formula`. Maybe when https://cocoapods.org/ is updated someone could explain the differences?
