### ISSUE TITLE
Importing pods in playground

### ISSUE THREAD

**Issue by sohocoke** [CocoaPods/CocoaPods#2240]
In what way would we be able to use pods with Swift playgrounds?

It appears Swift's `import` would require a pod setup to compile into a framework. Could his be facilitated with another pod command? That would be quite awesome.

**Comment by davidbjames** [comment]
@slabko (and others). In order to get this working:

* Manually add the pod frameworks via Link Binary With Libraries on the non-framework target.

Couple other caveats to keep in mind:
* Classes or protocols defined in the pod that need to be accessible in the playground, must be marked public.
* When dealing with a pod you've created, adding a playground directly to your framework's project will probably not allow importing the pod. One workaround is to create a "sample" project, include the pod and add your playground to that (then manually add frameworks per above ^).

**Comment by madnik** [comment]
**Update**

We got a ruby gem for creating playground out of pod by neonichu.
https://github.com/neonichu/ThisCouldBeUsButYouPlaying
