### ISSUE TITLE
inhibit_warnings should apply to implicit dependencies

### ISSUE THREAD

**Issue by lukeredpath** [CocoaPods/CocoaPods#2353]
I have a pod in my Podfile which has an implicit dependency which is giving me warnings that I'd like to inhibit.

When I add 'inhibit_warnings: true' to my Podfile, I still get warnings as only the parent pod is being inhibited.

Expected result: specifying inhibit_warnings should apply to all implicit dependencies of a pod.

Workaround: make the dependency explicit and specify inhibit_warnings to that dependency.

**Comment by lilyball** [comment]
I keep running into this issue and it really should be fixed.

When building a dependency graph, if all paths by which an implicit dependency is reachable includes a pod that has `:inhibit_warnings => true` then the implicit dependency should also inherit `:inhibit_warnings => true`. Or to put it another way, an implicit dependency should only emit warnings if there exists some path through the dependency graph to reach it where every pod along the way is allowed to emit warnings.

I can redeclare the dependency myself with `:inhibit_warnings => true`, but this is a terrible solution because it means if the actual explicit dependency that includes it ever removes this implicit dependency, now I'm pulling in the implicit dependency anyway even though I no longer want it. My Podfile should never have to care about implicit dependencies (beyond version mismatches if two explicit dependencies want incompatible implicit ones, but I assume CocoaPods will throw an error in that case), and I especially should never be put in the situation of, every time I update a dependency, checking its podspec to see if its own dependency list changed so I can update my Podfile accordingly.
