### ISSUE TITLE
Cannot add groups to the Development Pod files in a project created using “pod lib create”

### ISSUE THREAD

**Issue by khanmdv** [CocoaPods/CocoaPods#2359]
I created a new SDK project using "pod lib create XYZ" command. From the cocoapods guides, I see that the Pod directory contains Classes and Assets folders where all my SDK class files should reside. In Xcode I see all the files added to the Classes directory. However, when I try to create a group from a selection of few files and then do a "pod update", the groups vanish leaving the files behind.

How can I solve this ?

**Comment by jamessmith-airside** [comment]
Hi, I don't believe you answered the question correctly, or perhaps there is a legitimate bug or lack of clear documentation.

I am seeing this exact behavior. Cocoapods Dev pods are not respecting folder structure. My source files are contained in subfolders, yet when I run update, the files in my dev pod are not in Groups in the Xcode file organizer. They are placed under the root Group of that dev pod.

My file structure:

```
DevPod
    SomeFolder
        SomeFile.swift
```

After running pod update DevPod Xcode file organizer:

```
DevPod
    SomeFile.swift
```

The subfolder is missing.

**Comment by amorde** [comment]
Yes, after this issue behavior was changed so this comment is no longer accurate.

In general, we'd prefer not commenting on closed issues as it's very difficult to keep up with notifications on closed issues. This issue is over 5 years old.

Here's a related issue: https://github.com/CocoaPods/CocoaPods/issues/8873. If you are experiencing something different, please open another issue. Thanks!
