### ISSUE TITLE
Explicit plugins and plugin configuration

### ISSUE THREAD

**Issue by kylef** [CocoaPods/CocoaPods#2640]
I think it would be nice to have explicit plugins defined in a Podfile, and also allow passing configuration down to the plugin.

Here's an example of usage:

``` ruby
plugin 'cocoapods-keys'
plugin 'slather'
plugin 'acknowledgements', :plist => 'Resources/Acknowledgements.plist'
```

This goes along with #2619.

**Comment by feldan** [comment]
Hi, 
sorry to comment on such an old issue - i'm writing a plugin to work with custom private Spec repositories and i'm trying to figure out if there's a way my plugin can be configured to work globally with a set of parameters instead of having to include it and the parameters in each Podfille.
Is it something that's achievable currently?
Thanks.

**Comment by orta** [comment]
Your Podfile is ruby, you can do any computation you want

**Comment by feldan** [comment]
Ok, but i'm looking to not have to do anything in the Podfile - I want a global configuration for the entire client, or per repo perhaps.

**Comment by segiddins** [comment]
@feldan not possible at the moment, sorry. Please let's not comment on long-closed issues
