### ISSUE TITLE
How do I update a podspec?

### ISSUE THREAD

**Issue by dburr** [CocoaPods/CocoaPods#2772]
I've discovered a serious problem in the AdMob podspec, and I am attempting to push an update to it to fix said problem.  I am the "owner" of this podspec (i.e. it shows up when I do a `pod trunk me`.)

According to [the guide](http://guides.cocoapods.org/making/specs-and-specs-repo.html), in the "How do I update an existing Pod?" section, the procedure for updating an existing pod should be as follows:
1. Create your Podspec as described described above.
2. Run `pod spec lint` to check for errors.
3. Submit your Podspec to Trunk with `pod trunk push NAME.podspec`

I have done all of the above, the Podfile passes lint perfectly, however when attempting to `pod trunk push` it, I am getting the error "`Unable to accept duplicate entry for: Google-AdMob-Ads-SDK (6.12.0)`"

What am I doing wrong?

**Comment by mdjipcs** [comment]
`  s.version          = "0.1.0-beta"`
Change the version and push again!!!

**Comment by dji-dev** [comment]
Hi, I have the same problem too. Since my user case is that I want to make sure the version shown on Cocoapods is the same as the project version I have published on website. If I do find some serious bugs or License problem in the current version,  is it possible for me to update it with the same version? Or can I just delete the current version and update it again? I cannot find an option to delete the published Cocoapods pod spec in the command lists. Thanks!

**Comment by oliverou** [comment]
Hi, I have the same problem too. Since my user case is that I want to make sure the version shown on Cocoapods is the same as the project version I have published on website. If I do find some serious bugs or License problem in the current version, is it possible for me to update it with the same version? Or can I just delete the current version and update it again? I cannot find an option to delete the published Cocoapods pod spec in the command lists. Thanks!

**Comment by orta** [comment]
The commands are in the 1.0 betas

**Comment by oliverou** [comment]
Thanks orta! I do find the delete command.

**Comment by jcanizales** [comment]
Hi @orta, the delete command in `pod trunk` says:

> Once deleted, this version can never be pushed again.

Does that mean it is not a way to fix a broken podspec without changing the version?

@oliverou , did you end up trying it?

**Comment by dji-dev** [comment]
@jcanizales Yes, you cannot update the same version once you push to cocoapods trunk, you can only update your pods in next version. So be careful to update your pods.

**Comment by xingheng** [comment]
I encountered this issue when I `pod trunk push` at the second time as the first run failed when running `pod repo update`, it just pushes the podspec to cocoapods remote server successfully at the first time. Confirmed it just now. FYI.

**Comment by littlepod** [comment]
@xingheng, I tried twice. it did not work and why it should in second time. I guess there should have been a way to update existing podspec file (scope for improvement).
If not then, I guess, we have to
 - delete existing and recreate 
- make one beta and then then as usual version up.

Not happy though :-(
