### ISSUE TITLE
Multiple Email Registration Support

### ISSUE THREAD

**Issue by terryworona** [CocoaPods/CocoaPods#2822]
Running **$ pod trunk me** returns a single session + email. 

Since I manage several pods across work and personal emails, it would be nice to support _multiple_ emails/sessions.

**Comment by jalakoo** [comment]
Throwing my vote in for this as well.

**Comment by kevklam** [comment]
+1

**Comment by orta** [comment]
You're welcome to define what this would look like, through expanding on the issue or a PR. It's been many years without it being a priority, It probably won't be from our perspective.

**Comment by kevklam** [comment]
I don't have knowledge of the cocoapods code base, so I can only comment on 'desired experience'. Primarily, I would like to avoid having to go through email verification every time I want to push a change to a different pod.

From a UX perspective, and based on the help text, I'd always imagined 'pod trunk register' to just add another session to a list of credentials instead of replacing previously added credentials, with an explicit 'unregister' command to perform that function. Under that assumption, I would expect one of the following behaviors:

1. 'trunk push' to compare the list of owners of a pod against the list of registered sessions, and choose an appropriate one (or prompt to choose from a list if multiple valid options exist)
2. An additional 'trunk select-session' command to make a given session current
3. 'trunk register' to register a new session OR make an existing session current if already registered

Approach (1) seems convenient, but could become cumbersome if a user actually does have multiple sessions valid for a given repo. Probably not a common scenario, but something to think about.
Approach (2) and (3) are more or less the same, with (3) probably being the best for backward compatibility with any kind of automated scripts (assuming any scripts can handle email-based auth anyway).

As I said, these are just my thoughts without any background knowledge of implementation details.
