### ISSUE TITLE
Undefined symbols for architecture armv7 (Cocoapods 0.34.4)

### ISSUE THREAD

**Issue by Fosile** [CocoaPods/CocoaPods#2846]
Hey everybody, i struggling with this Problem for 3 Days now and you are my last hope.

Everything worked fine until i´ve done "pod update". Nothing more! After this i can´t compile my Project anymore, not with Device or Simulator! I get this Errors:

![bildschirmfoto 2014-11-19 um 13 10 46](https://cloud.githubusercontent.com/assets/5736296/5105476/837eb514-6fed-11e4-91f0-d0d01084dabc.png)

![bildschirmfoto 2014-11-18 um 14 40 55](https://cloud.githubusercontent.com/assets/5736296/5105460/4c18d64a-6fed-11e4-9bfc-039788a275bd.png)

This is my Podfile:
![bildschirmfoto 2014-11-19 um 13 12 56](https://cloud.githubusercontent.com/assets/5736296/5106011/c0dfefd0-6ff3-11e4-9690-7eb6607c35d0.png)

This should also be correct:

![bildschirmfoto 2014-11-19 um 13 22 13](https://cloud.githubusercontent.com/assets/5736296/5105616/7c6690c4-6fef-11e4-98fd-ee416e75061c.png)

Maybe this could be the Problem?:
![bildschirmfoto 2014-11-19 um 13 52 19](https://cloud.githubusercontent.com/assets/5736296/5105969/4f7b2fda-6ff3-11e4-9782-6a9522ed2abf.png)

I´ve nearly tried everything. I delete the whole cocoapods stuff and reeinstalled everything but nothing worked. 
My Pods project compile succesfully.
I ´ve also done $ rm -rf DerivedData. 
I restarted Xcode and have done a Clean...
I´m working with Xcode 6.1

**Comment by kylef** [comment]
Without a fully replicatible test case, we are unable to determine what's causing the problem, and therefore must assume that this is not an issue caused by CocoaPods, but instead a configuration problem in your project or Podfile. 

These types of errors indicate that a certain class, selector or function is missing when being linked in the given target. With this information you should be able to determine why it isn't found. If the class, selector or function is coming from a pod. Look where that pod is in your Podfile and ensure it will be linked to the target you are building.

I'm going to close this issue because it's not a problem with CocoaPods but a configuration issue against your targets in your project or Podfile. The issue tracker is reserved for bugs/features in CocoaPods and not usage questions. If you are still having issues I'd suggest you create a post on StackOverflow including a bit more information. I'd be more than happy to take a look if you link me to the Stack Overflow question providing it has sufficient information.

If of course, you do find there is an actual issue in CocoaPods, then please feel free to create an issue here stating what the problem is. But ensure you've attached sufficient steps to reproduce or an example project exhibiting the problem as outlined in our [CONTRIBUTION guidelines](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

If this problem is related to your test targets, you might be able to find some steps you can take a look at: https://github.com/CocoaPods/CocoaPods/issues/2583#issuecomment-57830300.

**Comment by Jignesh1805** [comment]
how to solve ?
Using google-cast-sdk (4.3.1)
[!] The 'Pods-DemoMeride' target has transitive dependencies that include static binaries: (/Users/romaltandel/Desktop/Demo1/DemoMeride/Pods/google-cast-sdk/GoogleCastSDK-ios-4.3.1_static/GoogleCast.framework)


podfile :
 platform :ios, '10.0.3'

target 'DemoMeride' do
  use_frameworks!

  pod 'MerideLib' , :path => ‘/Users/romaltandel/Desktop/Demo1/meride_ios_sdk'

end
