### ISSUE TITLE
CocoaPods unusable with static library projects with test target

### ISSUE THREAD

**Issue by jshier** [CocoaPods/CocoaPods#2853]
In relation to my closed #2713 I've been trying to get CocoaPods (0.35) working for any static library project that has a test target. No matter the Podfile permutation I try I can't get it to not have the duplicate symbol errors during linking. Only removing the OTHER_LIBTOOLFLAGS = $(OTHER_LDFLAGS) setting from the xcconfig works. 

A secondary issue is that there's a configuration conflict with the library project as created from the Xcode template, resulting in the following output when you try to do a pod install: 

```
[!] The `TestLibrary [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-TestLibrary/Pods-TestLibrary.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

Removing the build setting (just -ObjC) lets the project find the symbols but it then fails because of the duplication. 

Overall it doesn't seem like CocoaPods should be broken by default when trying to use it with a static library on iOS.

**Comment by neonichu** [comment]
I'm thinking this is related to the other issues we have regarding OTHER_LIBTOOLFLAGS - the agreed upon solution is reverting that change (<https://github.com/CocoaPods/CocoaPods/issues/2747#issuecomment-65797551>), not sure how it will affect this case, though.

The handling of OTHER_LIBTOOLFLAGS differs between Xcode 5 and 6, so that's where the difference comes from.
