### ISSUE TITLE
Use static library to speed up Xcode index and compile!

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#2905]
I test to other way to use cocoapods.

First, I use Cocoapods v0.35.0 to `pod install`, and everything is OK.

Then, I remove the `Pods.a` from `Linked Frameworks and Libraries` of the my project's target. 

I add a shell to the `Build Phases` of my project's target:

```
xcodebuild -project "${PODS_ROOT}/Pods.xcodeproj" -target Pods -arch ${CURRENT_ARCH} ONLY_ACTIVE_ARCH=NO -sdk ${SDK_NAME} -configuration ${CONFIGURATION}
```

This shell must be at the top of `Build Phases`.(Below the `Target Dependencies`).

And add `"$(PODS_ROOT)/build/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)"` to the `library search path` of my target.

Now, I just to open the `project.xcodeproj`, no the workspace. 

Everything will be OK, and the Xcode will not indexing for the `Pods` and will not compile it.

Why I do it? 

My project will dependency many libraries, and there are 64 targets in my `Pods`. 

The source files in the `Pods` will be indexed by the Xcode, there are almost 4000 files will be indexed! So when I open the project, I will wait until the index finish!!!

On the other hands, every target will be compile when I build my project. But I think they should not be compile every time!

What about my idea? Please tell me what you think.

**Comment by shepting** [comment]
I like this idea personally.

**Comment by kylef** [comment]
@Whirlwind Is this issue still relevant with [dynamic frameworks](http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/)?

**Comment by orta** [comment]
yeah, I think the crux of the matter is "I want the build artifacts in CP rather than having the source in them."

**Comment by orta** [comment]
@kylef and I talked about this an extension of the https://github.com/CocoaPods/cocoapods-packager plugin to support doing this on every `pod install` if you include it in the `Podfile`. This would automate what you're after.

**Comment by Whirlwind** [comment]
@kylef I think it is not relevant with dynamic framework. It just pre-build the Pods project to a static library. I think we should not care about the code in the Pods, just care about the header files..

**Comment by samdmarshall** [comment]
@Whirlwind have you tried creating an External Build Target instead of using a shell script in the build phases? That should make management of this a bit easier for your project and it will integrate the build process better.

If an additional target was to be added to the user's xcodeproj file that pointed `xcodebuild` at the pods.xcodeproj file then it would facilitate the same behavior and would allow for that target to be assigned as an explicit dependency on your main app. This could also pass "build" and "clean" actions onto xcodebuild when building the Pods.xcodeproj file.

**Comment by kylef** [comment]
@neonichu has built a [plugin that provides this for frameworks](https://github.com/neonichu/Rome). You can run `pod install` and it generates a set of frameworks you can manually integrate into your project.

**Comment by orta** [comment]
Yeah, I think the plugin should be enough. Let's close this issue.

**Comment by michaeleiselsc** [comment]
The plugin was giving me issues and is quite obscure. Considering that many people would like to speed up this build process, such as everyone at my company, it would be great to have a more standard, reliable solution. It's painful after cleans, when everything needs to be re-compiled even though it hasn't changed.

**Comment by alloy** [comment]
> it would be great to have a more standard, reliable solution

@michaeleiselsc I think that’s a great idea and would indeed serve a lot of people!

The issue here is not so much one of not considering your use case valid, it’s that we _personally_ prefer to have sources in the projects and as such the project does what we need, as we know our cases very well and can test them every day. On the other hand we don’t yet know what complexities we’ll run into building this alternate solution, let alone how much time it would cost us, nor would we be the best maintainers of it.

Plugins were introduced exactly to solve these kinds of issues. So I think it would be great if your company could put some resources into a plugin that fixes your own use case exactly to your liking and share that with the rest of our users. You don’t even need to start from scratch, you could expand on @neonichu’s work and make [the existing plugin](https://github.com/neonichu/Rome) better/more complete, or use it as a dependency for your own plugin and built on top of it. (@neonichu might have some ideas on that to share with you.)

And if it ends up being really clean and simple, we can always discuss merging it into the main project _then_. (No promises there, though.)

Hope this helps.

**Comment by michaeleiselsc** [comment]
Thanks for the excellent response :) I'll talk with my company.

**Comment by alloy** [comment]
@michaeleiselsc Awesome :+1:

**Comment by fabb** [comment]
What do people nowadays do to cope with the issues described in this thread with static and/or dynamic frameworks?

**Comment by MauriceArikoglu** [comment]
@fabb Use Carthage.
