### ISSUE TITLE
pod lib create generates a project that randomly crashes when running tests

### ISSUE THREAD

**Issue by guidomb** [CocoaPods/CocoaPods#2929]
When I run my tests from the command line using xcodebuild sometimes I get an error

```
xcodebuild: error: Scheme Foo is not currently configured for the test action.
```

but sometimes it works. It is super strange and I have not idea what it is.

I have been having this issue for weeks in a project of my own, [WLXBluetoothDevice](http://github.com/Wolox/WLXBluetoothDevice), and I thought that I was the one doing something wrong but If you create a new lib using the `pod` command line tool and run the tests you get the same error:

```
$> pod lib create Foo
$> cd Foo/Example
$> xcodebuild  -workspace Foo.xcworkspace -scheme Foo test  -sdk iphonesimulator
xcodebuild: error: Scheme Foo is not currently configured for the test action.
```

When I go to manage Schemes I see 2 schemes with the same name, if I rename one of those the problems seems to go away but everytime I run `pod install` the name of the shema goes back to the one originally generated by `pod lib create`. Any ideas?

**Comment by dtrenz** [comment]
It appears that this might still be an issue for local/development pods. 

Pod schemes created from the CocoaPods repo are created with the `Pods-` prefix, but local pod schemes are not getting that prefix, which causes the same `Scheme ________ is not currently configured for the test action" error.

**Comment by dtrenz** [comment]
Is there a way for me to specify a different scheme name in the Podfile? Renaming the scheme locally is fine, but when I `pod install` on a CI server, it creates the duplicate scheme name.

**Comment by kunalbalani** [comment]
This is still an issue

**Comment by neonichu** [comment]
Hm, I can't reproduce this anymore, though — are y'all accidentally using the "PodName" instead of the "PodName-Example" scheme?

**Comment by nickjwallin** [comment]
I am also still having this issue, and running `xcodebuild` on my PodName-Example scheme does get around the issue. However, may I ask @neonichu why this is the intended scheme? I'm working on a Cocoapod, not an example project. Why would I reference the example in my build tools' (e.g. Fastlane) configs? Is this just an unfortunate side-effect of the template for `pod lib create`? (We have other private library Cocoapods, with directory structures we set up manually, which also have example projects, but do not run into this issue. I assume because of the different directory/project/workspace/scheme structure.)
