### ISSUE TITLE
Mac-like folder structure

### ISSUE THREAD

**Issue by tinoheth** [CocoaPods/CocoaPods#2967]
🌈
Invisible dot-files (or folders) are common in UNIX-like systems, but (imho) quite ugly.
Mac OS has special directory where items that should be hidden from normal users should go - the Library-folder.
So, instead of "~/.cocoapods", the folder "~/Library/cocoapods" should be used.

**Comment by orta** [comment]
I think the reasons are that CocoaPods as it currently stands is a command line app, and thus it acts like a command line app. Breaking convention doesn't make much sense for us. 

I don't really know much about where we plan to take CocoaPods.app, but I would expect that it too will be keeping the `~/.cocoapods` structure for specs repos / plugin info / whatever. However I'd also except it to keep application state in the right places, because its a GUI app. It definitely wouldn't be worth trying to maintain two sets of places for little gain. 

Thanks for the PR, and it was nice to have the discussion, but I don't think we should go in that direction.

**Comment by neonichu** [comment]
👍

**Comment by kdawgwilk** [comment]
I do have to say that having things stored in any user home directory ( ~/ ) makes things a little more tricky for CI servers especially ones that use a special user created only for building (Xcode Bots use _xcbuildd user) Although its possible to get things to work, it requires some tweaking.

**Comment by tinoheth** [comment]
So are you voting for /Library/cocoapods? ;-)
(would be a nice option in theory, but I guess it wouldn't work well in practice)

It's a pity that Xcode seems to hamper tools like cocoapods and Carthage, but I still hope that Apple gets it right and finishes what they started with the "Working copies" feature: There is already the option to check out "favorites", but you cannot add the new clone directly to an existing workspace, so the process is very cumbersome.
As Frameworks finally reached iOS, there is not much left to have dependency management build into Xcode (hey, and starting to dream: We could even get an official plugin system and full scripting support ;-)
