### ISSUE TITLE
Feature request: Swift specific podspec

### ISSUE THREAD

**Issue by basvankuijck** [CocoaPods/CocoaPods#3016]
Let's say I've got this class `ESRandom` which is an objective-c class.
When swift became available we created a swift version of the same class. With the exact functionality and version code.

Now when defining this pod in my `Podfile`:
<code>
pod 'ESRandom', '~> 1.0'
</code>
It both loads the obj-c and swift files and my swift project builds with an error saying it has duplicate symbols (or something like that).
If I remove the obj-c files my project runs perfectly.

So it would be great if I could tell the Podfile which filetype I want to use
<code>
pod 'ESRandom', '~> 1.0' :lang => 'swift'
</code> (or something like that)

I have tried using subspecs, but these don't give the right result and I don't think they're used for this kind of setup.

Or is there any other workaround / solution for this ?

**Comment by getaaron** [comment]
What's the benefit of maintaining identical code in two different languages? You could also create a separate pod like `ESRandomSwift`, or cut a 2.0 Swift-only release.

**Comment by basvankuijck** [comment]
Honest question. Why would I want to do that? Don't have a straightforward answer for that. But I'm wondering how other developers see the objc -> swift transition in cocoapods. And what are the options / best practices. Regarding podspecs and codebase structure

**Comment by orta** [comment]
@kylef I believe has done one based on two separate subspecs. `pod "ESRandom/swift"` for swift for example with a default to objc. 

IMO it's better to do it as a separate pod, offering the exact same API but in swift is no real advantage, if you're gonna re-write for swift, give it a swift like name ( no prefixes, for example ) and try write using generics / extended enums etc.

**Comment by basvankuijck** [comment]
Yeah, I've seen https://github.com/QueryKit/QueryKit/blob/master/QueryKit.podspec which caught my interest

**Comment by neonichu** [comment]
I think this is a far too uncommon thing to do to warrant additional syntax in the Podfile.

**Comment by kylef** [comment]
Objective-C as the default subspec for QueryKit was only because this predated the Swift support in CocoaPods. I've [just amended this](https://github.com/QueryKit/QueryKit/commit/691dc86787d22b86da1c353bf135cec609f9c4a3) and now that is no longer true.

QueryKit did start as a Swift-only code base, it makes heavy use of Swift features (Generics, Optionals, Tuples, operator overloading, etc). Which unfortunately meant you couldn't even bridge this to Objective-C. There are three areas of QueryKit, the original Swift only component. The Objective-C counter-part, this doesn't provide an interface as elegant as the Swift component. It unfortunately doesn't provide type-safety like the Swift one does. The Objective-C component introduces a class prefix of QK.

There third part is a [bridging component](https://github.com/QueryKit/QueryKit/blob/master/QueryKit/ObjectiveC/QKQuerySet.swift), which allows you to transform between the two types. This was crucial part of using the Swift QuerySet implementation from Objective-C. It simply offers methods on each object to convert it to the other variant.

So, Swift to Objective-C variant:

```objective-c
[querySet asQKQuerySet]
```

and Objective-C variant to the Swift variant:

```swift
qkQuerySet.asQuerySet()
```

---

ReactiveCocoa 3.0 has a similar design, it started off in Objective-C. A new native Swift interface has been introduced using generics to provide type safety of elements inside a signal (or whatever Justin is calling Signals these days). There are also methods to interchange the Swift/Objective-C types similar to QueryKit.

---

QueryKit's Objective-C implementation was purely done to ease bridging between the two languages. I do not see this implementation staying around forever and I expect once Swift matures and becomes a dominant language for development in OS X and iOS I will remove it.

I'd expect the same would be true for ReactiveCocoa, however I don't actually know the truth.

**Comment by basvankuijck** [comment]
I think a subspec would be the best solution for now.
With a (or not) default subspec set to obj-c

Thanks all for your input

**Comment by mxcl** [comment]
Just FYI I did the same as @kylef for @mxcl/PromiseKit, two classes and the capability to bridge. Most of it is written in Swift with ObjC to make the bridging work better.
