### ISSUE TITLE
Compile issues when mixing Swift and Objective-C libraries

### ISSUE THREAD

**Issue by nicholaswyoung** [CocoaPods/CocoaPods#3018]
When you include both a Swift framework (like [Alamofire](http://github.com/Alamofire/Alamofire)) and an Objective-C library (in my case, [FreeStreamer](https://github.com/muhku/FreeStreamer)) in your Podfile, XCode throws compile errors.

For reference, look at the [machinefm/ios](http://github.com/machinefm/ios) project. It currently includes FreeStreamer on the master branch and compiles fine, but when [Swift projects were also included in the Podfile](https://github.com/machinefm/ios/commit/4538c2969b6ad5dfb0788b9ea4287e0fee935c32), compilation fails because XCode cannot find ```libxml2.dylib```.

**Comment by neonichu** [comment]
The issue seems to be that the xcconfig is not applied to the framework, but only the app target, so libxml2 headers are not being found while compiling the framework. The FreeStreamer pod pulls in libxml2.

**Comment by nicholaswyoung** [comment]
@neonichu So is this something I can resolve in my project, or is it a case where I should wait on the fix in Cocoapods?

**Comment by neonichu** [comment]
@nicholaswyoung You'll have to wait for a fix in CP.

**Comment by nicholaswyoung** [comment]
@neonichu Gotcha. Is this kind of mixing of Swift/Obj-C pretty high on the list of priorities? I'd like to know if I should hang on for a few days, or continue the project by manually copying Swift libraries that I need. (If it's expected to be a quick fix, I'll hang on. If not, I'll start on a workaround.)

**Comment by neonichu** [comment]
@nicholaswyoung Really unsure without knowing the actual root cause. As use of libxml2 is somewhat common, I'd expect a fix in the final 0.36 for sure.

**Comment by neonichu** [comment]
So looking a bit closer, my original comment was actually wrong, the framework is compiled just fine.

The actual issue is that the Pod uses libxml2 in its headers, which will unfortunately not work in the framework case with Swift, because the iOS SDK does not provide a clang module for libxml2 (actually for none of the dylibs, see also CocoaPods/swift#8). In addition to that, the FreeStreamer Pod also uses C++ in its public headers (e.g. <https://github.com/muhku/FreeStreamer/blob/master/astreamer/audio_queue.h>), which will also break in the framework case.

There's nothing we can do to fix that from the CP side, in its current form, the FreeStreamer Pod is simply not suitable for being build as a dynamic framework in conjunction with Swift.
