### ISSUE TITLE
0.36.0.beta.1: Too many arguments to function call, expected 0, have 2; Enable Strict Checking of objc_msgSend Calls should be set to NO

### ISSUE THREAD

**Issue by fatuhoku** [CocoaPods/CocoaPods#3060]
Lots of pods use `objc_msgSend`. Compiling these pods with causes the following error message:

```
.../Pods/Typhoon/Source/Factory/Block/TyphoonAssemblyDefinitionBuilder.m:198:29: Too many arguments to function call, expected 0, have 2
```

Is there a sensible way to avoid this problem for all of your pods the maintainers each patch it? Perhaps there should be a directive in the Podfile that lets the user turn off the `Strict Checking` option in Xcode.

![screen shot 2015-01-21 at 22 26 55](https://cloud.githubusercontent.com/assets/430233/5846790/b2403618-a1be-11e4-8154-44d03f36e35f.png)

**Comment by orta** [comment]
This is an [Xcode 6](http://stackoverflow.com/questions/24922913/too-many-arguments-to-function-call-expected-0-have-3) issue rather than a CocoaPods 0.36 issue. It's outside of the scope of CocoaPods o try and maintain forwards compatibility for source changes inside Pods. If Xcode now says its a warning on defaults, it's a warning.

Best to send Typhoon a PR fixing it.

**Comment by jasperblues** [comment]
Re Typhoon: We received PR #305 and updated obj_msgSend to include modern-style cast.

**Comment by orta** [comment]
Yeah, me too on one of mine, https://github.com/orta/ORSimulatorKeyboardAccessor/commit/5f43093553dd224d14b3d92ec1a14f8e52784655

**Comment by fatuhoku** [comment]
Fantastic.

**Comment by barrettj** [comment]
Is there any way that I can specify to ignore this warning on a particular pod?  I'm using an old version of a pod for compatibility purposes (and thus the version I'm using wouldn't get an update to cast the msgSend).  If I can't do this, I will now have to fork that project just so I can implement this change.

**Comment by neonichu** [comment]
Not casting to the correct type on 64-bit can cause crashes, so ignoring this in any way is a really bad idea.

**Comment by barrettj** [comment]
@neonichu I'm explicitly not building for 64bit (and stripping all 64bit slices) so that's not a concern

**Comment by Sajjon** [comment]
If anyone is experiencing problems with any Cocoapods project due to the objc_msgsend has too many arguments issue, I have fixed it using the post_installer script below.

What I am doing is that I am iterating through all targets in the Pods.xcproj and setting the flag 'ENABLE_STRICT_OBJC_MSGSEND' to NO.

```ruby
post_install do |installer|
	installer.project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['ENABLE_STRICT_OBJC_MSGSEND'] = "NO"
		end
	end
end
```
