### ISSUE TITLE
Cocoa pods refusing install because of resolved merge conflict

### ISSUE THREAD

**Issue by spencerkohan** [CocoaPods/CocoaPods#3093]
I tried to run:

    $ pod install

with an existing merge conflict, and I got this error:

    ArgumentError - The file `/path/to/project/project.pbxproj` is in a merge conflict

So I resolved the conflict, and I'm still getting the error.  I know the conflict is resolved because git status is coming back clean.

Is there somewhere within cocoa pods to clear this error?

**Comment by kylef** [comment]
For CocoaPods to say that message, the project will have <<<<<<<, >>>>>>> or ======= on a line indicating it has a conflict which hasn't been resolved.

It is possible that there is still the conflict markers and the file is still in a conflict (git only says it's resolved because it was told it has been resolved regardless of the conflict markers).

You can find them in your file by running the following:

```bash
grep -E '<<<<<<<|>>>>>>>|=======' /path/to/project/project.pbxproj
```

**Comment by spencerkohan** [comment]
Hey thanks that was definitely it!  I had left the ====== marker in.

**Comment by HeidiHansen** [comment]
I had this issue even after removing the merge conflict indicators.  Saving the edited file fixed it.  This may seem obvious to most, but it isn't at all necessary to save files when using Xcode, so it wasn't intuitive for me.
