### ISSUE TITLE
Local dependencies in podspec

### ISSUE THREAD

**Issue by bunchjesse** [CocoaPods/CocoaPods#3103]
Hi there,

I wanted to take a moment to point out an issue that I see with Cocoapods. Here's a scenario that I'm running into:

- I've started creating a new pod with a few dependencies. I started with `pod lib create <name>`
- For the majority of the dependencies, `s.dependency` works fine, that is, if the pod is in the main repository.
- In the case of one dependency, XMPPFramework, I want to use my local fork rather than the public version. Eventually, I may contribute my changes back to the public project but that is for another time.
- My only option seems to be to specify the local version as a development pod in my Podfile, which doesn't apply to the pod that I'm developing; rather, it applies to the test target that I'm running my unit tests on.
- Consumers of my podspec have to duplicate this podfile declaration in their podfile (along with the dependency on my podspec) which is really hard for an OCD person like me swallow.

Please tell me that there is a solution that I'm missing! Here are my requirements (as I understand Cocoapods):

- My podspec should specify all of it's dependencies and be completely self sufficient, even local podspecs that I have forked (and am currently working on in tandem).
- The podfile contained in the "Example" folder should contain dependencies of the test target or example app (e.g. OCMock) along with a dependency of the development pod.

Thanks for your great work on this project! I'd be happy to help in any way I can.

**Comment by segiddins** [comment]
You should either:
1) depend on the published version of the dependency
2) contribute your changes back upstream
3) properly fork the dependency, and instruct users to use your fork from a separate specs repo

**Comment by fatuhoku** [comment]
:+1: 

Dependencies split over `Podfile` and `podspec` is unacceptable. @segiddins workflow-wise those three steps you suggested are not practical.

1. Is not practical because there's usually a good reason you'll want to depend on a specific source rather than the published source... the developer is better off downloading the dependency and including it into the project him/herself.
2. Contribution + Pull requests takes days, weeks, if not months... again, better off keeping a locally modified fork somewhere.
3. ... is just lots of work. we can be talking about a one-line change.

**Comment by segiddins** [comment]
CocoaPods is pretty clear that this is _not_ the tool's responsibility.
