### ISSUE TITLE
Failed to import bridging header

### ISSUE THREAD

**Issue by tanob** [CocoaPods/CocoaPods#3120]
I'm getting errors in the build the moment I add a reference to the main module from the Test target, before that the build works fine.

![screen shot 2015-02-08 at 13 59 28](https://cloud.githubusercontent.com/assets/5013/6097197/d3f7419a-af9a-11e4-869e-63f0d359593f.png)

I'm not sure how to get this working. You can try to reproduce it by cloning the repo here: https://github.com/tanob/KeePassOSX (branch `import-bridging-header-failed`)

```
$ pod --version                                                                                                                                 14:03:09
0.36.0.beta.2
```

**Comment by orta** [comment]
Looks like KissXML is having issues when being generated as a framework, which looks related to the project bringing in a [c library in a header](https://github.com/hpique/Talks/blob/master/Building%20Swift%20frameworks/Building%20Swift%20frameworks.md#no-cheating). 

Closing as this is not a CocoaPods issue, but that we have to have it build a framework.

**Comment by tanob** [comment]
@orta can you help me understand it better, you mention it isn't a CocoaPods issue but then you also mention "we have to ...". 

From my point of view it IS a CocoaPods issue since that's the tool that configures the Pods project and how the dependencies are built. It's CocoaPods who will need to apply some hack/workaround or structure the dependencies differently to get them well integrated with the dependent project. If not applying some hack/workaround at least it should point people to some example/documentation on how to fix these issues.

**Comment by orta** [comment]
KissXML is a project that was built before framework support was added, as we have to generate frameworks for all dependencies in order to support something that _has_ to be a framework, thus for you KissXML is generated as a framework. 

We wrote a [blog post](http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/) on the most common pitfalls around migration for libraries. CocoaPods can't automatically make a library _always_ work as a framework, in this case KissXML didn't work.

**Comment by tanob** [comment]
I've created a podspec for KissXML and ran `pod lib lint --use-frameworks KissXML.podspec`, here's the output:

```
 -> KissXML (5.0)
    - WARN  |  /tmp/KissXML/KissXML/DDXMLDocument.m:94:47: warning: implicit conversion loses integer precision: 'NSUInteger' (aka 'unsigned long') to 'int' [-Wshorten-64-to-32]
    - NOTE  |  ld: warning: embedded dylibs/frameworks only run on iOS 8 or later

[!] KissXML did not pass validation.
You can use the `--no-clean` option to inspect any issue.
```

It doesn't mention anything like "We failed to get KissXML as a framework". After fixing the warning then the check passes:

```
 -> KissXML (5.0)
    - NOTE  |  ld: warning: embedded dylibs/frameworks only run on iOS 8 or later

KissXML passed validation.
```

Is the lint missing checks? 

As I've mentioned before, the build problem starts the moment I add a reference from the Test target to the main module, if KissXML had any issue to be used as a framework I'd get issues since the moment I've added it to `Podfile`.

Again, I really believe this issue I've reported means that some scenario is not covered by CocoaPods implementation.

**Comment by neonichu** [comment]
The reason why you only see the build failure with the test target is that it is the point where you introduce Swift Pods which opts you in to using frameworks (see <http://guides.cocoapods.org/syntax/podfile.html#use_frameworks_bang>).

Using `pod lib lint` will build the framework, this does not catch non-modular headers, because for that a client project is needed. Linting is necessary, but not sufficient, for ensuring that a library works in practice.

The first and foremost issue of KissXML is usage of libxml2. Unfortunately, Apple does not ship module maps for their dylibs - see CocoaPods/swift#8 for some further reading on that. This is not something CP can fix.
