### ISSUE TITLE
respect the deployment_target of a dependency when building

### ISSUE THREAD

**Issue by mmerickel** [CocoaPods/CocoaPods#3454]
XCode 6.3 has started to use the deployment target of a library when performing static analysis.

Currently CocoaPods overrides the deployment target of the podspec with the platform directive in each target. For example:

```
target 'MyApp' do
    platform :ios, '6.1'
    pod 'CorePlot' # <-- has a deployment_target of 5.0
    pod 'AFNetworking'
end
```

The library `libPods-MyApp-CorePlot.a` will be built with a deployment target of 6.1 instead of 5.0. This causes a lot of warnings in static analysis because CorePlot has shims in the code that make the library work on ios 5.0. However, XCode realizes those shims are no longer necessary if deploying to 6.1+ and emits warnings.

A possible work around for this was to create multiple targets with their own deployment targets:

```
target 'MyApp-50' do
    platform :ios, '5.0'
    link_with 'MyApp'
    pod 'CorePlot'
end

target 'MyApp-61' do
    platform :ios, '6.1'
    link_with 'MyApp'
    pod 'AFNetworking'
end
```

Unfortunately each of these targets has its own xcconfig and CocoaPods doesn't merge these xcconfigs into one, causing issues. So CocoaPods doesn't seem to support two pods linking against the same entry point (`MyApp`).

The correct solution (it seems to me) is that the deployment target should be used from the podspec when building the library. For example, CorePlot has `spec.ios.deployment_target '5.0'`, so when building `libPods-MyApp-CorePlot.a` the deployment target should be set to 5.0. This seems reasonable to me since we're talking about configuring the dependencies, not `MyApp` (which has its own xcodeproj that I configure). Everything works fine if I manually click to set the deployment target on there in the generated xcodeproj, but obviously this gets wiped out when I run `pod update` again.

**Comment by mmerickel** [comment]
No replies? Does everyone use `inhibit_all_warnings!` or something? How are more people not concerned about the compiler warnings being emitted in xcode 6.3? It seems to me this shouldn't be that hard to fix at least conceptually. Just build each pod with its own deployment target instead of the user-specified one. Then use the user-specified target for the aggregate library, or deprecate it altogether.

Obviously I'm sure I'm missing some bw-compat issues.

**Comment by segiddins** [comment]
The deployment target of the app is used since APIs could actually be different for the SDK version you're linking against (and it's that SDK version that matters, not the one the pod declares). Those warnings are as valid as any other, so I see no reason to use the pod's deployment target.

**Comment by mmerickel** [comment]
Your comment feels like it is confusing the compile-time SDK with the deployment target. Of course the user controls the compile-time SDK but the pod/library author controls which SDKs the library will work with at runtime. These are not equal.

**Comment by segiddins** [comment]
But it's being used in the context of the application -- it seems foolish to allow warnings go unseen simply because a pod supports an old iOS version?

**Comment by mmerickel** [comment]
The issue here is that CorePlot (for example) goes out of its way to maintain compatibility with older SDKs (5.0). This is great and commendable. My app only supports 6.1. That doesn't mean I'm supposed to go through CorePlot's source code and remove all of its bw-compat shims. That's ridiculous. It can have a deployment target of 5.0 and build without any warnings if CocoaPods was honoring its podspec.

**Comment by timbodeit** [comment]
I don't think that always using the Pods deployment target (no matter how low it's set) is a good idea.
The change makes sense with static libraries, but should maybe be restricted to them.
In my opinion with `use_frameworks!`, this change is causing more damage than good. 

On all included Pods with a deployment target lower than `8.0` I'm now getting `embedded dylibs/frameworks only run on iOS 8 or later` warnings.
Embedded Frameworks in iOS should (to the best of my knowledge) not be built with a deployment target lower than `8.0`. There may be some exceptions concerning testing frameworks (see [Nimble#102](https://github.com/Quick/Nimble/pull/102) and #3225).
Also Xcode 7.1 doesn't get along very nicely with `5.1.1` deployment target frameworks (most likely a bug in Xcode) and throws an additional linker warning for every file of the respective pod.

##### My suggestion:

CocoaPods should use the deployment target of the spec for static libraries.
When using frameworks, it should also try to use this value, but only if it is >= `8.0` (otherwise falling back to 8.0).
This would minimize issues such as this one or [Alamofire#871](https://github.com/Alamofire/Alamofire/issues/871), without causing additional issues with embedded frameworks.

I'd be happy to make the necessary changes and open a pull request, though I'd like some input first on whether this is the right way to handle the above mentioned issue.
Also I'm not exactly sure how to fit the testing frameworks edge cases into this.

---

@mmerickel I get where you're coming from with the analysing issues. I agree with you on the `thus it should require no changes` point. On a side note (without this really being relevant to the discussion now): To me (without too thorough inspection) this seems like a problem that should be solvable with the right preprocessor statements on the CoreParse side. I can't say that for a fact, since I haven't actually been able to reproduce these analyser warnings.

**Comment by segiddins** [comment]
@timbodeit this would be fixed via https://github.com/CocoaPods/CocoaPods/pull/4537
