### ISSUE TITLE
Dependency with static framework pod unable to reference within target

### ISSUE THREAD

**Issue by markst** [CocoaPods/CocoaPods#3532]
Please accept my apologies for the previous issue. 
However I've since figured more details in regards to the issue.

When defining a podspec with a dependency, the target cannot reference the dependency pod if it contains a static framework.

In this particular case the a spec which requires the 'Google-Maps-iOS-SDK' pod.
I've created a demo project as an example of unable to compile: http://d.pr/f/1lDgp

The resolution for this is to add the following to the spec. 
`s.ios.xcconfig = { 'FRAMEWORK_SEARCH_PATHS' => '$(PODS_ROOT)/Google-Maps-iOS-SDK' }`
Perhaps is expected & this is in fact not an issue?

Forgive me again if this issue does still not meet your guidelines.

**Comment by ashfurrow** [comment]
I'm having a similar issue with the CardFlight SDK.

**Comment by ashfurrow** [comment]
Looks like [this](https://github.com/CocoaPods/CocoaPods/issues/3499) is the same issue.

**Comment by Suz** [comment]
Looks like this might be my problem too. I opened a question on SO: 
http://stackoverflow.com/questions/30632446/framework-search-path-not-set-correctly-by-cocoapods

Can someone give a bit more explanation of the workaround suggested by @markst? Is there a workaround in the target build settings?

**Comment by neonichu** [comment]
@suz since you're working on an ObjC app, #3604 will probably help you. It'll be part of 0.38

**Comment by Suz** [comment]
Thanks. I finally have it working. I'm not entirely sure what the necessary steps were, because it turned out I was trying to load a deprecated header as well. However, renaming my project path to remove any spaces seemed to help. That revealed an error with the latest version of google-cast-sdk-ios framework where the copy pods resources build phase couldn't find the asset bundle properly. I removed the pod and add it manually. That got me to a `dylib: @rpath Pods.framework/Pods file not found` error.  Setting Pods.framework to optional finally fixed that, after trying several other things. Hopefully now I know enough that the next journey won't take so long. ;)

**Comment by chrishulbert** [comment]
A solution I've found is to add these lines to your bridging header (obviously change the paths to suit your pod). This doesn't require you changing your project each time running pod install:

```
#import "../../Pods/GoogleAnalytics/Headers/Public/GAI.h"
#import "../../Pods/GoogleAnalytics/Headers/Public/GAIFields.h"
#import "../../Pods/GoogleAnalytics/Headers/Public/GAIDictionaryBuilder.h"
```

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
