### ISSUE TITLE
Empty podfile makes my project not build

### ISSUE THREAD

**Issue by alper** [CocoaPods/CocoaPods#3617]
This is surely known already but it didn't show up on a search. I removed the last pod from my Podfile, did pod install and then my project wouldn't build anymore.

I don't want to remove cocoapods wholly since I think I will be using it again in the near future but it can happen that your need for pods is at zero. Shouldn't it still work then?

I fixed my problem by adding a generic library as a pod after which my project does build again.

**Comment by segiddins** [comment]
I know this has come up before, but we really should make this work.

**Comment by kylef** [comment]
You can use https://github.com/kylef/cocoapods-deintegrate to deintegrate your project from CocoaPods.

Related to and possibly duplicates #2471.

**Comment by orta** [comment]
Option: We could treat it as a "do you want to remove CocoaPods" and offer how to install cocoapods-deintegrate?

**Comment by alper** [comment]
This situation is actually a case where you don't want to remove CocoaPods but just don't have pods that you want to use at the moment.

One workaround similar to the one I'm using may be: when the Podfile is empty, under the hood pretend that it includes one (mostly empty) package of code and builds that in.

**Comment by dbburgess** [comment]
Consider this a +1. When setting up a project (particularly for a distributed team) where you *know* you're going to use pods, but don't have any specific ones picked out yet, this is a real pain. It'd be nice for it to gracefully work without requiring you to add a pod.

**Comment by iandundas** [comment]
This also applies for the case when you add a pod (say RxSwift) to the main target and other pods (say Quick, Nimble) to the testing target. If I remove the sole main target pod (RxSwift) but still want to keep my testing target pods installed, (say because I switch to ReactiveCocoa and they advise to add manually, not with cocoapods), the main project will no longer build (missing `Target Support Files/Pods-MainTargetName`), but `cocoapods-deintegrate` won't help here either, as we're still using cocoapods for testing. 

*breaths out*
