### ISSUE TITLE
Dropbox pod no longer usable

### ISSUE THREAD

**Issue by cipriancaba** [CocoaPods/CocoaPods#3635]
I have an issue after upgrading from 0.36 with the Dropbox spec since its no longer creating a Pod Target

Before, in the Pods project, a `Pods-ProjectName-Dropbox_iOS_SDK` target was automatically created

Now, unfortunately, this target is missing and I can no longer use 
`import Dropbox_iOS_SDK`

The [podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/Dropbox-iOS-SDK/1.3.3/Dropbox-iOS-SDK.podspec.json) for the Dropbox SDK is the one from the cocoapods specs repo

Is there any workaround this issue? Is it a bug or expected behaviour? I assume that the target is not created because it has no actual source files.. However, this will invalidate all the podspecs that were created in a similar manner

**Comment by neonichu** [comment]
This is expected, because the Dropbox SDK only ships a vendored framework. 

You should be able to import it using `import DropboxSDK`. Unfortunately, their framework doesn't include a module map, so that actually doesn't work and you will need to use a bridging header.

Please report this as an upstream issue, so that they can ship a module map in the future.
