### ISSUE TITLE
Pod frameworks are only codesigned if codesigning is required

### ISSUE THREAD

**Issue by nschum** [CocoaPods/CocoaPods#3646]
After switching to `use_frameworks!`, my Mac app failed to run with the following error:

    /Users/nik/Library/Developer/Xcode/DerivedData/App-hjgvbxcrkfmoglbubiknvpwqfcvj/Build/Products/Debug/App.app: code object is not signed at all
    In subcomponent: /Users/nik/Library/Developer/Xcode/DerivedData/App-hjgvbxcrkfmoglbubiknvpwqfcvj/Build/Products/Debug/App.app/Contents/Frameworks/MASPreferences.framework
    Command /usr/bin/codesign failed with exit code 1

The framework is unsigned because the `Pods-App-frameworks.sh` script only codesignes it if `CODE_SIGNING_REQUIRED` is set (which I believe is only the case on iOS).

    Pods/Target Support Files/Pods-App/Pods-App-frameworks.sh:
    if [ "${CODE_SIGNING_REQUIRED}" == "YES" ]; then
        code_sign "${destination}/$1"
    fi

I think instead it should always sign if the target is being signed, e.g. like this:

    if [ -n "${EXPANDED_CODE_SIGN_IDENTITY}" ]; then
        code_sign "${destination}/$1"
    fi

**Comment by segiddins** [comment]
If @mrackwitz can confirm this, a PR would be very welcome, @nschum!

**Comment by nschum** [comment]
certainly

**Comment by mrackwitz** [comment]
Thanks for pointing out Nikolaj!

As `CODE_SIGNING_REQUIRED` is used to disable codesigning and as both build settings aren't officially documented anywhere, as far as I can tell, I would like to keep the first in conjunction in the condition as shown below.

```bash
if [ -n "${EXPANDED_CODE_SIGN_IDENTITY}" && "${CODE_SIGNING_REQUIRED}" != "NO" ]; then
    code_sign "${destination}/$1"
fi
```

Otherwise Xcode could still expand `CODE_SIGN_IDENTITY` if it isn't explicitly cleared, e.g. by passing in only `CODE_SIGNING_REQUIRED=NO` via the command line.

Does that make any sense to you? Beside a PR, any source, which gives info when those build settings are supposed to be set, would be also more than welcome.

**Comment by nschum** [comment]
Hmm, `CODE_SIGNING_REQUIRED` is used to disable codesigning? That sounds odd to me, but it looks like a lot of people seem to be doing exactly that.

So :+1:. (But it only works because Xcode leaves it out completely when it really means "not required". That might break it in the future.)

There is another flag named `CODE_SIGNING_ALLOWED`, which looks like its actually intended to disable codesigning. I think it would be good to include that as well.

**Comment by AliSoftware** [comment]
This change seems to be the reason why code signing starts to fail on projects using `use_frameworks!` and a non-wildcard Provisioning Profile in #4331 ?

**Comment by szotp** [comment]
Had this problem after using this hack: https://stackoverflow.com/questions/44678958/creating-an-unsigned-ipa-with-xcode-8-3

Discovering the cause was not fun.
