### ISSUE TITLE
library not found for -lPods-AGEmojiKeyboard

### ISSUE THREAD

**Issue by sauchye** [CocoaPods/CocoaPods#3678]
when i remove a pod eg:(AGEmojiKeyboard) and run my project,xcode show error:
ld: library not found for -lPods-AGEmojiKeyboard
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by neonichu** [comment]
You have given us nothing to work with here, there's no way to diagnose your problem without information. Please see our [contribution guidelines](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md) on how file an actionable issue.

However, since you're dealing with deintegration, this plugin <https://github.com/kylef/cocoapods-deintegrate> might help you out.

**Comment by sauchye** [comment]
You can ignore this issue but it did appear.

**Comment by neonichu** [comment]
@sauchye I'm not doubting that, but simply stating that an error occurred doesn't help us fixing it. That's why I linked to the guidelines on filing issues that we can actually solve.

**Comment by sauchye** [comment]
Yeah,maybe you are right.I obtained from the pod for AGEmojiKeyboard it tips error.but fortunately,i fix it , still thanks a lot.
