### ISSUE TITLE
Operation not permitted - /usr/bin/xcodeproj

### ISSUE THREAD

**Issue by bryan1anderson** [CocoaPods/CocoaPods#3692]
I get this error every time I try and run

sudo gem install cocoapods

ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/xcodeproj

**Comment by lfarah** [comment]
Getting the same thing...

**Comment by neonichu** [comment]
Obviously, we need a bit more information, e.g. what OS version you are running on.

**Comment by lfarah** [comment]
I'm running El Capitan. Was forced to downgrade and now it works

**Comment by segiddins** [comment]
the issue here is rootless and the default gem home conflicting

**Comment by abelsu** [comment]
How to slove it ? I get the same thing:-(

**Comment by bspringston** [comment]
Also on OS X El Capitan and getting the same error.  Any known resolution without downgrading?

**Comment by neonichu** [comment]
# Installing CocoaPods on OS X 10.11

## Custom `GEM_HOME`

This is the solution when you are receiving the "Operation not permitted" error.

```bash
$ mkdir -p $HOME/Software/ruby
$ export GEM_HOME=$HOME/Software/ruby
$ gem install cocoapods
[...]
1 gem installed
$ export PATH=$PATH:$HOME/Sofware/ruby/bin
$ pod --version
0.37.2
```

## Standard system installation

For whatever reason, the rootless stuff seems less restrictive when one simply upgrades the system. I could `sudo gem install cocoapods` just fine on a machine upgraded from 10.10 - however, binstubs are no longer installed into `/usr/bin`:

```bash
$ sudo gem install cocoapods
[...]
1 gem installed
$ export PATH=$PATH:/Library/Ruby/bin
$ pod --version
0.37.2
```

Note: I've locked the issue to collaborators so that these instructions don't get buried for now.
