### ISSUE TITLE
Fail more gracefully when git is unavailable

### ISSUE THREAD

**Issue by segiddins** [CocoaPods/CocoaPods#3698]
See #3697

**Comment by k0nserv** [comment]
From my research this should already be handled [here](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/executable.rb#L51)

**Comment by segiddins** [comment]
Ah, but that code path isn't used when we use Kernel.`

**Comment by k0nserv** [comment]
So this is related to the downloading/updating of the specs rather than fetching the pods themselves?

**Comment by segiddins** [comment]
Yeah. Answer might just be to use executable for everything?

**Comment by k0nserv** [comment]
I think this is the what causes it then https://github.com/CocoaPods/CocoaPods/commit/6cb43f1769e1582e5a6ce872b7f08c976a3d7867

However I wonder if `$?` works with popen3?

**Comment by segiddins** [comment]
> However I wonder if $? works with popen3?

Probably not, but you can probably use `git!` and if it doesn't raise an exception, it succeeded.

**Comment by k0nserv** [comment]
That's a bit problematic since we raise `Informative` errors which if we caught them would obscure the original reason for the issue

[Here's](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/executable.rb#L52-Lundefined) the one when the binary is not found
[Here's](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/executable.rb#L70) The one that raise if `raise_on_failure` is `true`
[Here's](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/sources_manager.rb#L384) Another one that wouldn't be caught, but that we should still be triggering

Having `git_repo?` return the success seems like the most reasonable approach or making a subclass for this [error](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/executable.rb#L70) so we can catch only it

**Comment by segiddins** [comment]
What about introducing `git?`

**Comment by k0nserv** [comment]
What would `git?` do? Just verify if the binary exists?

**Comment by segiddins** [comment]
The question mark version would raise if the binary isn't found, return nil if the command fails, otherwise returns the output string?

**Comment by k0nserv** [comment]
Okay yes, that sounds like a good approach

**Comment by segiddins** [comment]
This can no easily be done by replacing all uses of `Kernel#backtick` with `Executable.capture_command`

**Comment by segiddins** [comment]
We've made lots of progress on this one. Closing.
