### ISSUE TITLE
Import static library with sources

### ISSUE THREAD

**Issue by confile** [CocoaPods/CocoaPods#3700]
I tried to import a precompile lib in my podspec. It works only if I import the headers only in ``source_files``:

```
s.source_files = ' srcDir/**/*.{h}
```

When I import the ``.m`` files as well in ``source_files`` then I get a compile error in Xcode saying that there are duplicates. 

Is it possible to import the sources of a static library as well which then can be used for debugging?

**Comment by neonichu** [comment]
No, this is not possible. What would be the purpose of providing a static library in the same podspec when there is already source code?

**Comment by confile** [comment]
The purpose is to have the static library precompiled an be able to browse source code while debugging as well. 

So assume I included my headers ``.h`` and my static lib ``libmystaticlib.a``. Is there any chance I can browse source code in xcode?

**Comment by neonichu** [comment]
AFAIK, this is not something Xcode even supports doing (associating source files to a precompiled library).

**Comment by confile** [comment]
To summ this up. I can online browse source code without using a static lib?

**Comment by orta** [comment]
Yes

**Comment by confile** [comment]
Thanks

**Comment by advayDev1** [comment]
Hi, sorry to reopen this, but here's what we're trying to do (for j2objc-contrib/j2objc-gradle#192).  We have already built a static library from some auto-generated headers/source and we link to that library.  We don't want to include those files as source in the podspec/xcode project, since they will be compiled again.  But we'd like to include the folders of source as 'referenced files' (not copied into the project directory, and also not as compile sources in any target).  I don't see addition of such files in pods via a quick look at:
https://guides.cocoapods.org/syntax/podspec.html#tab_group_root_specification
(but I don't use pods myself, just working with @confile on this)

cc: @confile @brunobowden

**Comment by segiddins** [comment]
You can add them to the `preserve_paths` if you don't want them to be deleted, and also not added to the Xcode project.

**Comment by advayDev1** [comment]
we want them in the Xcode project as 'referenced files' so that autocomplete, ctrl-click, etc. still works.  we just don't want the files copied to other paths OR to be compiled.  In the latest Xcode, you do Add Files to Project, select the root folder of source, and check Create folder references.  Anyway to replicate this in podspec?

**Comment by segiddins** [comment]
Nope, not something CocoaPods currently supports, and probably enough of a niche case that it’s not something we plan on adding.

**Comment by confile** [comment]
@advayDev1 Autocomplete works in xcode using header files and static library. The only thif which is not working is browsing the .m files.

**Comment by advayDev1** [comment]
ah you are correct.  you are our primary pod dev/user right now on j2objc-gradle, so if that level of support is sufficient for you, then we're good =)
