### ISSUE TITLE
Pods files not cleaned after switching to local files (by :path)

### ISSUE THREAD

**Issue by ssuchanowski** [CocoaPods/CocoaPods#3724]
There is an issue when we change the pod source from github to local (using :path). If I do any changes to the files then they are correctly changed at the path they exist but pods project haven't cleaned the files previously imported from github so it's resulting in pointing the right catalog in the project file but using old files that are stored in "/Pods". I did `pod update` and `pod install` - no help.

I am using version 0.37.2.

**Comment by segiddins** [comment]
This sounds like the sort of thing a clean build / deleting derived data would fix?

**Comment by ssuchanowski** [comment]
nope, xcode doesn't care about pods files

**Comment by segiddins** [comment]
In that case, could you please outline steps we could use to reproduce the issue? Thanks!

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
