### ISSUE TITLE
Framework works in podfile but not in podspec

### ISSUE THREAD

**Issue by mergesort** [CocoaPods/CocoaPods#3841]
I've been including `Fabric`, `TwitterCore`, and `TwitterKit` as dependencies in the podfile for my app, and that's working great. On the other hand, I made a development pod, and tried to declare those as dependencies like such

```
s.dependency 'Fabric'
s.dependency 'TwitterCore'
s.dependency 'TwitterKit
```
and get this error:

```
[!] The 'Pods' target has transitive dependencies that include static binaries: (projectRoot/Pods/Fabric/Fabric.framework, 
projectRoot/Pods/TwitterCore/TwitterCore.framework, and 
projectRoot/Pods/TwitterKit/TwitterKit.framework)
```

Even if I remove those dependencies from my podfile, it doesn't seem to work. Any thoughts on what I could/should do?

Thanks a lot!

**Comment by segiddins** [comment]
Not really much you can do -- it's as the error message says. You can't have static binaries that are transitive dependencies of multiple dynamic binaries, since that would lead to duplicate symbols and non-deterministic behavior.

**Comment by mergesort** [comment]
So it looks like https://github.com/CocoaPods/CocoaPods/pull/3844 shows that this functionality isn't possible in CocoaPods. I'm still stuck trying to figure out what I should do in my case.

My app is structured as such. There's an app target, a `Core` development pod, which is the models for my app. I separated out the `SocialCredentials` (for Twitter/Facebook interactions) into it's own development pod, so that way I could compile the `Core` without this for now, but ultimately the Core is dependent on the `SocialCredentials` (including `TwitterKit`, `TwitterCore`, `Fabric`, etc) development pod.

I could put SocialCredentials back into Core, but the issue still remains that my development pod won't be able to declare `Fabric`, `TwitterCore`, and `TwitterKit` as dependencies. I also can't keep the `SocialCredentials` in the main app target, because `Core` needs to know about it.

Is there some approach that I'm missing that could skirt around the transitive dependencies, and still be able to have the separation and/or app compilation?

**Comment by neonichu** [comment]
I'm afraid there is no good solution, but since this is (and will be for a while) a recurring topic, let's look at the options:

1. Wait until Fabric ships dynamic frameworks, which would solve all your problems :rainbow: 
2. Integrate using static libraries instead of frameworks. Of course, this might not be possible because you are required to use frameworks, e.g. because of having Swift dependencies.
3. Use a hacky workaround (inspired by [this comment](https://github.com/CocoaPods/CocoaPods/issues/3289#issuecomment-83075682) of someone who uses it in production :grin:): 

- Monkey-patch the error out using something like [this](https://github.com/CocoaPods/CocoaPods/issues/3289#issuecomment-84005488)
- Use `-undefined dynamic_lookup` to ignore linker issues

This is quite dangerous, because all linker errors will now be runtime errors, but should work until option 1 becomes a reality.
