### ISSUE TITLE
Is it possible to add a custom argument to a pod method request

### ISSUE THREAD

**Issue by sigmonky** [CocoaPods/CocoaPods#3860]
I would like to be able to pass a custom parameter to a podspec via a specification on the invoking pod method call. Something like:

pod 'mypodspec','1.0','<custom argument value>'

Is that possible? Or is there an alternative method for doing this.

**Comment by amorde** [comment]
Are you just trying to point to a custom `.podspec` somewhere? Because to do that you can do:

```
pod 'JSONKit', :podspec => 'https://example.com/JSONKit.podspec'
```
To answer your question however - no, there is currently no way to provide custom functionality to the `pod` method of the podfile.

There are also `pre_install` and `post_install` hooks that allow you to do custom setup

**Comment by segiddins** [comment]
The best way to do that is by using different [subspecs](https://guides.cocoapods.org/syntax/podspec.html#subspec).
