### ISSUE TITLE
How to set Build Option ENABLE_BITCODE for some pod?

### ISSUE THREAD

**Issue by Ewg777** [CocoaPods/CocoaPods#3936]
Hi,
How to set Build Option ENABLE_BITCODE for a pod in .podspec?

**Comment by neonichu** [comment]
This will be set automatically where appropriate by #3744

**Comment by shortstuffsushi** [comment]
Hi @neonichu, I'm curious what the state of this is now, since you closed #3744. Today is the first time I've run into this issue, and I'm not really sure the appropriate solution.

**Comment by shortstuffsushi** [comment]
Ahh, never mind, it seems that the issue was coming from somewhere else within the project (I had a local code copy it was referencing, and not the Pods folder, as I was testing different distribution mechanisms). I noticed in the Pods project that this seems to be defaulted to `YES` now, so it should work.
