### ISSUE TITLE
Require certain base SDK through podspec

### ISSUE THREAD

**Issue by lumaxis** [CocoaPods/CocoaPods#4199]
I want to require Xcode 7/iOS 9 as a base SDK but still have iOS 7 as the deployment target a pod and thought that declaring the `platform` as `:ios, '9.0'` and `deployment_target` as `'7.0'` would do exactly this but `pod install` (using version `0.38.2` and `0.39.0.beta.4`) still goes through perfectly fine but then of course building fails with Xcode 6.4 and the iOS 8.4 base SDK.
Am I missing some part in the documentation or is there maybe just no way currently to achieve what I want to do?

**Comment by segiddins** [comment]
I don't think that's something we currently support.

**Comment by lumaxis** [comment]
@segiddins Hm, interesting. Somethings I found while researching suggested otherwise (see for example [this StackOverflow question](http://stackoverflow.com/questions/16759064/how-to-ignore-the-base-sdk-for-a-single-pod) and we've also actually had someone run into an [issue](https://github.com/bitstadium/HockeySDK-iOS/issues/199) when trying to integrate our pod in a lower version.
Do you think this could be a supported scenario for CP in the future? And would the `platform` attribute be the right place to hook into?

**Comment by segiddins** [comment]
Honestly, it's not something I feel we need to support... It makes sense to me to always assume the latest production SDK, and `#error` if that precondition isn't met (if necessary)

**Comment by segiddins** [comment]
@orta thoughts on this one?

**Comment by orta** [comment]
Part of me wants this, mainly because of Swift support ("Oh, I downloaded a swift 1.2 lib - my app is 2.1" :-/ ) as Apple have no problem breaking everyone's stuff.

The only useful thing we could do here is add some runtime checking in the compare against the sandbox podfile.lock. You may have your `xcode-select` path to xcode6.4 for the moment but that doesn't mean you're developing apps in xcode6, so during `pod install` time it shouldn't die.

An optimal version could look like
```
Pod::Spec.new do |s|
  s.name     = 'Quick'
  s.version  = '1.0.4'
  s.swift    = '1.2'
end
```
and also support the format of
```
Pod::Spec.new do |s|
  s.name     = 'Quick'
  s.version  = '1.0.4'
  s.xcode    = '~> 6.4'
end
```

Where I guess it would end up creating for swift 1.2 `"> 6.1.0", "< 7"` where we just have some constants in xcodeproj, with the most recent being open-ended.

**Comment by segiddins** [comment]
And then you'd have to specify the swift and Xcode versions in your podfile?

**Comment by orta** [comment]
I hadn't thought of that, but I think that makes sense, yes.

**Comment by segiddins** [comment]
I think apple is fixing this for us with support for swift version conditionals. Closing because I don't foresee us actually implementing this.
