### ISSUE TITLE
Don’t burden lib maintainers with mistakes made in specs by spec maintainers

### ISSUE THREAD

**Issue by alloy** [CocoaPods/CocoaPods#4200]
Sometimes specs are not maintained by lib authors/maintainers. Sometimes those spec maintainers mess up a spec and thus a fixed spec needs to be pushed. We’re all human.

However, currently we usually require a new version to be released, which means the lib authors/maintainers need to push a new tag, just because of a mistake outside of their lib/repo.

In these cases we should have a better policy which doesn’t require a new version.

/cc @keith

**Comment by orta** [comment]
We regularly allow [small changes to podspecs](https://github.com/CocoaPods/Specs/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+is%3Amerged) - in the last two days these came through

* https://github.com/CocoaPods/Specs/pull/13495
* https://github.com/CocoaPods/Specs/pull/13495

This is nothing new.

**Comment by rnapier** [comment]
The trouble as a provider (who doesn't actually care much about CP; my users just bug me about it), is that the docs strongly discourage it. So I wind up having to tag a new release just to fix the podspec, leading to "CocoaPods continues to be a pain in my butt and I don't even use it."

I think the best approach is to allow versioning of specs using semver metadata. You should be able to have multiple versions of podspecs that all point back to the same version of the code. For example, I should be able to push version 3.0.0 of the podspec that points to 3.0.0 of the code. I then should be able to push version 3.0.0-1 of the podspec that still points to 3.0.0 of the code.

This may be possible today, just undocumented.

**Comment by segiddins** [comment]
It definitely is possible, though I believe a warning will be given.

**Comment by keith** [comment]
There's a lot of context from twitter folks are missing. Here is [some of it](https://twitter.com/alloy/status/644527187786395648).

Like @orta said we have no problem accepting fixes to podspecs. These are pretty rare for most libraries since often once a library maintainer makes a podspec that works, there are minimal changes in the future besides bumping the version number.

I think it's still important that these changes are made, or approved, by a contributor on trunk. Like @alloy said on twitter, you can add anyone you want to be in charge of this. To me this ensures that someone will be responsible for fixing the spec, if the fix doesn't stick. Many libraries where the author doesn't maintain the podspec have very active consumers maintain it instead.

I think adding versions to podspecs that don't correspond to release versions could be confusing to users. And since we allow changes via pull requests, which are very low volume and typically quickly merged, I don't see the need for this either.

**Comment by alloy** [comment]
I don’t think we need to add anything either, more that we’re all on the same page that such changes are allowed. (Because the general sense is that it’s not allowed at all, which doesn’t stop the people not reading the docs, but does those that want to do the right thing.) But I think the consensus is that we are on the same page, so :+1:

**Comment by orta** [comment]
Cool, I'm closing this. 

I also don't think supporting multiple per-version podspecs is a good idea, it adds a separation that doesn't really make sense and would require extra documentation that can only raise the barrier to entry.
