### ISSUE TITLE
Improvement: Centralising storage for pods on every machine instead of every project

### ISSUE THREAD

**Issue by mehulmind123** [CocoaPods/CocoaPods#4298]
I think, we can store downloaded pods at some specific location on every OS X Machine, instead of storing it on every project folder.

As every developer mostly working on more projects, even if developer is working on single project he/she is checking more open source controls/projects from cocoacontrols/github and downloading sample codes to play around with it. Now a days, mostly open source projects have some common pods already added, so evert project have to download same pods separately, also it will use network bandwidth.

So, if we can apply this, we can save space on local machine, save developers network bandwidth.

What everyone say about this?

**Comment by segiddins** [comment]
CocoaPods already has download caching?

**Comment by kylef** [comment]
Hi @mehulmind123,

Thanks for your feedback. Since a few versions back CocoaPods will now cache Pod sources into `~/Library/Caches/CocoaPods` so they will not be downloaded again and again (unless of course you are using a different version).

```
$ pod cache list
Hyperdrive:
  - Version: 0.2.0
    Type:    External                                                               Spec:    /Users/kyle/Library/Caches/CocoaPods/Pods/Specs/External/Hyperdrive/d631475f712bed81cff1632d2025dc5c-7362f.podspec.json
    Pod:     /Users/kyle/Library/Caches/CocoaPods/Pods/External/Hyperdrive/d631475f712bed81cff1632d2025dc5c-7362f
```

As for your other comment about saving disk space, the amount of space used for the source code of pods should not be much (if it is, perhaps the Pods you are using are too bloated?). The source files of a Pod can differ depending on platform, subspecs used, and version of a Pod. As such the source for a pod in one project can vastly differer from it's source in another.

We also [recommend checking in your Pods directory](http://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control) which would defeat the purpose of sharing pods source as they would be committed directly to your projects repository.

Considering these points, there would be very little benefit of adding this to CocoaPods, and it would greatly complicate the code-base.

If you are interested in having such feature, you can take a look at our plugin architecture. You may be able to write a plugin that offers this behaviour if you would like it.
