### ISSUE TITLE
issues on El Capitan OS

### ISSUE THREAD

**Issue by mltk96** [CocoaPods/CocoaPods#4302]
after updating my OS to El Capitan i'm running issue with cocoa pods.
when trying to install it, i get the following error:
Error loading RubyGems plugin "/Library/Ruby/Gems/2.0.0/gems/yard-0.7.5/lib/rubygems_plugin.rb": cannot load such file -- rubygems/doc_manager (LoadError)
Successfully installed cocoapods-0.38.2
Parsing documentation for cocoapods-0.38.2
1 gem installed

then, when trying to update one of my projects, i'm getting the next error (not sure if it's released to the prior RubyGems error):
Analyzing dependencies
dyld: warning, LC_RPATH @executable_path/../../../../../../../SharedFrameworks in /Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/../../..//DVTInstrumentsFoundation.framework/Versions/A/DVTInstrumentsFoundation being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/Xcode3Core being ignored in restricted program because of @executable_path
Downloading dependencies

any suggestions?

**Comment by ylecuyer** [comment]
Same here

**Comment by segiddins** [comment]
Seems to just be a system ruby issue?

**Comment by drwin** [comment]
Same hero

**Comment by ppamorim** [comment]
same here

**Comment by segiddins** [comment]
This should just be a warning, is it _actually_ affecting installation for anyone?

**Comment by LastObject** [comment]
Updating local specs repositories
Analyzing dependencies
dyld: warning, LC_RPATH @executable_path/../../../../../../../SharedFrameworks in /Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/../../..//DVTInstrumentsFoundation.framework/Versions/A/DVTInstrumentsFoundation being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/Xcode3Core being ignored in restricted program because of @executable_path
Downloading dependencies
Installing AFNetworking (2.6.0)

[!] Error installing AFNetworking
[!] /usr/bin/git clone https://github.com/AFNetworking/AFNetworking.git /var/folders/6t/kt9rd7f512737cmnt2wcw2440000gn/T/d20151004-3135-v6aygu --single-branch --depth 1 --branch 2.6.0 --recursive

Cloning into '/var/folders/6t/kt9rd7f512737cmnt2wcw2440000gn/T/d20151004-3135-v6aygu'...
fatal: unable to access 'https://github.com/AFNetworking/AFNetworking.git/': SSLRead() return error -9806


[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`
dianyis-MacBook-Pro:SmileCampus Eric$ pod install
Updating local specs repositories
c^C[!] Cancelled
＊-MacBook-Pro:SmileCampus Eric$ pod repo update --verbose

Updating spec repo `master`
  $ /usr/bin/git pull --ff-only

**Comment by eflyjason** [comment]
same here :(

**Comment by ylecuyer** [comment]
@segiddins It doesn't seem to affect installation

**Comment by sonnytron** [comment]
It affects installation for me.  
I'm cloning a repo that has ZERO issues for every other developer when they: clone, pod install, run workspace and build.  
When I pod install, I get these warnings in pod install:  
Analyzing dependencies  
dyld: warning, LC_RPATH @executable_path/../../../../../../../SharedFrameworks in /Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/../..  /..//DVTInstrumentsFoundation.framework/Versions/A/DVTInstrumentsFoundation being ignored in restricted program because of @executable_path  
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib being ignored in restricted program because of @executable_path  
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib being ignored in restricted program because of @executable_path  
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/Xcode3Core being ignored in restricted program because of @executable_path  
And then further down:  
[!] The `*Project name deleted NDA*' [Debug]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods/Pods.debug.xcconfig'. This can lead to problems with the CocoaPods installation  
    - Use the `$(inherited)` flag, or  
    - Remove the build settings from the target.  

[!] The `*Project name deleted NDA*` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.debug.xcconfig'. This can lead to problems with the CocoaPods installation  
    - Use the `$(inherited)` flag, or  
    - Remove the build settings from the target.  

[!] The `*Project name deleted NDA*` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods/Pods.release.xcconfig'. This can lead to problems with the CocoaPods installation  
    - Use the `$(inherited)` flag, or  
    - Remove the build settings from the target.  

[!] The `*Project name deleted NDA*` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.release.xcconfig'. This can lead to problems with the CocoaPods installation  
    - Use the `$(inherited)` flag, or  
    - Remove the build settings from the target.  
I've tried a LOT of recommended solutions online like adding $inherited or $(inherited), deleting Debug/Release flags in Build settings, checking consistency for architecture settings on both project target and Pods target, I've tried removing master repo, pod setup and another pod install.  
And it should NOT be this complicated... If I have to manually drag and drop pod frameworks to my project file, that's going to seriously affect my push requests when I start building new models/controllers using my incorrectly linked frameworks on my Frankenstein El Capican't build.  
Please help me get this resolved using the actual pod install because right now it's NOT working.  
When I build, I get this build error:  
ld: library not found for -lPods-HockeySDK  
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by justjoeyuk** [comment]
:+1: also seems to break the installation of my pods

**Comment by neonichu** [comment]
I don't see any evidence that the `dyld` warnings are actually affecting installation. The warnings will be silenced in a future release (see #312).

Please don't get distracted and open individual issues, because everyone on this thread has had different ones so far and there's no way to properly deal with them in a single issue.

**Comment by wvalenzuela** [comment]
for LC_RPATH @executable_path/ problem you need to disable System Integrity Protection of El Capitan with  csrutil disable in recovery mode

**Comment by ZzAntares** [comment]
@wvalenzuela could you give more details in that? what is the procedure to do it, and why this happens?

Thanks
