### ISSUE TITLE
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

### ISSUE THREAD

**Issue by goktugyil** [CocoaPods/CocoaPods#4498]
I am using Xcode Version 7.0.1 (7A1001) with `Cocoapods`. 

My app builds & runs fine on my simulator and device. 

When I try to archive the project I get this error:

[![enter image description here][1]][1]

    xcodebuild -project InstaApp.xcodeproj -scheme TryProjects

When I use command line build, I get this error:

[![enter image description here][2]][2]

I tried getting rid of `Alamofire` but then the error moved on to the next import which is `SwiftyJSON`. I got rid of that then it moved on to `Alamofire` from the next file.

I tried `Cocoapods` reinstalling, changing pods, removing pods, compiler optimizations, deleting test cases, clean building, changing compile order, removing frameworks, readding frameworks, almost everything on the internet about this subject and more. But still, I cannot archive my project. 

I had no problem 5 days ago. I didn't update Xcode or anything since then. Changed a few Cocoapods settings, added some new pods and thats it. What could be the problem here?

  [1]: http://i.stack.imgur.com/6pBZZ.png
  [2]: http://i.stack.imgur.com/dv9On.png

**Comment by kmalkic** [comment]
I got the same issue with my own framework in release mode.
This is somehow due to SWIFT_OPTIMIZATION_LEVEL defined as Fast. If you set it to None, it will succeed.
As for cocoapods it does not allow you to override the value.
I've been playing in target_installer.rb and added in the custom_build_settings , settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
Since then validation passes. But this is not a fix!
I wonder why the compiler fails in Fast.

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!

**Comment by PraveenProIos** [comment]
Try to re-create the class. And one more thing
I create below like This 

 1. swift file --> confirmOrderVC
 2.CoacoaTouch class -->  confirmOrderVC

both files will be created as well as  I can run the code this issue returns 
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1


Try to re-create the class issue is gone.
