### ISSUE TITLE
Build issue with cocoapods

### ISSUE THREAD

**Issue by mlloyd** [CocoaPods/CocoaPods#4621]
I have a bug with cocoapods when using the master, branch. 
I was using this to solve a couple of other issues with regards to tvos.

However, the latest version, appears to not create the framework, in the normal way, it's sprinkled all over the build output dir. I have a project here; https://github.com/mlloyd/cocoapods_exampleBug.git
![screen shot 2015-12-01 at 15 10 23](https://cloud.githubusercontent.com/assets/2125109/11512753/adc52604-983d-11e5-9235-a86038f56e2e.png)

**Comment by neonichu** [comment]
I don't see this issue with the example you provided, it builds just fine. Also the screenshot doesn't seem to match the example, as the FB SDK isn't even specified in the Podfile there: `https://github.com/mlloyd/cocoapods_exampleBug/blob/master/Podfile#L8-L17`. Could you please update the example so that it reproduces your problem?

**Comment by mlloyd** [comment]
The project produces the issue only when using the master branch, have you tried? I'm at commit ae13ab00df6819448f2c9eaf66f5f52d4a6bb04e

**Comment by segiddins** [comment]
@mlloyd is this still an issue in the 1.0 betas?

**Comment by mlloyd** [comment]
Not an issue for me anymore, thanks.
