### ISSUE TITLE
Error exporting archive for app store (bitcode + app symbols)

### ISSUE THREAD

**Issue by tonyxiao** [CocoaPods/CocoaPods#4624]
Recently got this error as I tried to export app store archive. (not submitting, just exporting) This only happens when exporting with both bitcode + appsymbol enabled for app store submmission. 
```
2015-12-03 18:16:01 +0000 [MT] Presenting: Error Domain=IDEFoundationErrorDomain Code=1 "The archive did not contain <DVTFilePath:0x7ffdd942a4b0:'/Users/Tony/Library/Developer/Xcode/Archives/2015-12-03/0 2015-12-03 09.59.20.xcarchive/BCSymbolMaps/66CC42D1-FA54-3419-A0BE-58363B1E699C.bcsymbolmap'> as expected." UserInfo={NSLocalizedDescription=The archive did not contain <DVTFilePath:0x7ffdd942a4b0:'/Users/Tony/Library/Developer/Xcode/Archives/2015-12-03/0 2015-12-03 09.59.20.xcarchive/BCSymbolMaps/66CC42D1-FA54-3419-A0BE-58363B1E699C.bcsymbolmap'> as expected.}
 ```
Did a little googling around, and it seems that it Carthage had to recently patch itself to copy bcsymbolemap files (https://github.com/Carthage/Carthage/pull/853). I was wondering whether this also applies to cocoapods?

**Comment by cahlbin** [comment]
I'm seeing this issue too. The scenario is I have a framework bundle, say MyFramework.framework, I  that is a Swift / dynamic framework which have .bcsymbolmap included in it to begin with. Then when that framework is integrated into an application target with CocoaPods, the .bcsymbolmap are not included in the "repackaged" Pods.framework, and thus the upload / validating to Apple App Store fails.

(I've also verified that adding the original MyFramework.framework directly to the target application's Embedded Binaries (i.e. not integrating via CocoaPods) works fine, so it seems to be a CocoaPods issue)

**Comment by AnarH93** [comment]
the same problem. swift + dynamic framework, bitcode + appsymbols enabled.

**Comment by maciekish** [comment]
+1

**Comment by segiddins** [comment]
Anyone want to make a PR with a fix to the embed frameworks script?

**Comment by maciekish** [comment]
Here is an `Archive` `Post Action Script` (**not** a Build Phase Script) that fixes the issue temporarily

    cp "${SRCROOT}/Carthage/Build/iOS/"*.bcsymbolmap "${ARCHIVE_PATH}/BCSymbolMaps/

**Comment by maciekish** [comment]
Oh dear, i had this issue in Carthage!

**Comment by keybuk** [comment]
Find the framework in the app's file list, and change the "Location" from "Absolute", to "Relative to Build Products"

**Comment by tang3w** [comment]
@keybuk After changing the path to "Relative to Build Products", "Archive" will failed. Xcode tell me that:

![image](https://cloud.githubusercontent.com/assets/2226563/13910508/3b2807e2-ef5e-11e5-926e-95c1986081d0.png)

**Comment by keybuk** [comment]
I found that you have to be super-careful about setting all this up:

http://netsplit.com/xcode-two-apps-with-a-shared-private-framework-in-a-workspace <http://netsplit.com/xcode-two-apps-with-a-shared-private-framework-in-a-workspace>

I suggest setting it up from scratch following this procedure, it works every time for me… even doing minor changes like clicking buttons, rather than dragging, can produce the wrong results 😔 

Scotty

**Comment by neonichu** [comment]
This issue has been inactive for some time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
