### ISSUE TITLE
Pushing a new release doesn't update documentation

### ISSUE THREAD

**Issue by gk-brown** [CocoaPods/CocoaPods#4655]
Creating a new issue since I can't re-open issues. See original issue #4654:

https://github.com/CocoaPods/CocoaPods/issues/4654

I see that the 1.5 docs are available here:

http://cocoadocs.org/docsets/MarkupKit/1.5/

However, the main documentation has not been updated. It is still reflecting an earlier version of the README:

https://cocoapods.org/pods/MarkupKit

The differences might not be obvious at first glance, but the main doc is definitely out of date. I would expect the main documentation to reflect the latest version of the README, not an earlier version.

**Comment by neonichu** [comment]
probably something for @orta to look at

**Comment by orta** [comment]
Hrm, sometimes this happens, still not found the root cause of these, It seems to happen occasionally, at random, I usually trigger [a redeploy](http://orta.github.io/rebase/why-cant-i-expand) and it fixes it. In either case, this issue is covered in the cocoapods.org/cocoadocs.org issue, so it can be closed from here where nothing is actionable.
