### ISSUE TITLE
Centralize HEADER_SEARCH_PATH in a common xcconfig

### ISSUE THREAD

**Issue by AliSoftware** [CocoaPods/CocoaPods#4724]
This is an internal feature that will allow commits after a `pod install` to be smaller by centralizing the `HEADER_SEARCH_PATH` settings in a common `xcconfig` file.

---

### Issue

Every time we add a pod in the Podfile, and thus every `.xcconfig` file — associated with each Pod — is regenerated, it adds the search path of that new pod in the `xcconfig`'s `HEADER_SEARCH_PATH`.

That changes has the effect that the diff after a `pod install` flag every `xcconfig` file as "changed" and needs to be committed, making the commit diff a bit polluted.

### Propose solution

An improvement would be to make each Pod's `xcconfig` file `#include "common_search_path.xcconfig"` and declare those `HEADER_SEARCH_PATH` in that common `xcconfig`.
This way, when we add a Pod and do a `pod install` and every `xcconfig` is regenerated, _only_ the `common_search_path.xcconfig` file will have a diff (instead of having every Pod's `xcconfig` file to commit, only the common one will need to be committed), which will make commits smaller (and easier to review)

### Considerations

This approach might present a challenge with target de-duplication and CP 1.0's new target inheritance mechanism, which may introduce the need for multiple common xcconfigs depending on the configurations and contexts

**Comment by mrackwitz** [comment]
You're right about your considerations regarding target de-duplication. As the header search paths are generated individually per target, the complication doesn't seem to be worthwhile to me. This is especially true, because this wouldn't be easy to follow anymore and throw up naming issues (`Pods-Foo-Bar-shared.xcconfig`), which could easily wipe out the advantage of reduced SCM pollution as all the imports would need to be updated as well.

In addition to that, this overlaps with the more general issue #2467.

(Also this is not a `t4:internal` as this brings user-facing changes.)

**Comment by mrackwitz** [comment]
@segiddins @neonichu: Any opinions?

**Comment by segiddins** [comment]
Agree this no longer really makes sense with the last set of deduplication changes. If we can come up with a way to simplify the XCConfigs, great, but I don't think it needs to be an issue.

**Comment by neonichu** [comment]
I agree with @segiddins

**Comment by mrackwitz** [comment]
Great, same here.

**Comment by AliSoftware** [comment]
I think it's not worth the effort anymore, esp with the implementation complexity that would rise due to dedup.
