### ISSUE TITLE
Cannot uninstall Cocoapods from ElCapiten

### ISSUE THREAD

**Issue by MobileDevVT** [CocoaPods/CocoaPods#4770]
Hi,
I had OSX Yosemite and I had Cocoapods installed on it. Then I upgraded my system to El Capiten and found instructions on how to install Cocoapods on El Capiten. I followed these instructions 
https://github.com/CocoaPods/CocoaPods/issues/3692
Afterwards I did a 
list gem list --local | grep cocoapods 
and saw I have bunch of versions of Cocoapods so I decided to uninstall them all and make a clean install. This is the list I saw

cocoapods (0.39.0, 0.37.2, 0.37.1)
cocoapods-core (0.39.0, 0.37.2, 0.37.1)
cocoapods-deintegrate (0.2.1)
cocoapods-downloader (0.9.3, 0.9.0)
cocoapods-plugins (0.4.2)
cocoapods-search (0.1.0)
cocoapods-stats (0.6.2)
cocoapods-trunk (0.6.4, 0.6.1, 0.6.0)
cocoapods-try (0.5.1, 0.4.5, 0.4.4)

While I was unistalling cocoapods-try I got messgage
ERROR:  While executing gem ... (Gem::InstallError)
    cocoapods-try is not installed in GEM_HOME, try:
	gem uninstall -i /Library/Ruby/Gems/2.0.0 cocoapods-try
So I tried that one.

I have succeeded in uninstalling all of them except one. Now when I do 
gem list --local | grep cocoapodsd
I get 
cocoapods (0.39.0)

And whatever I do it just won't go away :) How can I remove this last one so I can make clean install? 
Thanks

**Comment by neonichu** [comment]
What's the error you are getting when trying to uninstall that last gem?

**Comment by MobileDevVT** [comment]
I don't get an error. I just get the prompt. But when I type
list gem list --local | grep cocoapods 
I see that cocoapods (0.39.0) is still there.

**Comment by segiddins** [comment]
Can you try `gem uninstall coocapods` and choose all if/when it prompts?

**Comment by segiddins** [comment]
Closing due to lack of response.

**Comment by rushk2112** [comment]
I am trying to clean out old versions of Cocoapods and move to the .bash_profile settings instead of sudo installs after upgrading to El Capitan.

Here's what I tried:
HarpoMarx:~ devUser$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.2.2
  - RUBY VERSION: 2.0.0 (2015-12-16 patchlevel 648) [universal.x86_64-darwin15]
  - INSTALLATION DIRECTORY: /Library/Ruby/Gems/2.0.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/bin
  - SPEC CACHE DIRECTORY: /Users/devUser/.gem/specs
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-darwin-15
  - GEM PATHS:
     - /Library/Ruby/Gems/2.0.0
     - /Users/devUser/.gem/ruby/2.0.0
     - /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /opt/apache-ant/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /opt/X11/bin
     
HarpoMarx:~ devUser$ ls -l /Users/devUser/.gem
ls: /Users/devUser/.gem: No such file or directory

HarpoMarx:~ devUser$ ls -l /Users/devUser/.gem/specs
ls: /Users/devUser/.gem/specs: No such file or directory

HarpoMarx:~ devUser$ 

HarpoMarx:~ devUser$ gem uninstall cocoapods
/* Note there is no response or prompt to uninstall */

HarpoMarx:~ devUser$ sudo gem uninstall cocoapods
/* Note there is no response or prompt to uninstall */

HarpoMarx:~ devUser$ pod --version
1.0.0.beta.5

HarpoMarx:~ devUser$

================================================

Any insight would be appreciated as I can not seem to get it to recognize the latest version even after installing an update. It is locked on 1.0.0.beta.5 regardless of what I have installed.

Thanks!

**Comment by rushk2112** [comment]
I have also tried

HarpoMarx:~ devUser$ gem uninstall cocoa pods
and
HarpoMarx:~ devUser$ gem uninstall cocoa pods --pre

HarpoMarx:~ devUser$ gem uninstall cocoapods

Select gem to uninstall:
 1. cocoapods-0.39.0
 2. cocoapods-1.0.0.beta.8
 3. All versions
> ^CERROR:  Interrupted

HarpoMarx:~ devUser$ pod --version
1.0.0.beta.5
