### ISSUE TITLE
Pods are not installed in the Frameworks folder when they belong to a dependency target and not the the main one

### ISSUE THREAD

**Issue by andreacremaschi** [CocoaPods/CocoaPods#4772]
Hi, 

let's say we have a target with a framework target as a dependency, named "dependency":

```
App
   - dependency (Framework)
```

The Framework imports a pod that is not in the main target app, like this:

```ruby
use_frameworks!
target 'dependency' do
     pod 'Alamofire'
end
```

As a result, when archiving the project, the `Alamofire` framework is not copied in the folder structure as it should:

```
.
├── Base.lproj
│   ├── LaunchScreen.storyboardc
│   │   ├── 01J-lp-oVM-view-Ze5-6b-2t3.nib
│   │   ├── Info.plist
│   │   └── UIViewController-01J-lp-oVM.nib
│   └── Main.storyboardc
│       ├── BYZ-38-t0r-view-8bC-Xf-vdC.nib
│       ├── Info.plist
│       └── UIViewController-BYZ-38-t0r.nib
├── Frameworks
│   ├── dependency.framework
│   │   ├── Frameworks
│   │   ├── Info.plist
│   │   └── dependency
│   ├── libswiftContacts.dylib
│   ├── libswiftCore.dylib
│   ├── libswiftCoreGraphics.dylib
│   ├── libswiftCoreImage.dylib
│   ├── libswiftDarwin.dylib
│   ├── libswiftDispatch.dylib
│   ├── libswiftFoundation.dylib
│   ├── libswiftObjectiveC.dylib
│   └── libswiftUIKit.dylib
├── Info.plist
├── PkgInfo
└── alamofire-inaframework
```

As a workaround, one can install the missing dependency in the main target, but the behaviour is really confusing and it should definitely be fixed.

I've set up a sample project to demonstrate the issue: https://github.com/andreacremaschi/cocoapods-dependencypodsnotinstalled.git

Cheers!

**Comment by orta** [comment]
Have you tried this with the 1.0.0 beta?

**Comment by neonichu** [comment]
I don't think anything has changed there. Our longstanding recommendation has been to make your own frameworks Pods themselves, since there is no way for us to embed the dependencies inside your framework.

I actually wonder if we should warn/error when a pod target is a dynamic framework with dependencies, since there is no case where that actually does something useful, right?

**Comment by orta** [comment]
> I actually wonder if we should warn/error when a pod target is a dynamic framework with dependencies, since there is no case where that actually does something useful, right?

To my knowledge we don't no, I thought we did give an error - so I'm on board with that.

**Comment by segiddins** [comment]
Actually, making it work is exactly the same work needed to fix extensions, now that I think about it.

**Comment by neonichu** [comment]
@segiddins that's true, but it might set up wrong expectations for people, e.g. thinking that the dependencies will somehow be embedded inside the framework they're building.

**Comment by yonaskolb** [comment]
A workaround I've been using is to add another line to the "Embed Pods Frameworks" script in the main target. In the example from @andreacremaschi, that script would usually be:
`"${SRCROOT}/Pods/Target Support Files/Pods-App/Pods-App-frameworks.sh"`
I've been adding the line:
`"${SRCROOT}/Pods/Target Support Files/Pods-dependency/Pods-dependency-frameworks.sh"`

Is there a better way? Or something I can add to the podfile that will automate this? Because in the current cocoapods version this is being reset after each pod install

**Comment by segiddins** [comment]
@yonaskolb make the change in a post install hook in your podfile.

**Comment by yonaskolb** [comment]
What would that look like?

**Comment by andreacremaschi** [comment]
Just to enforce the approach suggested by @neonichu: iTunes Connect will refuse an embedded framework containing a folder named "Frameworks" with the ERROR ITMS-90206. Now it makes perfectly sense to me why CocoaPods does not support secondary targets.
