### ISSUE TITLE
use-frameworks! prevents Xcode from linking libraries

### ISSUE THREAD

**Issue by ExoticObjects** [CocoaPods/CocoaPods#4792]
I doubt this is a bug, but I'm pretty sure it's an area where general users of CocoaPods suffer from a real lack of clarity! 

Since I've begun to (try) to `use_frameworks!` my local development pods can't access code that is included at the top level of my project. This used to work, and still works if I comment out `use_frameworks` in my dead-simple Podfile below:

```ruby
platform :ios, '9.0'
use_frameworks! #comment this out and all is well

target :test_use_frameworks do
  pod 'STHTTPRequest', '1.0.0' #test a well known library
  pod 'test_pod', :path => '../test_pod/' #Attempt to use that library from within local pod
end
```

If you want to try this yourself, I've made a simple **objective-c only** test project that is accessible [here](https://github.com/ExoticObjects/test_cocoapods_use_frameworks).

When I try to use STHTTPRequest from within my local test_pod, like so:

`STHTTPRequest * r = [STHTTPRequest requestWithURLString:@"http://www.google.com"];`

I get the following error:

```ruby
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_STHTTPRequest", referenced from:
      objc-class-ref in TestClass.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

(This happens no matter what class I try to use - the issue has nothing to do with `STHTTPRequest`...)

The local podspec is also as simple as it can be:

```ruby

Pod::Spec.new do |s|
  s.name             = "test_pod"
  s.version          = "0.1.0"
  s.summary          = "A short description of test_pod."
  s.description      = "use_frameworks! is causing problems for me"
  s.homepage         = "https://github.com/<GITHUB_USERNAME>/test_pod"
  s.license          = 'MIT'
  s.source           = { :git => "https://github.com/<GITHUB_USERNAME>/test_pod.git", :tag => s.version.to_s }
  s.platform     = :ios, '7.0'
  s.requires_arc = true
  s.source_files = 'Pod/Classes/**/*'
  s.resource_bundles = {
    'test_pod' => ['Pod/Assets/*.png']
  }
  s.dependency 'AFNetworking', '~> 2.3'
end
```

Here are the SO questions I've found on this topic: ([1](http://stackoverflow.com/questions/31103831/xcode-cant-see-objects-added-via-cocoapods), [2](http://stackoverflow.com/questions/32530058/cocoapods-use-frameworks-causes-linker-errors), [3](http://stackoverflow.com/questions/12002905/ios-build-fails-with-cocoapods-cannot-find-header-files)), but none of them help. I've tried every variation of *header search path, user header search path* and *framework search path* that I can think of. 

Again, this project **HAS NO SWIFT** in it. It will soon, if I can get this to work, but not yet...

I'm using cocoapods 0.39.0

I'm guessing this is due to a change in how things work, but with cocoapods, these are only ever inferred from long discussions on pages like this - there is never a definitive announcement or set of instructions. In fairness, the problems are typically so complex that I'm not sure there could be. That said, the test project is incredibly simple and is attempting to run a single line of code that used to work. It would be great if cocoapods could somehow be more helpful in a situation like this...

What am I missing?

**Comment by segiddins** [comment]
Your podspec needs to depend upon `STHTTPRequest` if it wants to reference symbols from that pod

**Comment by ExoticObjects** [comment]
Why did this change when `use_frameworks` became a thing?

**Comment by segiddins** [comment]
Its because frameworks are dynamically linked -- the compiler / linker needs to have access to those symbols, which simply isn't necessary for static libraries.

**Comment by orta** [comment]
It was probably grabbing the symbols from the application's global scope and working as an implementation detail, symbols in frameworks however are separated into their own chunks via frameworks and dynamically linked in. That's part of their selling point from Apple's perspective.

**Comment by ExoticObjects** [comment]
The original issue came up for me when trying to use [AttributedMarkdown](https://github.com/dreamwieber/AttributedMarkdown) inside my local pod. AttributedMarkdown is only available like this:

`pod 'AttributedMarkdown', :git => 'https://github.com/dreamwieber/AttributedMarkdown.git'`

```ruby
pod search AttributedMarkdown
[!] Unable to find a pod with name matching `AttributedMarkdown'
```

It can't be a dependency inside a pod, so my pod can't depend upon AttributedMarkdown (until they fix the issue, if ever). 

Is there any workaround you can imagine, using, say, a post_install hook?

**Comment by segiddins** [comment]
Nope, you'll have to get them to publish their pod, or you can publish it in a private specs repo.

**Comment by ExoticObjects** [comment]
Private specs repo! Good idea. Thanks!

**Comment by apbendi** [comment]
Posting this here as it might help somebody else out. I eventually got to this issue after much Googling. I'm working on a new Pod that has several (public) pods as dependencies in the podspec. I had `use_frameworks!` in the Example apps Podfile. `pod install` worked with no problem and pulled in the dependencies.

When I imported and referenced a class from one of the dependency pods inside my development pod, I began getting the `Undefined symbols for architecture x86_64:` error described in the original post. As you can see, my situation is the reverse of the OP. My dependencies were in the podspec, not the example app Podfile, but I was still seeing this error.

I commented out `use_frameworks!` in the Podfile and ran `pod install` to see if this would remove the errors. Indeed, the project did build, but since I need to make this Pod available to Swift users, I still needed to figure out how to get it to link with `use_frameworks!` enabled. So I uncommented the `use_frameworks!` line and ran `pod install` again, fully expecting the error to return, but lo and behold...it is building.

Why you ask? 

¯\_(ツ)_/¯

Some kind of problematic state or configuration seemed to be blown away by this process. I don't know what or why, and I'm hoping this won't cause issues for the pod consumers down the line. Anyway, hoping this helps someone out!
