### ISSUE TITLE
No longer propagating deployment target of importing target to pods

### ISSUE THREAD

**Issue by ChristopherRogers** [CocoaPods/CocoaPods#4859]
🌈

(Previously discussed somewhat in issue #4636.)

I believe that this is an intentional change, but I think there are valid use cases for wanting to use the deployment target of the app/target, which is sometimes higher. My use case is conditionally compiling code depending on the deployment target. You can remove unnecessary code, dependencies, or workarounds this way. Perhaps there should be an option in the Podfile and/or Podspec to opt-in to this behavior.

(By the way, there's no way to specify in a Podspec that a dependency should only be included if the deployment target is below a given version, right? For example, JSONKit if < iOS 5.)

**Comment by segiddins** [comment]
This is intentional. If you want to change it, you'll need a post-install hook.

**Comment by ChristopherRogers** [comment]
OK, thanks.

**Comment by artemisia-absynthium** [comment]
@segiddins excuse me, I'd like to know, why this choice? What are the downsides of the previous approach? Do I risk any side effect by adding a post-install hook that does this?

**Comment by LinusU** [comment]
@segiddins I would also love to know why this is intentional? Is there any drawback to doing this?

I'm running into a bit of an annoying situation at the moment. I'm including an auto-generated `.rb` file in my Podspec (it's the Flutter `podhelper.rb`, I'm building a Flutter add-to-app project) and unfortunately that one is defining a `post_install` hook, so I cannot add my own.

Since I have a deployment target of iOS 12 in my main app, my app doesn't build arm 32-bit code, but since some of the pods have a much lower deployment target they do. This leaves me with linking errors when I'm trying to archive the app, and the only fix I've found is to bump the deployment target to `12` on all my pods as well.

This leaves me in a state where I have to manually update the `podhelper.rb` every time I'm doing a release (since it's an autogenerated file I lose the changes all the time), to let the post-install hook add the updated deployment target...

I think it would be very neat if CocoaPods could always propagate my `platform :ios, '12.0'` down to the individual pods deployment target. That way all pods would be optimized to run for the appropriate platform!

I'm guessing that there is a catch here though? 🤔

**Comment by LinusU** [comment]
ping @segiddins, @dnkoutso ☺️

**Comment by artemisia-absynthium** [comment]
@LinusU I found the answer to the questions I asked in my previous comment here: https://github.com/CocoaPods/CocoaPods/issues/7314#issuecomment-494188527
