### ISSUE TITLE
Question: 'Single Vector' PDF resource in a private pod

### ISSUE THREAD

**Issue by SpacyRicochet** [CocoaPods/CocoaPods#4862]
I'm trying to create a private pod with some UI functionality, which has some single vector PDF image resources. So far, I'm rather unsuccessful in getting this to work;
- When adding the PDF as a normal asset, I can't create a UIImage from it.
- When adding the PDF to an .xcassets, I have no clue where the xcassets seem to be. I tried adding the post_install as mentioned in [here](https://github.com/CocoaPods/CocoaPods/issues/2292#issuecomment-129591236), but no luck.

Can anyone tell me what the best way currently would be to achieve this?

**Comment by peterdeweese** [comment]
I have tested this and the resources get placed into the right file location and included in the sub-pods resources such as pngs are, but as stated above, do not work.

**Comment by orta** [comment]
Perhaps the CocoaPods install scripts need to be improved to add xcassets?

**Comment by efirestone** [comment]
1) Are you using resource bundles? If so then `[UIImage imageNamed:]` isn't going to work since it only looks in the main bundle.
2) If you aren't using resource bundles, or you're using `[UIImage imageNamed:inBundle:compatibleWithTraitCollection:]`, where the bundle is the resources bundle, then does this work:

1) Use CocoaPods 1.0.0.beta.3
2) Define your resources using a recursive glob: `s.resources = 'ResourcesFolder/**/*'`
3) Create an `xcassets` catalog bundle inside of `ResourcesFolder`.
4) Manually add your PDF to the `xcassets` catalog using the Xcode UI.
5) Make sure the image is set to vector. See Step 2 in [this post](http://martiancraft.com/blog/2014/09/vector-images-xcode6/).

After doing that, I believe you should be able to access the PDF using `imageNamed:` or `imageNamed:inBundle:compatibleWithTraitCollection:`. If not, can you provide a sample project (ideal), or a screen shot of what your resources look like in Finder and in the Xcode Navigator?

**Comment by peterdeweese** [comment]
Thanks, @efirestone. I have tried a number of those steps but not the latest beta. Of note is that for images referenced in storyboards, it works perfectly fine with a png and not at all with a pdf vector inside or outside of xcassets, with everything else being equal. I assume the same is true for imageNamed but haven't tested it.

**Comment by efirestone** [comment]
Might be a silly question, but have you tried this in a project that's not using Pods? I don't have a lot of personal experience with using vector PDFs for assets, but I suspect they're a lot more finicky than traditional images. Is it possible this is just an issue with your PDF and UIImage independently of Pods?

**Comment by mpretty-homepass** [comment]
@efirestone Just my 2c, XCode actually takes PDF files and outputs @1x, @2x & @3x png images during compilation. @SpacyRicochet That's probably why you can't load the PDF when adding it as a normal asset (iOS actually can't render it as a UIImage).

I'm also running in to problems trying to load assets from a bundle which includes PDF files in the asset catalogue (They were working prior to turning my project in to a pod).

**Comment by mpretty-homepass** [comment]
@efirestone, @SpacyRicochet Just tried CocoaPods 1.0.0.beta.3 and it looks like it's building and copying the bundle including the Asset Catalogue with the path **'Resources/\*\*/*'**.

**Comment by efirestone** [comment]
Excellent! That makes sense. Here's what I believe was happening/is happening:
- In the long long ago, CocoaPods had a naive resources copy phase that took everything in the resources folder and copied it into the built app bundle
- Blind copying didn't work because some resources (CoreData models, XIBs, images, etc) needed special handling, such as compilation or optimization. To fix this the copy-resources.sh build phase was added to do the right thing for specific resources, basically mimicking what Xcode does normally. This didn't include PDFs because PDFs weren't supported at the time, and that support was never added.
- With the changes for https://github.com/CocoaPods/CocoaPods/pull/4635, CocoaPods now has semantic understanding of these special resources at the time that it constructs the Xcode project. This means that things like `xcassets` bundles are added as the correct element in the Xcode project, and its child elements aren't copied into the project directly (even though you said `**/*`, it knows not to traverse that bundle folder). The result is that Xcode now knows directly about each resource, rather than the top level file system reference that it's supposed to copy, and because it knows about the resource, and it's type, it will handle processing/compiling it directly, which for your case means processing the xcasset catalog with full PDF support.
