### ISSUE TITLE
Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0.beta.1`

### ISSUE THREAD

**Issue by UglyTroLL** [CocoaPods/CocoaPods#4869]
```
$ pod spec lint

[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0.beta.1`
[!] The spec did not pass validation, due to 1 error.
```

This happened when I tried to lint the spec and publish a new version of my library, not sure why. I'm using 0.39.0 which is the latest version I believe

**Comment by segiddins** [comment]
What's the output of `pod spec lint --verbose`? (The warning is fixed in 1.0 beta and shouldn't have any actual effect)

**Comment by UglyTroLL** [comment]
nvm, I tried this morning and it's working fine now...not sure why did it fail in the first place

**Comment by userException** [comment]
I am having the same error. Here is the verbose out put

spec lint --verbose

    RDAppPermissions (1.0.1) - Analyzing on OS X platform.
  Preparing
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0`

Analyzing dependencies

Fetching external sources
-> Fetching podspec for `RDAppPermissions` from `/Volumes/Workspace HD/My Workspace/Live Data/Live Apps/AppPermissions/RDAppPermissions.podspec`

Resolving dependencies of 

Comparing resolved specification to the sandbox manifest
  A RDAppPermissions

Downloading dependencies

-> Installing RDAppPermissions (1.0.1)
 > Git download
 > Git download
     $ /usr/local/bin/git clone https://github.com/userException/AppPermissions.git
     /var/folders/y9/lt52gfbx28zgl4f9djzh20rr0000gn/T/d20170324-2471-1xmyeqf --single-branch --depth 1 --branch
     v1.0.1
     Cloning into '/var/folders/y9/lt52gfbx28zgl4f9djzh20rr0000gn/T/d20170324-2471-1xmyeqf'...
     warning: Could not find remote branch v1.0.1 to clone.
     fatal: Remote branch v1.0.1 not found in upstream origin

[!] Error installing RDAppPermissions
 -> RDAppPermissions (1.0.1)
    - ERROR | File Patterns: The RDAppPermissions (1.0.1) spec is empty (no source files, resources, resource_bundles, preserve paths, vendored_libraries, vendored_frameworks, dependencies, nor subspecs).
    - ERROR | [OSX] unknown: Encountered an unknown error ([!] /usr/local/bin/git clone https://github.com/userException/AppPermissions.git /var/folders/y9/lt52gfbx28zgl4f9djzh20rr0000gn/T/d20170324-2471-1xmyeqf --single-branch --depth 1 --branch v1.0.1

Cloning into '/var/folders/y9/lt52gfbx28zgl4f9djzh20rr0000gn/T/d20170324-2471-1xmyeqf'...
warning: Could not find remote branch v1.0.1 to clone.
fatal: Remote branch v1.0.1 not found in upstream origin
) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 2 errors.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/spec/lint.rb:77:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by benasher44** [comment]
Hi there! Thanks for the report! Could you try uninstalling your CocoaPods, verifying that `pod` is no longer a valid command on your system, and then reinstalling? Thanks!
