### ISSUE TITLE
Unable to load xcassets from bundle when using frameworks.

### ISSUE THREAD

**Issue by asharma-atx** [CocoaPods/CocoaPods#4897]
This issue is a follow up to issue [#4851](https://github.com/CocoaPods/CocoaPods/issues/4851), as requested by @segiddins and @efirestone.

My CocoaPod [(ASMessenger, pre-release)](https://github.com/asharma-atx/ASMessenger) is unable to load xcassets from it's bundle when the Podfile specifies that it should `use_frameworks!`. It is able to load the image assets if it is being used as a static library.

I'm able to log out the bundle (see below) but it seems that there are no images in the bundle (viewing the bundle contents in Finder does not reveal any xcassets). For that reason, I suspect that the image assets are simply not being copied into the bundle.

`NSLog(@"Bundle %@", bundle);` logs out this:
```
bundleTest[5637:1947336] Bundle: NSBundle </var/containers/Bundle/Application/20071A5C-738C-429B-81DC-6CE9B0C1B882/bundleTest.app/Frameworks/ASMessenger.framework/ASMessenger.bundle> (not yet loaded)
```

You can grab a copy of the source [here](https://github.com/asharma-atx/ASMessenger). The image is being used in the class ASAttachmentCell on line 67. 

**Important Note:** You'll need to add the `use_frameworks!` flag to the Podfile to reproduce the issue. If you accidentally install the app before you do this, please be sure to clear out the old bundle before your add `use_frameworks!` and redo the pod install, or you may still be working with the static library bundle (which works fine).  

Here is the setup:

Podspec:
`s.resource_bundles = { 'ASMessenger' => ['Pod/Assets/**/*'] }`

Resources path in project directory:
`ASMessenger > Pod > Assets`

How I'm accessing the bundle:
```
+ (instancetype)ASMessengerBundle{
    
    // TODO: Resolve issue preventing assets from being bundled if CocoaPod is being used as a framework.
    
    static NSBundle *bundle = nil;
    
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        
        NSBundle *containingBundle = [NSBundle bundleForClass:[ASEntry class]];
        NSURL *bundleURL = [containingBundle URLForResource:@"ASMessenger" withExtension:@"bundle"];
        
        if (bundleURL) bundle = [NSBundle bundleWithURL:bundleURL];
    });
    
    return bundle;
}
```

How I'm _trying_ the accessing the image:

`[UIImage imageNamed:@"detail_arrow.png" inBundle:[NSBundle ASMessengerBundle] compatibleWithTraitCollection:nil];`

Details:
- CocoaPods 1.0.beta.3

**Comment by efirestone** [comment]
Dug into this more and have a strong lead. The reason this fails is two-fold:
- `+[UIImage imageNamed:inBundle:compatibleWithTraitCollection:]` doesn't work if the bundle passed in doesn't contain a `CFBundleVersion` in its Info.plist
- When generating resource bundles while using `use_frameworks!`, the Info.plist for the resource bundle has an empty string value for `CFBundleVersion`.

I'm not entirely sure why this is, but [this](https://github.com/CocoaPods/CocoaPods/blob/1fd0fe8d218c6983fd982f4ef7efe38ac540768e/lib/cocoapods/generator/info_plist_file.rb#L113) seems to be the offending line. I'm not sure why `CURRENT_PROJECT_VERSION` is empty in that scenario, but it should be fixable.

I've confirmed that if you manually set a value for `CFBundleVersion` then the image starts loading as expected.

@segiddins I unfortunately don't know the Info.plist generation code at all and don't have time to dig into it. Would you mind driving a fix?

**Comment by segiddins** [comment]
This should be an easy fix, we just need to make sure the current project version is also set for resource bundles

**Comment by da-na** [comment]
Hi folks!
I have a similar issue, and the CURRENT_PROJECT_VERSION in my private pod is set. According to the guideline I should discuss my issue here, so here's the info of my project.

Please let me know if I'm missing something obvious here. I find it astounding, that I can access the image from my private Pod through the storyboard, but then later on it doesn't show in the app. 

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I've created a private Pod, to hold MyAppUI components, like image assets, custom buttons etc. Then in Example for MyAppUI I created a storyboard with a button and icon as an example.

## What did you expect to happen?

I expected the image in a button to be loaded after running my app - since I had no problem adding it in a storyboard.

## What happened instead?

This is what I have in storyboard:
![screen shot 2017-01-16 at 12 01 20 pm](https://cloud.githubusercontent.com/assets/9628216/21992215/96d9f9a2-dbe3-11e6-9a86-609ebdfa3f7b.png)

And then after running the app I can see the button, but without the image. The image is not displayed, and I can see an error in the console:

2017-01-16 11:39:50.903 MyAppUI_Example[2887:73017] Could not load the "ic_account_circle_18pt_3x.png" image referenced from a nib in the bundle with identifier "com.mycompany.demo.MyAppUI-Example"

This bundle identifier is wrong (I think...) Image is bundled in org.cocoapods.MyAppUI

I have this code in MyAppUI.podspec
```
Pod::Spec.new do |s|
  s.name             = 'MyAppUI'
  s.version          = '0.1.0'
  s.summary          = 'CocoaPod for MyAppUI elements.'

 (...)

  s.ios.deployment_target = '10.2'
  s.source_files = 'MyAppUI/Classes/**/*.{swift}'
  s.resource_bundles = {
   'MyAppUI' => ['MyAppUI/Assets/**/*.{imageset}']
  }

```
## CocoaPods Environment

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-darwin15]
    RubyGems : 2.6.8
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.6.2
Ruby lib dir : /Applications/CocoaPods.app/Contents/Resources/bundle/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d4b534ca6a3d1982e269cae9e7c0fa6fc1a1529d
```

### Installation Source

```
Executable Path: /Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod
```

### Plugins

```
cocoapods-check           : 1.0.0
cocoapods-deintegrate     : 1.0.1
cocoapods-plugins         : 1.0.0
cocoapods-plugins-install : 0.0.1
cocoapods-search          : 1.0.0
cocoapods-stats           : 1.0.0
cocoapods-trunk           : 1.1.2
cocoapods-try             : 1.1.0
```

### Podfile

```ruby
use_frameworks!

target 'MyAppUI_Example' do
  pod 'MyAppUI', :path => '../'

  target MyAppUI_Tests' do
    inherit! :search_paths
    
  end
end
```

**Comment by benasher44** [comment]
@da-na thanks for the detailed report! Mind opening up a new issue? This one has been closed for some time. Thanks!

**Comment by gizmoboy7** [comment]
I'm facing the same problem as @asharma-atx 
podspec -  `s.resource_bundle = {"Resources" => ["native/MyProject/MyProject/*.xib","native/MyProject/MyProject/*.lproj"]}`

Error  - `/Library/Developer/CoreSimulator/Devices/6FAB3140-D5CB-4262-ADAD-8DBA7D154A53/data/Containers/Bundle/Application/84B3BA53-64C4-48A1-9DB2-DEEC3DBEB10A/podsNewCrash.app/BugSquashResources.bundle> (not yet loaded)'`

When i try to explicitly load the bundle using `[bundle load]`  i get the error  -
```
 Cannot find executable for CFBundle 0x7fe133503f70 </Users/Giridhar/Library/Developer/CoreSimulator/Devices/6FAB3140-D5CB-4262-ADAD-8DBA7D154A53/data/Containers/Bundle/Application/C10D774E-C32D-4877-92A5-4E523E9CC139/podsNewCrash.app/Resources.bundle> (not loaded)
```
I checked the bundle, it has all the resources i specified in the podspec in it. 
Am i missing out something obvious? 
I'm running Cocoapods version `1.2.1`
