### ISSUE TITLE
No colored output for pod search in 1.0.0.beta.4

### ISSUE THREAD

**Issue by 0xced** [CocoaPods/CocoaPods#4993]
# Report

## What did you do?

Run `pod search`

## What did you expected to happen?

Colored output, like in version 0.39.

## What happened instead?

Output with visible escape codes gibberish such as `ESC[33m` instead of colored output, cf screenshot.
<img width="1270" alt="output of pod search for v0.39 and v1.0.0.beta.4" src="https://cloud.githubusercontent.com/assets/51363/13575554/c87e3394-e489-11e5-8979-dccbe3630d6d.png">

**Comment by segiddins** [comment]
What happens if you run with `--no-pager` ?

**Comment by 0xced** [comment]
Running with `--no-pager` produces the expected colored output.

**Comment by manuyavuz** [comment]
Hi @0xced,

could you share the output of the following in your terminal:
```
echo $PAGER
```

**Comment by 0xced** [comment]
```
$ echo $PAGER
more
```

```
$ which more
/usr/bin/more
```

```
$ /usr/bin/more --version
less 458 (POSIX regular expressions)
Copyright (C) 1984-2012 Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less
```

**Comment by manuyavuz** [comment]
Thanks,

After v1.0, `pod search` outputs found pods in a pager by default, to provide a `git log` like experience. And it uses the default `$PAGER` choice it this is set, otherwise it uses `less -R`.

`less` & `more` commands need to include `-R` option in order to correctly parse and visualize colors. Because your $PAGER is just `more`, not `more -R`, output is not pretty printed.

You can change your $PAGER value to `more -R` in order to get a colored output while using `more` command.

**Comment by 0xced** [comment]
Excellent, thank you for the explanation.
