### ISSUE TITLE
ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/bin/git clone 

### ISSUE THREAD

**Issue by ankitthakur** [CocoaPods/CocoaPods#5008]
ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/bin/git clone 

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`$ pod trunk push GMEllipticCurveCrypto.podspec --verbose`

```
Updating spec repo `master`
  $ /usr/bin/git pull --ff-only
  Already up-to-date.

CocoaPods 1.0.0.beta.5 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Validating podspec
    GMEllipticCurveCrypto (1.2) - Analyzing on iOS 8.0 platform.
  Preparing

Analyzing dependencies

Fetching external sources
-> Fetching podspec for `GMEllipticCurveCrypto` from `/Users/ankitthakur/Documents/Github/GMEllipticCurveCrypto/GMEllipticCurveCrypto.podspec`

Resolving dependencies of

Comparing resolved specification to the sandbox manifest
  A GMEllipticCurveCrypto

Downloading dependencies

-> Installing GMEllipticCurveCrypto (1.2)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/ankitthakur/GMEllipticCurveCrypto.git
     /var/folders/pr/fmr7nlts5k7665wc4wp51g04v1tl0y/T/d20160309-40656-6vh407 --single-branch --depth 1 --branch 1.2
     Cloning into '/var/folders/pr/fmr7nlts5k7665wc4wp51g04v1tl0y/T/d20160309-40656-6vh407'...
     warning: Could not find remote branch 1.2 to clone.
     fatal: Remote branch 1.2 not found in upstream origin

[!] Error installing GMEllipticCurveCrypto
 -> GMEllipticCurveCrypto (1.2)
    - ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/bin/git clone https://github.com/ankitthakur/GMEllipticCurveCrypto.git /var/folders/pr/fmr7nlts5k7665wc4wp51g04v1tl0y/T/d20160309-40656-6vh407 --single-branch --depth 1 --branch 1.2

Cloning into '/var/folders/pr/fmr7nlts5k7665wc4wp51g04v1tl0y/T/d20160309-40656-6vh407'...
warning: Could not find remote branch 1.2 to clone.
fatal: Remote branch 1.2 not found in upstream origin
) during validation.

[!] The podspec does not validate.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.6.4/lib/pod/command/trunk/push.rb:114:in `validate_podspec'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.6.4/lib/pod/command/trunk/push.rb:59:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

## What did you expected to happen?

> 1.2 tag is already deployed on https://github.com/ankitthakur/GMEllipticCurveCrypto/releases/tag/v1.2. So it should be pushed properly on CocoaPods.

## What happened instead?

> [!] Error installing GMEllipticCurveCrypto
>  -> GMEllipticCurveCrypto (1.2)
>     - ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/bin/git clone https://github.com/ankitthakur/GMEllipticCurveCrypto.git /var/folders/pr/fmr7nlts5k7665wc4wp51g04v1tl0y/T/d20160309-40656-6vh407 --single-branch --depth 1 --branch 1.2

**Comment by k0nserv** [comment]
The tag does exist, but CocoaPods is looking for the branch 1.2 not the tag. Could you post your `.podspec`?

**Comment by ankitthakur** [comment]
Pod::Spec.new do |s|
  s.name             = "GMEllipticCurveCrypto"
  s.summary          = "An Objective-C library for Elliptic Curve Digital Signing Algorithm (ECDSA) and for Elliptic Curve Diffie-Hellman (ECDH)."
  s.version          = "1.2"
  s.homepage         = "https://github.com/ankitthakur/GMEllipticCurveCrypto"
  s.license          = 'BSD 2-Clause License'
  s.author           = { "Ankit Thakur" => "ankitthakur85@icloud.com" }
  s.source           = {
    :git => "https://github.com/ankitthakur/GMEllipticCurveCrypto.git",
    :tag => s.version.to_s
  }
  s.social_media_url = 'https://twitter.com/ankitthakur'

  s.ios.deployment_target = '8.0'

  s.requires_arc = true
  s.ios.source_files = 'Pod/Classes/**/*'

  s.ios.frameworks = 'UIKit', 'Foundation'
  # s.osx.frameworks = 'Cocoa', 'Foundation'

  # s.dependency 'Whisper', '~> 1.0'
end

**Comment by segiddins** [comment]
Shouldn't the tag be `"v#{s.version}"` in the podspec?

**Comment by ankitthakur** [comment]
@k0nserv, @segiddins Thanks. Nice catch.

**Comment by ankitthakur** [comment]
issue is fixed, so closing it.

**Comment by iadwait** [comment]
> issue is fixed, so closing it.

Please let me know what is the issue i got error
Validating podspec
 -> ABDoneKeyboard (0.1.0)
    - WARN  | url: The URL (https://github.com/adwaitbarkale@gmail.com/ABDoneKeyboard) is not reachable.
    - ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/bin/git clone https://github.com/adwaitbarkale@gmail.com/ABDoneKeyboard.git /var/folders/9r/mpt8wpms6f725gf0mtwdckyh0000gq/T/d20200820-3212-jci92o --template= --single-branch --depth 1 --branch 0.1.0

Cloning into '/var/folders/9r/mpt8wpms6f725gf0mtwdckyh0000gq/T/d20200820-3212-jci92o'...
fatal: unable to access 'https://github.com/adwaitbarkale@gmail.com/ABDoneKeyboard.git/': The requested URL returned error: 400
) during validation.

[!] The spec did not pass validation, due to 1 error and 1 warning.


podspec file
#
# Be sure to run `pod lib lint ABDoneKeyboard.podspec' to ensure this is a
# valid spec before submitting.
#
# Any lines starting with a # are optional, but their use is encouraged
# To learn more about a Podspec see https://guides.cocoapods.org/syntax/podspec.html
#

Pod::Spec.new do |s|
  s.name             = 'ABDoneKeyboard'
  s.version          = '0.1.0'
  s.summary          = 'This Project will add Done Button on Keyboard'

# This description is used to generate tags and improve search results.
#   * Think: What does it do? Why did you write it? What is the focus?
#   * Try to keep it short, snappy and to the point.
#   * Write the description between the DESC delimiters below.
#   * Finally, don't worry about the indent, CocoaPods strips it!

  s.description      = <<-DESC
'This Project will add Done Button on Keyboard.Just import and set accessory to on.'
                       DESC

  s.homepage         = 'https://github.com/adwaitbarkale@gmail.com/ABDoneKeyboard'
  # s.screenshots     = 'www.example.com/screenshots_1', 'www.example.com/screenshots_2'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'iadwait' => 'adwaitbarkale@gmail.com' }
  s.source           = { :git => 'https://github.com/adwaitbarkale@gmail.com/ABDoneKeyboard.git', :tag => s.version.to_s }
  # s.social_media_url = 'https://twitter.com/<TWITTER_USERNAME>'

  s.ios.deployment_target = '13.0'

  s.source_files = 'Classes/**/*.swift'
  
  s.swift_version = '5.0'
  
  s.platforms = {
      "ios": "13.0"
  }
  
  # s.resource_bundles = {
  #   'ABDoneKeyboard' => ['ABDoneKeyboard/Assets/*.png']
  # }

  # s.public_header_files = 'Pod/Classes/**/*.h'
  # s.frameworks = 'UIKit', 'MapKit'
  # s.dependency 'AFNetworking', '~> 2.3'
end

**Comment by iadwait** [comment]
mail me at adwaitbarkale@gmail.com
