### ISSUE TITLE
Localized dependencies don't get localized in a swift project

### ISSUE THREAD

**Issue by maxminipedia** [CocoaPods/CocoaPods#5203]
# Report

## What did you do?
Added Armchair as a dependency, which worked fine, no problem there.
My app's project is localized for ~15 languages. The app itself gets localized just fine

## What did you expected to happen?

So I would expect the dependency also to be localized, 

## What happened instead?

The Armchair alert is always in English. I am not 100% sure if it even uses it's english .strings file or just the key

So I double checked this, and used objc Appirater instead, but it does not localize either.
This seems to be some swift - pod - framework issue?

## Podfile

```ruby
target 'xyz' do
platform :ios, "8.0"
use_frameworks!

pod 'ObjectMapper', '~> 1.2'
pod 'KeychainAccess'
pod 'Alamofire', '~> 3.3'
pod 'MBProgressHUD', '~> 0.9.2'

pod 'Armchair', '~> 0.1.1'

end
```
Thanks for your help
Max

**Comment by segiddins** [comment]
What CocoaPods version are you using ? I think we made some improvements around this in the 1.0 betas

**Comment by maxminipedia** [comment]
pod --version
0.39.0

**Comment by maxminipedia** [comment]
So I tried this with 1.0.0.beta.8 now, but it's still the same problem.
Any more ideas?

**Comment by maxminipedia** [comment]
So I found a workaroud for now, this should be useful for any dependency with localization.
I added this runscript to the build phases

`TARGET="${TARGET_BUILD_DIR}/${PRODUCT_NAME}.app"
ARMCHAIR="${TARGET}/Frameworks/Armchair.framework"

for path in $TARGET/*.lproj; do
    xbase=${path##*/}
    language=${xbase%.*}
    cp "${ARMCHAIR}/$language.lproj/ArmchairLocalizable.strings" "${TARGET}/$language.lproj/"
done`

This moves the localized strings file to the apps *.lproj dir, so Armchair can find it.
Same for Appirater, which creates a Appirater.Bundle. If this bundle file is moved to the apps base direcory localization works fine.

Hope this is helpful for others ;)

**Comment by segiddins** [comment]
@efirestone didn't your changes attempt to fix this?

**Comment by efirestone** [comment]
This is a misconfiguration of [Armchair's podspec](https://github.com/UrbanApps/Armchair/blob/master/Armchair.podspec). They're using `resources` rather than `resource_bundle`, and when you compile with Swift it creates a `.framework` rather than a `.a`, which moves where the resources are located. For a `.a`, the target for the resources copy is the app itself, so you can look things like localizations up using `[NSBundle mainBundle]`. For a `.framework` the target for the resources copy is the framework itself, so you would need to look up resources/localizations using the framework bundle (something like `[NSBundle bundleForClass:[SomeClassInTheFramework class]]`).

The fix here is for Armchair to use `s.resource_bundle` in its podspec, and in all its calls to `NSLocalizedString[WithDefaultValue]`, specify the resources bundle that ships with its library/framework. Note that this will be different than the examples above -- you'll want to look up the resources bundle from within the framework. [Sample code here](https://github.com/CocoaPods/CocoaPods/issues/4851#issuecomment-184323213). This will work consistently for both static libraries and dynamic frameworks (like Swift uses).

**Comment by willpowell8** [comment]
I had the same issue. Does this help: https://github.com/willpowell8/LocalizationKit_iOS you can include it in your modules.
