### ISSUE TITLE
Issue with pod spec lint for library that has dependencies

### ISSUE THREAD

**Issue by astruts** [CocoaPods/CocoaPods#5213]
Hello, I am using Cocoapods 1.0.0 beta-8 and trying to lint a static library that has a dependency on another library, during lint I get the next error:

error: include of non-modular header inside framework module	‘name of the library’

I’ve created a simple project with pod create and have the same issue over there.
https://github.com/astruts/LRLib 
The project is a pure Objective-C project and the dependency is also a pure Objective C library (no Swift is used).
Please take a look on source files of this project.

**Comment by lrozenblyum** [comment]
It's rather an annoying issue.
Does anyone know a workaround?

Even when I try to create a pod that depends on a simple library JKBigInteger it also doesn't pass the validation with the same message 'error: include of non-modular header inside framework module ‘name of the library’.

**Comment by segiddins** [comment]
If it needs to be a static library, lint with `--use-libraries`.

**Comment by lrozenblyum** [comment]
Hello! Your suggestion about `--use-libraries` was really great ! It solved the issue of linting.

I have a few questions.
1) Can the `pod spec lint` documentation be extended to clearly state need of usage of this flag for this case? 
2) Will it be possible to push our library to trunk if it doesn't pass `pod spec lint` but passes `pod spec lint --use-libraries'?
3) maybe what we are doing was wrong and untypical in iOS world (because of lack of experience), should we create another kind of library to pass the lint validation without additional flags?

Thank you for help & feedback!

**Comment by segiddins** [comment]
`pod trunk push` has the `--use-libraries` flag, which is documented in https://guides.cocoapods.org/terminal/commands.html#pod_trunk_push. (And no, what you're doing isn't necessarily wrong, it just happens to not work with the default of dynamic frameworks installation by the linter)
