### ISSUE TITLE
Allow to use customized build dirs

### ISSUE THREAD

**Issue by mrackwitz** [CocoaPods/CocoaPods#5217]
# Report

## What did you do?

1. Setup a project and customized the `CONFIGURATION_BUILD_DIR`.
2. Run `pod install`.
3. Try to build the project.

## What did you expected to happen?

In step 2, I would expect a warning telling me either what I need to do when I'm using a custom value for `CONFIGURATION_BUILD_DIR` or recommending me to remove the build settings from the target.

Alternatively, it would be nice if step 3 would succeed.

## What happened instead?

In step 2, I wasn't seeing a warning for conflicting overridden build settings.
In step 3 instead of successfully building my target, the build failed with a linker error, because the linker cannot find the pod targets' build products.

## Why does that happen?

The pods build products cannot be found because the user target XCConfig injects custom `LIBRARY_SEARCH_PATHS` / `FRAMEWORK_SEARCH_PATHS` which rely on a build setting, which has a different value in my project than in the `Pods.xcodeproj`. We shouldn't avoid relying on a user-customized value for the build directory. But we could allow customizing the `CONFIGURATION_BUILD_DIR` by just relying on `BUILD_DIR`. Even better would be to defining aliases in the user target XCConfig, which can then be overriden in the user target, if needed. Such overwrites should then obviously not cause warnings on installation-time.

```bash
PODS_BUILD_DIR=$(BUILD_DIR)
PODS_CONFIGURATION_BUILD_DIR="$(PODS_BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)"
```

Without a change around that, users would be required to redefine all these custom scoped search paths themselves, beginning from 1.0 with the implementation of the different scoping strategy.

**Comment by neonichu** [comment]
This seems very edge casey to me. Is there a good use case for users to customise `CONFIGURATION_BUILD_DIR`? If not, I would say just warning in that case is fine.

**Comment by tutipeti** [comment]
@mrackwitz I read through way too many issues already about `CONFIGURATION_BUILD_DIR` here but still couldn't solve mine. So I'd definitely appreciate some help.
On our Jenkins build we changed `CONFIGURATION_BUILD_DIR` to a custom directory and it was working fine before CocoaPods 1.0.0.

I understand that you added `PODS_CONFIGURATION_BUILD_DIR`, I set that on Jenkins to match `CONFIGURATION_BUILD_DIR`, but the build is still failing. Partly because of #5358, but it isn't just HockeyApp that is located elsewhere.
I see plenty of error messages saying
```
ld: warning: directory not found for option '-L/Users/jenkins/workspace/iOS_deploy_branch_to_hockey/build/CocoaLumberjack'
ld: warning: directory not found for option '-L/Users/jenkins/workspace/iOS_deploy_branch_to_hockey/build/Raven'
ld: warning: directory not found for option '-L/Users/jenkins/workspace/iOS_deploy_branch_to_hockey/build/socket.IO'
```
where `PODS_CONFIGURATION_BUILD_DIR ` = `/Users/jenkins/workspace/iOS_deploy_branch_to_hockey/build/`.
During the build all the pods are being symlinked to that directory, but *not under a subdirectory* as `ld` expects it or as #5358 describes it. They are all on the top level in that directory.

Could you tell me what am I doing wrong here?

**Comment by neonichu** [comment]
As said in #5358, you should be using `BUILD_DIR` instead, as `CONFIGURATION_BUILD_DIR` is just one build setting that is derived from that, among others.

**Comment by sibelius** [comment]
what is the proper solution for this when using fastlane?
