### ISSUE TITLE
#import path problem (+, _)

### ISSUE THREAD

**Issue by hjanuschka** [CocoaPods/CocoaPods#5284]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

i have a pod  (name it: demopod ) wich has UIAlertView+Blocks as a dependency.
in one app (i require my pod AND support for IOS7) - i don't use `use_frameworks`

it works - as in dempod - i do:

```
#import <UIAlertView+Blocks/UIAlertView+Blocks.h>
```

using `demopod` in an `use_framework!`  based project.
results in an `file not found` - required to change the import to (inside demopod):

```
#import <UIAlertView_Blocks/UIAlertView+Blocks.h>
```

but if i change it in the pod, the IOS7 project cant find the import.
with cocoapods 0.39 - it worked! problem is now with 1.0

any solution for this situation?
is there any `#ifdef` i can put arround the import?

**Comment by neonichu** [comment]
This might have accidentally worked prior to 1.0 because those headers were available in two locations. This is not an option anymore in general, because it can break building Swift projects under certain circumstances.

Generally, it is a legacy problem, a Pod's module name needs to be a C99 identifier for a while now, if the default `pod lib lint` is being used. So the right solution is changing the pod itself and consistently use `UIAlertView_Blocks`.

**Comment by hjanuschka** [comment]
god damn! - what a day!


ok so i am going to fork this pod and rename it!
