### ISSUE TITLE
Define PODS_TARGET_SRCROOT per pod target

### ISSUE THREAD

**Issue by mrackwitz** [CocoaPods/CocoaPods#5375]
Define a custom build setting `PODS_TARGET_SRCROOT`, which points to the pod target's current source root directory. For pods integrated in the usual way, this would equal to `$(PODS_ROOT)/PodName` while this would equal to whatever directory the pod was built from when it was used as development pod.

This might solve some issues with podspecs relying on files in their build settings, as they could reference them correctly in that way, independently how they are integrated.
At the same time, it allows to define podspecs to rely on files, they don’t “own”, so that they pass `pod lib lint` but fail on `pod spec lint`.

/c @segiddins @neonichu

**Comment by neonichu** [comment]
Might make sense to gather use cases for this to evaluate. 

I currently know of one, which is Swift Pods which depend on system libraries which aren't exposed as a clang module, e.g. SQLite. An example for such a Pod is <https://github.com/stephencelis/SQLite.swift/blob/master/SQLite.swift.podspec>, it uses `SWIFT_INCLUDE_PATHS` which break when integrating it as a development Pod.

Any other use cases we know of?

**Comment by mrackwitz** [comment]
CommonCryptoSwift does the same.
Beside that we need it at [Realm](https://github.com/realm/realm-cocoa/blob/master/Realm.podspec#L61-62).

**Comment by neonichu** [comment]
Judging from existing specs, there's loads which use `PODS_ROOT` for similar purposes. I think this proposal is a good way to get those specs to behave in a more future-proof manner and I don't see an issue with depending on the structure of the `$(PODS_ROOT)/PodName` directory as it is controlled by the podspec itself.

I'm thinking if we implement this, we should also start linting build settings for direct use of `PODS_ROOT` and start rejecting that. It has been publicly documented as being deprecated for a long time.

**Comment by chrisballinger** [comment]
This would be a really good feature because we have a number of podspecs that rely on the PODS_ROOT hack as well.

For example:

`  s.xcconfig = { 'HEADER_SEARCH_PATHS' => '$(PODS_ROOT)/src $(PODS_ROOT)/src/curve25519 $(PODS_ROOT)/src/curve25519/ed25519 $(PODS_ROOT)/src/protobuf-c $(PODS_ROOT)/../../src $(PODS_ROOT)/../../src/curve25519 $(PODS_ROOT)/../../src/curve25519/ed25519 $(PODS_ROOT)/../../src/protobuf-c' }`

The current solution results in twice the definitions because we want it to work when integrated as a development pod, but it's brittle because it depends on where the development podspec source is located relative to the Pods project, which may vary from project to project.

**Comment by ronak2121** [comment]
Hi, 

any update on this? I have a similar issue with libxml and common crypto as well.

Thanks

**Comment by dnkoutso** [comment]
We need this also, so I might be taking a stab at it.
