### ISSUE TITLE
Private pod no longer compiles - symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by kevinrenskers** [CocoaPods/CocoaPods#5383]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

I am working on my own (private) pod, and after upgrading to cocoapods 1.0 and running `pod install` in the Example folder, the project no longer compiles.
## What did you expected to happen?

I'd expect the example project to still compile.
## What happened instead?

I get these errors:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SlingAPIClient", referenced from:
      objc-class-ref in ConversationsViewController.o
      objc-class-ref in ShiftsViewController.o
      objc-class-ref in TasksViewController.o
      objc-class-ref in AppDelegate.o
      objc-class-ref in ChannelViewController.o
      objc-class-ref in DashboardViewController.o
      objc-class-ref in RootViewController.o
      ...
  "_OBJC_CLASS_$_SlingAttachment", referenced from:
      objc-class-ref in ConversationViewController.o
  "_OBJC_CLASS_$_SlingLeaveApplication", referenced from:
      objc-class-ref in ShiftsViewController.o
  "_OBJC_CLASS_$_SlingSession", referenced from:
      objc-class-ref in DashboardViewController.o
  "_OBJC_CLASS_$_SlingShift", referenced from:
      objc-class-ref in ShiftsViewController.o
      objc-class-ref in DashboardViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

And in fact, my iOS app using this private pod also no longer compiles due to similar errors but then in its Today Widget extension. 
### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /usr/local/Cellar/ruby/2.2.3/lib
Repositories : gangverk - git@github.com:gangverk/pods.git @ 70d963065d6db68f3acfbda08c5315799a6d76a9
               master - https://github.com/CocoaPods/Specs.git @ 18bd72051f01c60837da16b6abd27252c8035ee0
               Snagajob - git@github.com:Snagajob/CocoaPods.git @ acc0eff46f506921ca48440fa7e9479b1e71a99c
               snagajob-1 - https://github.com/Snagajob/CocoaPods.git @ acc0eff46f506921ca48440fa7e9479b1e71a99c
```
### Installation Source

```
Executable Path: /usr/local/bin/pod
```
### Plugins

```
cocoapods-acknowledgements : 1.1.1
cocoapods-deintegrate      : 1.0.0
cocoapods-plugins          : 1.0.0
cocoapods-search           : 1.0.0
cocoapods-stats            : 1.0.0
cocoapods-trunk            : 1.0.0
cocoapods-try              : 1.0.0
```
### Podfile

``` ruby
use_frameworks!

target 'SlingAPI' do
  pod "SlingAPI", :path => "../"
  pod "SlackTextViewController"
  pod "DateTools"

  target 'Tests' do
    inherit! :search_paths
  end
end
```
## Project that demonstrates the issue

I don't have an example project (*). This is a private pod, and a pod freshly created with `pod lib create Whoop` seems to work fine. I did notice that my version doesn't have the `Support Files` folder under `Development pods/SlingAPI`.

My private pod "SlingAPI":

![screen shot 2016-05-20 at 14 59 59](https://cloud.githubusercontent.com/assets/229384/15428439/a7237c76-1e9b-11e6-84d6-ccecf11ad9e0.png)

My freshly created test pod "Whoop"

<img width="262" alt="screen shot 2016-05-20 at 15 00 17" src="https://cloud.githubusercontent.com/assets/229384/15428440/aadb4498-1e9b-11e6-834e-c49d110283af.png">

(*) I can zip up my private pod and email it to someone to get help, I'd just rather not share it here out in the open :)

**Comment by kevinrenskers** [comment]
Deleting the DerivedData folder sadly didn't help.

**Comment by taylesworth** [comment]
I'm having the same problem building my unit test scheme after upgrading from CocoaPods 0.35 to 1.0. The scheme that builds the app and the scheme that builds XCUI tests all build fine. The unit test scheme gives `Undefined symbols for architecture x86_64` similar to the ones shown by the OP.

**Comment by kevinrenskers** [comment]
I've downgraded to cocoapods 0.39.0 for now

**Comment by GeroHerkenrath** [comment]
Since I've seen this error also during my experiments when migrating my development pod to 1.0, maybe the issue I just filed might help you? [Here](https://github.com/CocoaPods/CocoaPods/issues/5384)
However, you might also have to recreate your dev pod's xcode project file (the one that is generated with a fresh pod lib create)...

**Comment by kevinrenskers** [comment]
Would be great if cocoapods could update / recreate the project file, since I don't really know what changes to me. But yes, I also have a private header file so it might be related.

**Comment by taylesworth** [comment]
In my case, it was a misunderstanding of the new Podfile syntax. I thought the new `inherit! :searchpaths` was appropriate for my unit test target. But I actually needed the libraries linked with the target (unfortunately). Once I removed that for the test target, it build and ran tests fine.

**Comment by kevinrenskers** [comment]
For me it's simply running the example project on the simulator.

**Comment by keithburgoyne** [comment]
Hey @kevinrenskers, have you tried upgrading to 1.1.1? I'm also having the same issue as you, and I'm curious if you've resolved your issue.

**Comment by kevinrenskers** [comment]
I am no longer involved with the project that had this problem, so I can't test it, sorry.

**Comment by shvekiasaf** [comment]
hey @keithburgoyne, I wonder if you find some workaround to solve this issue? I'm using cocoapods 1.1.1

**Comment by fionaom** [comment]
I am using CocoaPods 1.2.0 and I still have this issue.

**Comment by starr0stealer** [comment]
Details outlined in my experience with similar build errors might help someone else who is getting them. In short adding `pod_target_xcconfig -> OTHER_LDFLAGS` let me build again.

I was having this error when I was taking a static library (Koamtac SDK) and turning it into a "private" podspec. Everything worked normally if you used a Bridging-Header file, which I didn't want as I find using CocoaPods much more enjoyable, ie less configuration. So in the process of figuring out how to fully support `use_frameworks` I started to get the error below in Xcode builds. Note the "architecture" value would be different depending on which ever build platform you targeted. I was rather puzzled with this, because using the Bridging-Header everything worked fine.  My searches led me to both this issue as well as #2926 

I honestly atm don't know what this does, but in one of the comments I saw the below config in their podspec file, and this made my builds work. I am still researching on what that flag setting is doing, and if I should be using something else or what. I don't have control of the static library, and I believe the issue is with something not exported. For example using the SocketMobile SDK the same way did not have any linking errors.

```
  s.pod_target_xcconfig = {
    'OTHER_LDFLAGS' => '$(inherited) -ObjC'
  }
```

Build error without `pod_target_xcconfig` in podspec
```
Undefined symbols for architecture armv7:
  "_kdcConnectionChangedNotification", referenced from:
      KTSwiftDemo.ViewController.viewDidLoad () -> () in ViewController.o
  "_OBJC_CLASS_$_KDCReader", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
