### ISSUE TITLE
[1.0.0] Umbrella header regression with Mantle

### ISSUE THREAD

**Issue by chrisballinger** [CocoaPods/CocoaPods#5419]
- [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

Compilation regression between 0.39 and 1.0.0.
## Project that demonstrates the issue

A full description of the issue is here: https://github.com/Mantle/Mantle/issues/704

Even though the behavior seems to be the same between 0.39 and 1.0.0 for the umbrella header generation and modulemap, the inclusion of the project-provided `Mantle.h` that uses angled includes of its project headers within the umbrella header seems to cause issues (non-modular includes).

It's resolved by changing Mantle's header to quoted includes, but I can't seem to figure out why it works fine with 0.39.

**Comment by neonichu** [comment]
This is quite strange indeed — I'm assuming you were **not** using different Xcode versions when switching between 0.39 and 1.0.0?

**Comment by cfedak** [comment]
I'm having the same or at least a very similar issue.  I have use_frameworks! set (because another pod requires it), and am using pod 'Mantle'.

Using Xcode Version 7.3.1 (7D1014), if I change to Cocoapods 0.39, I can #import <Mantle/Mantle.h> without errors.  

Using the same Xcode version, If I use Cocoapods 1.0.0 xcode complains that it cannot find <Mantle/Mantle.h>.  If I swich the #import directive to #import "Mantle.h", then I get a new error, where it cannot find <Mantle/MTLJSONAdapter.h>.  The latter directive is in the Mantle.h umbrella header.  

This issues seems to also happen with other framework pods, such as CocoaLumberjack.

**Comment by chrisballinger** [comment]
@neonichu Same Xcode version and environment (7.3.1)

**Comment by wlisac** [comment]
I'm seeing the same Mantle issue with CocoaPods 1.0 and Xcode 7.3.1
