### ISSUE TITLE
Target scope suffix can cause name conflicts with vendored binary names

### ISSUE THREAD

**Issue by xin-savysoda** [CocoaPods/CocoaPods#5518]
- [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report

Either issue with Realm or Cocoapods when building to multiple platforms in one project (e.g. iOS and Apple Watch)
## What did you do?
- Made empty project with build targets to iOS and Apple Watch.
- Added Pods file specifying realm:

```
target 'Testie' do
platform :ios, '7.0'

pod 'Realm'
end

target 'TestieWatch Extension' do
platform :watchos, '2.0'
pod 'Realm'
end
```
- Run pod install
- Open xcworkspace, try to build project
- Errors
## What did you expect to happen?

Project builds and runs
## What happened instead?

201 errors
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.4.5
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f2bdd7fad22d812712a21e6084cf45ce274a50d1
```
### Installation Source

```
Executable Path: /usr/local/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
### Podfile

``` ruby
target 'Testie' do
platform :ios, '7.0'

pod 'Realm'
end

target 'TestieWatch Extension' do
platform :watchos, '2.0'
pod 'Realm'
end
```
## Project that demonstrates the issue

[Testie.zip](https://github.com/CocoaPods/CocoaPods/files/314891/Testie.zip)

**Comment by twomedia** [comment]
+1

**Comment by skrew** [comment]
Same for me, any workaround ?

**Comment by ordinaryman09** [comment]
I tried with the pod 0.39, but I'm still getting the errors

**Comment by dvor** [comment]
Unfortunately 0.39 pod doesn't work for me because of another bug in it. Waiting for fix.

**Comment by mrackwitz** [comment]
I can confirm that this is a problem and could locate the root cause.

The problem here is that there is a name overlapping of the build product of the static library target generated by CocoaPods (`libRealm-iOS.a`) and the vendored static library used by the podspec (`librealm-ios.a`). Even though the name is not exactly identical, clang's linker is case-insensitive and uses the first matching according to the order of the `LIBRARY_SEARCH_PATHS`. As both are required changing the order doesn't help.

Usually the linter ensures that a pod can be built and included in a project. But it uses frameworks by default and doesn't additionally check whether a pod can be used in the integration mode with static libraries.

This requires a fix in CocoaPods to avoid conflicting names of the generated targets.

As an alternative workaround to using an older version as proposed before, you could also declare `use_frameworks!` in your Podfile and use frameworks, while this will break backwards-compatibility to iOS 7.0 for distribution via the AppStore and could potentially lead to other issues when using frameworks with extensions.

**Comment by mrackwitz** [comment]
This would have been more obvious if #4014 was resolved as that's about recognizing such name conflicts. I'll leave this issue open as this is caused by the scoping suffixes introduced by the advanced target deduplication.

**Comment by xilin** [comment]
@skrew 
```
pod _0.39.0_ install
```
works currently. Thanks.
