### ISSUE TITLE
Feature Request: Prompt user to force upgrading "cocoapods" command line tools through Podfile 

### ISSUE THREAD

**Issue by circleplus** [CocoaPods/CocoaPods#5601]
I'm working on a project with multiple pods. I often run into the problem that some of my co-workers always use latest version of cocoapods, some of them whereas stick to old ones. Then I have to constantly do "pod update" when my version is different from theirs. This is sometimes in particular annoying when you don't know whether they're upgrading or not.

so I'm thinking that it might be good to be able to specify the version of cocoapods command line tools in Podfile so when people do "pod install" or "pod update", the version specified in the Podfile would be enforced and user would be prompted to upgrade if necessary. This would be greatly helpful for a team working on different pods.

**Comment by jshier** [comment]
This is what [bundler](http://bundler.io) was designed to address. Define a ` Gemfile` that contains the versions you want and have everyone use `bundle install` to install dependencies and everything should stay in sync. I like to combine it with [RVM](https://rvm.io) and `.ruby-version` and `.ruby-gemset` files so that everyone uses the exact same Ruby version and all of the dependencies are contained in a gemset.

**Comment by orta** [comment]
You can do this by checking `Pod::VERSION` inside your Podfile, but as @jshier - this is bundler's domain.

**Comment by circleplus** [comment]
thanks for all your suggestions. I think going with 'bundler' would be another thing to have team to all agree on. But yeah, it would work.
