### ISSUE TITLE
Does cocoapods recongnize the /*! - */ block

### ISSUE THREAD

**Issue by iDevelopper** [CocoaPods/CocoaPods#5667]
For generating doc?

Thanks

**Comment by orta** [comment]
CocoaPods itself doesn't do any documentation generation, you might want to look at both [Jazzy](https://github.com/realm/jazzy) and [Appledoc](http://appledoc.gentlebytes.com) for more information.

**Comment by iDevelopper** [comment]
Ah! What have I misunderstood?

http://nshipster.com/documentation/

![2016-07-25_17-51-56](https://cloud.githubusercontent.com/assets/1782450/17107757/e5e04fce-5290-11e6-8ef3-6998d072c8d1.png)

**Comment by orta** [comment]
The websites, and infrastructure like CocoaDocs indeed generate documentation, but that's not the domain of CocoaPods - we let other projects (linked above) handle making the web pages. We just host it.  👍

**Comment by iDevelopper** [comment]
Ok, thanks for fast reply, then do you think this block /*! - */ will be recognized? I know this one is recognized (/** - */).

**Comment by iDevelopper** [comment]
Another question, sorry, it is my first cocoapods project. Do I need to trunk push a new version if I change only comments or readme.md after pushing the files to Github?

**Comment by orta** [comment]
The original reason I didn't answer that question is that it's off topic, you should check [appledoc](http://appledoc.gentlebytes.com/appledoc/) - we use Stack Overflow for usage questions like this. Mainly because we have hundreds of thousands of users, and a small core dev team.

But for the second one it's on every trunk push.
