### ISSUE TITLE
can we drop the need for the "--repo-update" flag in "pod install"?

### ISSUE THREAD

**Issue by skydivedan** [CocoaPods/CocoaPods#5697]
I understand the issues identified here:
http://blog.cocoapods.org/Master-Spec-Repo-Rate-Limiting-Post-Mortem/

I realize that there were very good reasons to make the changes described here. However, this part has never really squared with me:
> We will no longer automatically update spec-repos on pod install. If a lockfile exists and podspecs are missing, an error will be raised that suggests the user to update their spec-repos with pod repo update.

I'm just wondering if this particular step was necessary.

See, my thinking about "pod update" and "pod install" goes like this:
`pod update` => satisfy the requirements found in `Podfile`
`pod install` => satisfy the requirements found in `Podfile.lock`

I expect `pod update` to look at the Podfile, and download any dependencies, and get the latest ones. I expect `pod install` to get the *exact* dependencies listed in `Podfile.lock`, and if those dependencies don't happen to be locally cached on my machine, I still expect those dependencies to be satisfied.

I work on a team of about 6 people. I used to explain the difference between `pod update` and `pod install` as described above.  The `Podfile.lock` file is important, so that a build can be made with the *exact dependencies*. Now, when an error is seen, they'll just do a `pod update` - which may not be what is desired. I'd prefer that `pod update` be an explicit action (get me the latest pods). But now it's an error corrective.

And, yes, we could all do a `pod install --repo-update` now instead. I do that, too. But the thing is, in this kind of collaborative environment, with changes happening frequently, and changes to other pods happening frequently... I don't see a case where I'd ever just call `pod install`. B/c more often than not, it's going to error on me, and I'll have to add the `--repo-update` flag.

That's all. If there's a way we can undo the need for the explicit flag in 1.1, that would be awesome.

**Comment by neonichu** [comment]
I think the most important case you're missing is that people might have more than one project. If they switch between them during the day, it is much more likely that updating the spec repo is not necessary.

If the default doesn't suit you, you can indeed just switch to using `pod install --repo-update`, but it still makes sense for the default to be gentle on resource usage.

**Comment by skydivedan** [comment]
Ok, my knowledge of how the tool works might be naive (I mean no sarcasm
there or anything, sincerely), but. Say I have *version 1* of "MyPod" in my
local pod repo, and 4 of 5 projects use version 1.

Now, I `git pull`, on FifthProject, and it wants *version 5* of MyPod,
because that's what is in `Podfile.lock`.

Would the act of retrieving *version 5* of MyPod destroy my local copy of
*version 1*? I thought both versions would be stored on my machine.

See, my thinking is that if *version 5* isn't local, then it will get that
specific version. Once it is local, it won't hit the remote repo again,
right? So I don't see where the extra networking overhead is here.

Anyway, I'm sorry if I'm oversimplifying the process here. I'm likely
missing something. I'm just saying if I want to get the versions in
`Podfile.lock` - then I'll always be adding the `--repo-update` flag, to
make sure I get the right versions. If that's the case, then could you
explain why someone would use `pod install` without the extra flag.

Again, not trying to sound angry or anything, just having trouble
understanding this.

**Comment by orta** [comment]
I think you're confusing the list of specs from the Specs repo, from the actual library code. The spec here being the recipe to install the library. here's one as [an example](https://github.com/CocoaPods/Specs/blob/master/Specs/RxSwift/2.6.0/RxSwift.podspec.json).

The Specs repo is the one that isn't updated on `pod install`. Not the library code, so it will not download new specs from CocoaPods/Specs unless you specifically request it. We do this because it puts an unfair amount of server pressure on github to have so many clients constantly updating. It's the same systems that home-brew uses. 

When you `pod install` it looks through all of your download specs, and will download the libraries for pods that it has specs for.  Most of the time you already have all of the specs downloaded, and so `pod install` will do exactly what it says on the tin, it will turn the lockfile'd dependencies into downloaded libraries.  Adding `--repo-update` says run `pod repo update` before doing `pod install`.

So, if someone in your team creates a new version of your library (e.g. bumps something to from v4 to v5 ) and adds that to the specs repo, you will need to do a specs repo update. Otherwise you shouldn't need to update the spec repo at all.

**Comment by skydivedan** [comment]
OK, thanks for taking the time to further explain this.

-Dan.

**Comment by dd-stoyanova** [comment]
go to platform/ios directory 
run the command 
pod install --repo-update
