### ISSUE TITLE
'Unable to read the license file' for custom license file locations

### ISSUE THREAD

**Issue by miklselsoe** [CocoaPods/CocoaPods#5711]
# Report

When using a project with a custom license file location, CocoaPods warns it can't find it. I have only tested this with a single pod ([Changeset](https://github.com/osteslag/Changeset)) but it seem to be configured correctly, so I think it's a CocoaPods issue (i.e. I haven't been able to find other projects with custom license file location). This can be reproduced with a brand new Xcode project/Podfile (link below). I get this warning when running `pod install`. 

```
[!] Unable to read the license file `/Users/mikkel/Development/TEST/Pods/Changeset/LICENSE` for the spec `Changeset (1.0.5)`
```

This is the `podspec` from [Changeset](https://github.com/osteslag/Changeset):

```
Pod::Spec.new do |spec|
	spec.name = 'Changeset'
	spec.version = '1.0.5'
	spec.license = { :type => 'MIT', :file => 'LICENSE.md' }
	spec.homepage = 'https://github.com/osteslag/Changeset'
	spec.author = { 'Joachim Bondo' => 'joachim@bondo.net' }
	spec.social_media_url = 'https://twitter.com/osteslag'
	spec.summary = 'Minimal edits from one collection to another'
	spec.description = 'A Swift value type to compute and hold the edits required to go from one CollectionType of Equatable elements to another.'
	spec.source = { :git => 'https://github.com/osteslag/Changeset.git', :tag => "v#{spec.version}" }
	spec.source_files = 'Sources/*.swift'
	spec.requires_arc = true
	spec.ios.deployment_target = '8.0'
	spec.osx.deployment_target = '10.9'
	spec.watchos.deployment_target = '2.0'
end
```

## What did you do?

Added the pod [Changeset](https://github.com/osteslag/Changeset) to my project
Run `pod install`

## What did you expect to happen?

Installation without warnings.

## What happened instead?

Pod is installed but with warnings:

```
Analyzing dependencies
Downloading dependencies
Installing Changeset (1.0.5)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `TEST.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

[!] Unable to read the license file `/Users/mikkel/Development/TEST/Pods/Changeset/LICENSE` for the spec `Changeset (1.0.5)`

[!] Unable to read the license file `/Users/mikkel/Development/TEST/Pods/Changeset/LICENSE` for the spec `Changeset (1.0.5)`
```

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9802150c0eb574bdff709656a6345a3f1865717b
               master-1 - git@github.com:CocoaPods/Specs.git @ 96cd568f5e0a7ca44b7596dc46ed9d5f895768f2
               mobilelife - https://github.com/mobilelife/DanskeBank-Pods.git @ 7265933610d75c411b763cce2fcc2c64f51c4a20
               mobilelife-1 - git@github.com:mobilelife/DanskeBank-Pods.git @ 7265933610d75c411b763cce2fcc2c64f51c4a20
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-acknowledgements : 1.1.1
cocoapods-deintegrate      : 1.0.0
cocoapods-plugins          : 1.0.0
cocoapods-search           : 1.0.0
cocoapods-stats            : 1.0.0
cocoapods-trunk            : 1.0.0
cocoapods-try              : 1.0.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TEST' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Changeset'

end
```

## Project that demonstrates the issue

[Sample project](https://www.dropbox.com/s/e0w4q26xuj1xxha/cocoapods_issue.zip?dl=1)

**Comment by neonichu** [comment]
Looks like the 1.0.5 version of this Pod refers to a non-existing license file: <https://github.com/CocoaPods/Specs/blob/master/Specs/Changeset/1.0.5/Changeset.podspec.json#L6> — please report this upstream.

**Comment by linmingzhi** [comment]
I also encountered this problem, don't know how to solve

**Comment by benasher44** [comment]
Hi @linmingzhi! This issue is quite old. Would you mind filing a new issue and filling out the issue template? Thanks!

**Comment by linmingzhi** [comment]
GitPodTextSDK has the license file ,I can see The picture in The attachment。

GitPodTextSDK.podspec passed validation.but I can not search GitPodTextSDK,What should I do ？






At 2016-12-22 22:45:16, "Ben Asher" <notifications@github.com> wrote:


Hi @linmingzhi! This issue is quite old. Would you mind filing a new issue and filling out the issue template? Thanks!

**Comment by linmingzhi** [comment]
GitPodTextSDK git:(1.0.1) pod trunk push

[!] Found podspec `GitPodTextSDK.podspec`
Updating spec repo `master`

CocoaPods 1.2.0.beta.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.2.0.beta.1

Validating podspec
-> GitPodTextSDK (1.0.1)

Updating spec repo `master`

CocoaPods 1.2.0.beta.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.2.0.beta.1


--------------------------------------------------------------------------------
🎉 Congrats

🚀 GitPodTextSDK (1.0.1) successfully published
📅 December 23rd, 01:17
🌎 https://cocoapods.org/pods/GitPodTextSDK
👍 Tell your friends!
--------------------------------------------------------------------------------
➜ GitPodTextSDK git:(1.0.1) pod repo update
Updating spec repo `master`

CocoaPods 1.2.0.beta.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.2.0.beta.1

➜ GitPodTextSDK git:(1.0.1) pod search GitPodTextSDK
[!] Unable to find a pod with name, author, summary, or description matching `GitPodTextSDK`

At 2016-12-22 22:45:16, "Ben Asher" <notifications@github.com> wrote:


Hi @linmingzhi! This issue is quite old. Would you mind filing a new issue and filling out the issue template? Thanks!

**Comment by jasonmerino** [comment]
For anyone that may run across this later, I had this issue with the Lookback pod, but none of my coworkers did. What fixed it for me was just removing all the installed pods and reinstalling them. This was after a `pod cache clean --all` and `pod install` which did not resolve the issue.

**Comment by rob-keepsafe** [comment]
As an FYI for others: if your source points to a `.zip` using the `http:` option in the `.podspec`, you need to ensure the `.zip` file includes a copy of the `LICENSE` file.

e.g.

```ruby
s.source = { :http => "https://github.com/iwasrobbed/MyAwesomeLibrary/releases/download/v#{s.version.to_s}/MyAwesomeLibrary.zip" }
```

CocoaPods doesn't care if the license file is included in the repo root (like it does when you use `git:` as a source); it needs to be included when the source gets unzipped.

**Comment by dnkoutso** [comment]
makes sense. The file is being downloaded instead because thats what the source is.

**Comment by seakeylife** [comment]
> For anyone that may run across this later, I had this issue with the Lookback pod, but none of my coworkers did. What fixed it for me was just removing all the installed pods and reinstalling them. This was after a `pod cache clean --all` and `pod install` which did not resolve the issue.

It's work for me,thanks
