### ISSUE TITLE
Add doc about swift_version podfile config

### ISSUE THREAD

**Issue by puttin** [CocoaPods/CocoaPods#5875]
How about add sample for the latest released version in guides.cocoapods.org about the [`attr_accessor :swift_version`](https://github.com/CocoaPods/CocoaPods/pull/5540/files#diff-462abb0a22117f10761d4fa26213a0adR21)

something like

```
target 'MyApp' do
  swift_version = '2.3'
end
```

people are still using `post_install` something like [this](https://github.com/CocoaPods/CocoaPods/issues/5521#issuecomment-226328062)

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

#5540 #5521

**Comment by puttin** [comment]
and also the `.swift_version` for the Pods

**Comment by orta** [comment]
> How about add sample for the latest released version in guides.cocoapods.org about the attr_accessor :swift_version

This isn't on the Podfile ( the full DSL is here: https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/podfile/dsl.rb )  - this is generated by looking at your targets and deriving it - it's not a public property because it already exists in Xcode

> and also the .swift_version for the Pods

This was added today, we'll be documenting it - don't worry.

**Comment by pcantrell** [comment]
Good _lord_ this was difficult to find!

**Comment by orta** [comment]
I updated the CHANGELOG - which should make it more obvious
