### ISSUE TITLE
Custom compiler options per file

### ISSUE THREAD

**Issue by strax** [CocoaPods/CocoaPods#589]
It would be useful to specify custom linker options per-file basis. Podfile `compiler_flags` attribute could allow a hash where the keys are filenames or patterns and values are the custom compiler options for the corresponding file:

``` ruby
s.compiler_flags = {'Classes/Something.m' => '-f-no-objc-arc', 'Classes/**/*' => '-O0'}
```

**Comment by ipmcc** [comment]
I'd like to add a +1 for the **per-file compiler-flags** feature. This flexibility is especially relevant when packaging up legacy open-source C libraries for easy consumption. You don't hit it this as much with Objective-C but with C libraries, the `subspec` workaround is really clunky. 

If you have a file or two that need different compiler flags, and you put them in `subspec`s, then their link step fails (because the `subspec` can't see anything above it at the moment it's linked.) The only workaround I could find was to add `-undefined dynamic_lookup` to `OTHER_LDFLAGS` (or the more surgical ` -Wl,-U,_single_symbol_to_ignore`). Since it appears that you can't specify per-subspec linker flags (i.e.  `sp.pod_target_xcconfig` appears to be global to the entire Pod) you end up having those linker problems silenced for the whole Pod.

The problem with that is that you're effectively "hoping for the best" when it comes to linking, and any genuinely missing symbols won't be found until runtime, at which point they'll present as largely inscrutable to the end consumer of your Pod. 

What would help? Well, this really turned into an "Old lady who swallowed the fly" situation. Let me recap:
 - I needed per-file compiler_flags (to compile some code that isn't mine, but which I'm trying to package)
 - So I made subspecs for those files
 - Because subspecs imply different units of linkage, I now have missing symbols in my subspecs
 - So I change the linker flags to ignore them
 - Because I appear to be unable to specify `OTHER_LDFLAGS ` per-subspec
 - I end up suppressing the missing symbol errors for the whole Pod
 - And now I have potentially silent errors that would only de-cloak at a later time.

At the end of the day, in this specific case, I wouldn't be in this position if I could just specify per-file `compiler_flags`, but I also suspect that there's a case to be made here for per-subspec linker flags as well. If subspecs are going to be the shoehorn/workaround for all these various complex situations, then I'd argue that they ought to be more flexible.

**Comment by segiddins** [comment]
You can specify an xcconfig or linker flags per subspec already.
In addition, please don't comment on years-old issues.

**Comment by wade0317** [comment]
some time add a subspec could not resolve the problems .
