### ISSUE TITLE
Allow Podspec dependency on a SPM package

### ISSUE THREAD

**Issue by fulldecent** [CocoaPods/CocoaPods#5903]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 🌈

CocoaPods' Podspec file format provides information about a pod and lists dependencies needed to build that pod. Now that Apple, the "upstream vendor", has publicly released Xcode, there is a competing standard for publishing and packaging Swift code, Swift Package Manager.

To promote interoperability, this issue advocates allowing pods to express a dependency on SPM packages.

----

## Dependency

Express such dependencies like this:

    s.dependency = :spm => 'https://github.com/apple/example-package-deckofplayingcards.git'

or

    s.dependency = :spm => 'https://github.com/apple/example-package-deckofplayingcards.git', version => '2.0.1'

Swift has more expressive ways to define version dependencies. To resolve this issue, I recommend we only implement explicit version dependencies for MVP.

 -----

## Fetching

CocoaPods will need to integrate these new dependencies into the xcode workspace. The `swift` command line tool makes this much more simple.

**Comment by orta** [comment]
IMO, we should make it as easy as possible to convert existing CocoaPods libraries into Apple's Swift PM format and make that the way in which people migrate to the officially sanctioned dependency manager. 

Adding support for Swift Packages as a dependency of CocoaPods seems like another place where  Apple will reasonably break an existing CocoaPods project because we made it work with last years SwiftPM format.

**Comment by neonichu** [comment]
Another issue with this would be that swiftpm packages cannot reasonably partake in the resolver which would be a nightmare once transitive dependencies come into play. For example, what happens when the swiftpm dependency depends on AFNetworking and so does one of the Pods?

I was toying with a similar idea back when Carthage came out and abandoned it because of this. I agree with orta that a better way is providing tooling to make it easy for library maintainers to support multiple  or to migrate between different dependency managers.

**Comment by fulldecent** [comment]
Long term, I think the role of CocoaPods will be pod discovery and anything that touches anything that deals with Objective-C.

So what I am hearing here sounds like:

 1. Use CocoaPods to publish your pod no matter what
 2. If writing Swift, and only depending on other SPM-available things, then publish Package.swift

Then eventually peer pressure from downstream will motivate people to drop/replace Objective-C dependencies.

OK, this makes sense and does not require functional changes from CocoaPods.

Thanks for the discussion!

**Comment by fulldecent** [comment]
Maybe to be polite: in the future when someone runs `pod trunk push` we can say:

 > Hi it appears you have a Swift 3.0 project that has no objective-c dependencies, maybe think about supporting SPM, for details see url...

That's something to think about later.

**Comment by fabb** [comment]
SwiftPM also supports Objective-C: https://github.com/apple/swift-evolution/blob/master/proposals/0038-swiftpm-c-language-targets.md

**Comment by orta** [comment]
Yeah, this is great, hopefully by WWDC 2017 we can start recommending people support it 👍
