### ISSUE TITLE
1.1.0 RC 2 not respecting commit ids in Podfile

### ISSUE THREAD

**Issue by mhuusko5** [CocoaPods/CocoaPods#5967]
# Report

## What did you do?

```
pod 'LiyoKit', :commit => '167ce635ba2b531449a674f06833611073e135a8', :git => '....', :branch => 'master'
 
pod 'LIMediaKit', :commit => 'cb80b517be81eba9f2cd4506221fa1f953e2be23', :git => '....', :branch => 'master'
```

## What did you expect to happen?

Commits '167ce635ba2b531449a674f06833611073e135a8' and 'cb80b517be81eba9f2cd4506221fa1f953e2be23' to be used, as previous CP version would.

## What happened instead?

Latest commits from master used, logging...

```
Fetching external sources
-> Pre-downloading: `LIMediaKit` from `https://github.com/LiyoApp/LIMediaKit.git`, commit `cb80b517be81eba9f2cd4506221fa1f953e2be23`, branch `master`
  $ /usr/bin/git ls-remote https://github.com/LiyoApp/LIMediaKit.git master
  b3060347af4a9f65288bcdc28bca2f724ba57b89	refs/heads/master
  > Copying LIMediaKit from `/Users/mhuusko5/Library/Caches/CocoaPods/Pods/External/LIMediaKit/4cf8b993a4da18735d66562a25fb584b` to `Pods/LIMediaKit`
-> Pre-downloading: `LiyoKit` from `https://github.com/LiyoApp/LiyoKit.git`, commit `167ce635ba2b531449a674f06833611073e135a8`, branch `master`
  $ /usr/bin/git ls-remote https://github.com/LiyoApp/LiyoKit.git master
  cc20670db664f1c4537ad0ae522a13d29d9c0fcd	refs/heads/master
  > Copying LiyoKit from `/Users/mhuusko5/Library/Caches/CocoaPods/Pods/External/LiyoKit/5344348855583cbc2129b77d00384d3c` to `Pods/LiyoKit`
```

**Comment by neonichu** [comment]
You shouldn't be specifying `:branch` in this case. Maybe this coincidentally worked in previous versions, but since no precedence between `:commit` and `:branch` is guaranteed, the result is undefined.

**Comment by orta** [comment]
Feels like something we should raise as a warning in `pod install`

**Comment by mhuusko5** [comment]
Oh, interesting. Quick fix.

Out of curiosity.. that sounds like its not possible at all to target a specific commit on non-master branch?

**Comment by orta** [comment]
imagine git as a git soup of commits, branches are just a way of saying this lineage of commits can be named "thing" - a branch is made of commits, but a commit is just a single part of the branch. 

End result: You don't need to have a branch to have a commit. That's why you sometimes see things like this:

![screen shot 2016-09-28 at 20 02 10](https://cloud.githubusercontent.com/assets/49038/18928072/798ba02c-85b6-11e6-9014-34af84dbbdfd.png)

Where I'm just floating around inside a commit, not on a branch. As humans find it easier to think in terms of branches, then git reminds you you're detached from a branch.

**Comment by orta** [comment]
Closing 👍
