### ISSUE TITLE
Could not build Objective-C module

### ISSUE THREAD

**Issue by rvishal1991** [CocoaPods/CocoaPods#6213]
It was working very well with  cocoa pod 0.39 version.
After upgrading it to 1.0.0 it giving me error like:
'Could not build Objective-C module'.
Now, I can not run 'pod install' as project is unable to build.
I haven't made any changes in xcode project settings.
I am using Xcode 7.3.

**Comment by benasher44** [comment]
Hi there! There's no info here about the project you're trying to build, the Podfile you're using, or any other info that we can use to help debug this. We'd love to help, but we'll need some more info! I'm going to close this one since there's no info, but please file a new ticket whenever you're able and fully fill out the issue template. Thanks so much!
