### ISSUE TITLE
Project created by 'pod lib create'  not treat it as a error when method not return properly.

### ISSUE THREAD

**Issue by CodeLife2012** [CocoaPods/CocoaPods#6230]
## What did you do?
Init a new pod with `pod lib create`.

## What did you expect to happen?
Compiler should warn when a method has a return type not return.

## What happened instead?
The project build success when method not return。 

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.6.6
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.0/lib
Repositories :
               master - https://github.com/CocoaPods/Specs.git @ c630ea5dc40079fd6a5c91764766d4e4994d1d6c
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue
[DemoNoReturn](https://github.com/CodeLife2012/DemoNoReturn)
`+ (NSURL *)noReturnMethod` should return a `NSURL`, but actually not return and also build success, make the runtime in risk.

**Comment by ThePantsThief** [comment]
I also frequently experience this issue. Chalked it up to Xcode at the time but now I realize it only happens in my pod development projects.

**Comment by orta** [comment]
Looks like an app gets this by default in Xcode
![screen shot 2016-11-28 at 12 07 04](https://cloud.githubusercontent.com/assets/49038/20667814/3e3308a8-b563-11e6-9137-228fcf8af081.png)

but a framework does not

![screen shot 2016-11-28 at 12 06 50](https://cloud.githubusercontent.com/assets/49038/20667802/339aad42-b563-11e6-8bad-f24e5777e32b.png)

( I just did changed, which is why it is bold )

I agree that this is a legit bug, but I'm not sure that we should be changing any defaults from what apple uses in Xcode I'm afraid, so the answer to this is to raise it as a radar.
