### ISSUE TITLE
Can't compile when the product name has space. 

### ISSUE THREAD

**Issue by ZuYuanZhou** [CocoaPods/CocoaPods#6271]
Error occurred when execute "Code resign ..." when the product name has space.

**Comment by benasher44** [comment]
Hi @ZuYuanZhou! I believe you're referring to code signing failing with paths that contain spaces. This was fixed in #6160 and will be available in an upcoming 1.2.0 beta. If that's not the issue you're referring to, then please file a new issue and fully fill out the issue template, and we'd be happy to help! Thanks for filing!

**Comment by ZuYuanZhou** [comment]
@benasher44 Yes. You are right, waiting for your new version.
