### ISSUE TITLE
RFC: Make pod install not require the specs repo when lockfile present

### ISSUE THREAD

**Issue by marcomorain** [CocoaPods/CocoaPods#6310]
This is related to #3937 🌈 

When building an xcode project that uses CocoaPods on CircleCI (and Travis), a local copy of the specs repository is required. The specs repo is large, and changes often, making caching difficult.

From my naive understanding (as an outsider to the CocoaPods project), a copy of the specs repo should not be necessary when a `Podfile`, an up-to-date `Podfile.lock`, and a full `./Pods` directory are present. This is the case on CircleCI more often than not, because we cache the `Pods` folder from build to build.

For Ruby projects that use Bundler (like Rails projects), we use have the following idiom:

```bash
bundle check || bundle install
```

This allows the build to short-circuit the slow bundle install command when the necessary ruby gems are already present.

I would like to write a PR for CocoaPods (or a CocoaPods plugin as suggested in #3937) that would enable the same short-circuiting workflow for CocoaPods.

The benefits for CocoaPods users would be a minute or two shaved off most CI builds. The benefit for CircleCI (and Travis and other CI tools) would be faster builds, and also much less storage and network overhead.

I would love some guidance on how best to approach this. Are there any reasons why this is not feasible?

**Comment by benasher44** [comment]
Hi @marcomorain! Thanks for the suggestion! This is a great idea, and I think it'd be not too hard to cache the specs themselves. Ideally, I think `pod install` would search this cache for the required specs instead of going to the specs repo, and then it would only go to the specs repo if it can't find the specs it needs (specs are just json files, so should be cheap to cache). By default, this cache could be a folder in the Pods folder (90% sure there's already a folder called `Local Pod Specs` in there that could be used for this). Additionally, I think it'd be great if you could do something like `pod install --specs-cache=<path>` (only would need to do this once, and then we'd save the cache location to the Podfile.lock), which would allow people to save this folder outside of the Pods folder for those of us that would want to commit this cache but not the Pods directory entirely.

@marcomorain if you're up for it, we'd be happy to take a PR adding this feature!

**Comment by marcelofabri** [comment]
`pod install --specs-cache=<path>` would be great 💯

**Comment by DanToml** [comment]
Although the concept of the changes that need to happen here are simple, the code change seems to be more complicated than I originally expected, as most of this is tightly hooked into external sources. Hopefully gonna get some more time to look into this soon.

**Comment by DanToml** [comment]
@probot-stale[bot] this is still important

**Comment by dnkoutso** [comment]
This is an old issue and I believe it is now mitigated by the usage of CDN. CocoaPods no longer needs to clone the master specs repo. Going to close.
