### ISSUE TITLE
Pod lint not searching dependencies linking paths. #6323

### ISSUE THREAD

**Issue by ntnmrndn** [CocoaPods/CocoaPods#6324]
✅ I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

    $ pod repo push specs src_share.podspec

## What did you expect to happen?

Push my spec to the repository

## What happened instead?

- ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
#### Stack

 

>   CocoaPods : 1.1.1
>         Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
>     RubyGems : 2.5.2
>         Host : Mac OS X 10.12.2 (16C67)
>        Xcode : 8.2 (8C38)
>          Git : git version 2.11.0
> Ruby lib dir : /usr/local/Cellar/ruby/2.3.3/lib
> Repositories : master - https://github.com/CocoaPods/Specs.git @ a7d152f65e7d1e5eb8649e97972470d1428003ef
>                specs - git@git.motionportrait.jp:antoine/specs.git @ a959dd91824df30f64b5c512dce9658da01bb3a9

#### Installation Source

Executable Path: /usr/local/bin/pod
#### Plugins

> cocoapods-deintegrate : 1.0.1
> cocoapods-plugins     : 1.0.0
> cocoapods-search      : 1.0.0
> cocoapods-stats       : 1.0.0
> cocoapods-trunk       : 1.1.1
> cocoapods-try         : 1.1.0

#### Explanations:

I created a private repo with some specs.

One of the specs contains a collection of pre compiled libraries (.a). We expect the user to link the appropriate ones since some of them are optional. This worked great so far.

I created a repos (Repo B) that contain a collection of utilities that rely upon one of A libraries.

Here is the relevant part of B podpsec

>s.source_files = "iOS/src", "iOS/include"
>s.library = "theLib" #The dependency that fail to link
>s.dependency "PodA" #A pod

And the relevant part of A pod spec
> s.ios.xcconfig = { "LIBRARY_SEARCH_PATHS" => "${PODS_ROOT}/#{s.name}/lib.iOS/lib.release/" }
> s.preserve_paths = 'lib.iOS/lib.release/*.a'
> s.source_files = "include/*.h"
>s.xcconfig = { "HEADER_SEARCH_PATHS" => "${PODS_ROOT}/PodA/include/" }
>s.ios.xcconfig = { "LIBRARY_SEARCH_PATHS" => "${PODS_ROOT}/PodA/lib.iOS/lib.release/" } #LD command is laking this mandatory path

So to test the build of B lint should provide the LIBRARY_SEARCH_PATHS from A but fails to do so. The build fail at link time with `-ld: library not found for -theLib`

**Comment by ntnmrndn** [comment]
I included `{ "HEADER_SEARCH_PATHS" => "${PODS_ROOT}/PodA/include/" }` in Pod B as a workaround.

**Comment by benasher44** [comment]
Hi @ntnmrndn! There are a couple of issues I can spot right off the bat, and maybe tackling those will get you farther:

- `s.sources_files = "<folder>"` might not be sufficient to pick up all the files you expect. Instead, try `s.sources_files = "<folder>/*"` or `s.sources_files = "<folder>/**/*"` to ensure that CocoaPods includes the contents of those folders.
- Instead of `s.xcconfig`, try using `s.pod_target_xcconfig` instead. This'll ensure you're only modifying XCConfigs related to building this pod.
- Finally, you shouldn't need those `xcconfig` lines at all. CocoaPods will pull in all of the files and setup the header search paths for you project appropriately

Let me know how it goes!

**Comment by ntnmrndn** [comment]
Hi @benasher44,
Thank you a lot for your time.

I tried your suggestion, but the same problem persist. I'm afraid I was not specific enough in explaining my setup. I edited my post but let me sum it up:

Pod A contains pre compiled libraries; as ressources. xcconfig seems to be mandatory in this case.
Pod B needs to links against Pod A libraries; but Pod A's xcconfig is not taken into account for PodB building.

**Comment by benasher44** [comment]
Using XCConfigs in general is fine. We just recommend using `pod_target_xcconfig` or `user_target_xcconfig`, since `xcconfig` is deprecated. I noticed something else:

> s.xcconfig = { "HEADER_SEARCH_PATHS" => "${PODS_ROOT}/PodA/include/" }
s.ios.xcconfig = { "LIBRARY_SEARCH_PATHS" => "${PODS_ROOT}/PodA/lib.iOS/lib.release/" } #LD 

should really be:

> s.ios.user_target_xcconfig = { "LIBRARY_SEARCH_PATHS" => "${PODS_ROOT}/PodA/lib.iOS/lib.release/", "HEADER_SEARCH_PATHS" => "${PODS_ROOT}/PodA/include/" }

The 2nd time you set `xcconfig`, I *think* it'll just overwrite the previous value. You should instead just set it all at once. It's safe however to set `s.ios.user_target_xcconfig` followed by `s.osx.user_target_xcconfig`, since those are namespace by platform.

Can you give that a try?
