### ISSUE TITLE
EACCES - Permission denied

### ISSUE THREAD

**Issue by adwardWang** [CocoaPods/CocoaPods#6331]
Errno::EACCES - Permission denied - /Users/Adward/Downloads/预习代码/10-DSWB(自定义转场)/DSWB/Pods/AFNetworking/AFNetworking/AFHTTPSessionManager.h

Help me check it. Thanks

**Comment by benasher44** [comment]
Hi @adwardWang! Thanks for filing an issue! Unfortunately, there's not enough detail here for us to debug this, so I'm going to close this for now. If I could hazard a guess, I'd say there's some kind of permissions issue in your Downloads folder or elsewhere in the path that you provided, and something like that is usually fixed with some combination of the `chown` or `chmod` commands. Whenever you're ready, feel free to open up a new ticket and fully fill out the issue template. Once you can do that, we'd be happy to help you out. Have a great day!
