### ISSUE TITLE
Mac App Extension Crashes with Image Not Found for Cocoapod Dependencies

### ISSUE THREAD

**Issue by jeffreybergier** [CocoaPods/CocoaPods#6342]
# Report

**Mac App Extension Crashes with Image Not Found for Cocoapod Dependencies**

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

I'm working on a Mac Share Extension and it looks like Cocoapods isn't getting the extension the cocoa pods frameworks. I also have an iOS app and iOS share extension in the same project (not the project below) and they work fine. So I'm not sure if its related to a difference in how iOS App Extensions work compared to Mac OS share extensions? Its probably something I am doing wrong.

Any help or workarounds you could suggest would be extremely helpful.
Thanks so much!
Jeff

## What did you do?

1. Create new OS X Cocoa Application Project in Xcode 8.2 release
1. Add OS X Share Extension Target
1. Run the Mac App and run the extension
    - I run the extension via notes app because its easy to quit and reopen
1. Close the project in Xcode
1. Open Terminal and CD into the folder
1. run 'pod init'
1. Add the pod file I have pasted below into the podfile
1. Run 'pod install'
1. Open the XCWorkspace
1. Run the Mac App, Run the extension
    - I had issues running the extension via the GUI
    - If this happens, CD into the AppEx file in the Derived Data folder and execute the binary in the terminal

```

target 'PodApp' do
  platform :osx, '10.12'
  use_frameworks!
  pod 'RealmSwift'
end

target 'PodExten' do
  platform :osx, '10.12'
  use_frameworks!
  pod 'RealmSwift'
end

## this section comes from the getting started guide at Realm.io
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0.2'
    end
  end
end
```

## What did you expect to happen?

1. Expected the default template share extension to appear in the notes app

## What happened instead?

Crash due to missing dynamic library

```
dyld: Library not loaded: @rpath/Realm.framework/Versions/A/Realm
  Referenced from: /Users/jeffreybergier/Library/Developer/Xcode/DerivedData/PodApp-cajtdvpffhxwtggjnywxzmvwmwrp/Build/Products/Debug/PodExten.appex/Contents/MacOS/./PodExten
  Reason: image not found
fish: './PodExten' terminated by signal SIGABRT (Abort)
```

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2 (8C38)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 29a67416420577872b600154196da40821602427
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

[RealmApp.zip](https://github.com/CocoaPods/CocoaPods/files/669648/RealmApp.zip)

**Comment by benasher44** [comment]
Hi @jeffreybergier! Thanks for bringing this up! I went ahead and downloaded your app, and I don't think you can execute the extension directly like you're trying to. To get this to work, I first had to fix some signing issues and ensure I had a development team selected. Once that was done, building and running the Notes app from the RealmExtension scheme installed the extension properly and it showed up in the Extension pref pane on my mac (i.e. now we know it's installed). The next step was to get it to actually show up in the Notes app's share menu, and to do that you have to modify its Info.plist. Here's how I updated it:

![screen shot 2016-12-23 at 9 58 39 pm](https://cloud.githubusercontent.com/assets/1120429/21465513/4c33691e-c95b-11e6-83c2-6203da58cad7.png)

You can see I added some attributes that explicitly allows using this extension with text-type data. Once I did that, the RealmExtension showed up in the Notes app's share menu, and it launched just fine.

Since this doesn't appear to be a CocoaPods issue (i.e. nothing I can do here to patch CP make this work better), I'm going to close this. Have a great weekend, and best of luck with your extension!

**Comment by jeffreybergier** [comment]
Hi @benasher44 thanks for looking at this,

I was unable to reproduce your fix. It worked on that downloaded project (that had a podfile, but did not have pods installed). But once I ran pod install it broke it again.

The default NSExtensionActivation rule is TRUEPREDICATE which means it should show up in every menu. Also, the framework error is there still. 

Is it possible you could try following the steps in the issue rather than using the project? That way you're guaranteed to run into the issue.

Thanks and Merry Chrismas!
-Jeff

**Comment by jeffreybergier** [comment]
I found a temporary workaround. I had to enable embedding all swift libraries which causes a warning in cocoapods. I also had to add a copy phase to copy the frameworks from Cocoapods. Attached are screenshots. This got the share extension to launch in Notes.

<img width="951" alt="realmapp_xcodeproj" src="https://cloud.githubusercontent.com/assets/7349616/21468666/b886cc50-c9d3-11e6-9ffb-1281054edcb7.png">
<img width="1178" alt="realmapp_xcodeproj" src="https://cloud.githubusercontent.com/assets/7349616/21468668/bb5dbd94-c9d3-11e6-8a71-daec0a47e2a1.png">

**Comment by benasher44** [comment]
I tried following your instructions, but I don't believe the extension is intended to be launched directly like that because of how they have to live in a host app. This seems accurate, given how the default scheme setup doesn't launch the extension directly, it requires that you pick an app in which you want to try the extension, and then it install the extension into your system.

I can put the Info plist back to how you had it, but I don't think that was the root issue anyway (i.e. I agree with your assessment of TRUEPREDICATE). The fact is that with your project as it was, the extension wasn't showing up in the list of extensions in the system preferences. Once I fixed that (by fixing some signing issues), it was just a matter of messing with the Info.plist (which I had already messed with, so I just fixed it I saw fit but again your way would've prob been fine). Then, it launched fine. Can you try making sure there are no signing/team issues in your General tab there, when your RealmExtension target is selected?

**Comment by benasher44** [comment]
I don't mean to sound dismissive. The question to me seems to be: does CocoaPods work for Mac extensions with the default extension project? And I believe the answer is: yes assuming you have signing setup correctly such that the debug extension gets properly installed into your system

**Comment by jeffreybergier** [comment]
@benasher44 I'm a little confused. I am launching it from within the Notes app or Safari or any other app that supports extensions. Once I made the modifications in the screenshot, it launched via those programs fine. But every time cocoapods is run, those settings are reset to how Cocoapods wants to handle extensions and then it breaks again.

**Comment by jeffreybergier** [comment]
@benasher44 Thanks a lot for your help. I'm doing some more investigating to see if I can get it to work as you say.
