### ISSUE TITLE
Setting up cocoapods master repo update stuck

### ISSUE THREAD

**Issue by kwstasna** [CocoaPods/CocoaPods#6404]
Hello.
All day i'm trying to update the repo master with no luck.
First I've tried with "pod install" and seen by Activity Monitor that git-remote-https is stuck at 30mb of download and doesnt download anymore. I've got a stable internet connection.

Also if tried to clone the git inside 
`cd /Users/kwstasna/.cocoapods/repo/`
`git clone https://github.com/CocoaPods/Specs.git master`

Still no luck, sometimes it stops at 29% some other times in 1%

Also tried to manually the unzipped file from git Cocoapods/Specs
but when i try the `pod install` i get

`[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master-1`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.`

Also updated all gems.
Any idea why?

**Comment by benasher44** [comment]
It's working fine for me right now. I just did a fresh clone. Can you try `rm -rf ~/.cocoapods`, and then run `pod setup`? Maybe there was some kind of Github or network issue on your end earlier.

**Comment by kwstasna** [comment]
I have macos sierra 10.12 via vmware and i'm using the NAT network.
Although in my Windows when i execute git clone to a folder, it's working fine.
When i download it as a zip from github, it downloads it fine without interruptions on the Activity Monitor -> Network.

**Comment by benasher44** [comment]
I'd make sure your developer tools are up-to-date to start. This doesn't sound like a CocoaPods issue though, since this appears to be an issue with your macOS environment, and it doesn't seem like there's a patch we could make that would help fix your situation. I recommend asking on Stack Overflow to try to get more community help with your macOS/git environment. Best of luck, and please feel free to update this issue in the future if you find a solution. Have a great day!
