### ISSUE TITLE
Signing for --- requires a development team. Select a development team in the Target Editor.   Code signing is required for product type 'Framework' in SDK 'iOS 10.0'

### ISSUE THREAD

**Issue by kartheekminna** [CocoaPods/CocoaPods#6445]
I AM A NOOB.
trying to install popcorn time on my apple tv 
but these error come up:-

Signing for --- requires a development team. Select a development team in the Target Editor.

Code signing is required for product type 'Framework' in SDK 'iOS 10.0'

help--
complete instructions..

**Comment by benasher44** [comment]
Hi @kartheekminna! Thanks for the report! There's not enough info here for us to really help you debug  this issue. Because I can't tell that this is a CocoaPods issue (and no debug info/output), I'm going to close this one. This looks more like a generic signing issue, so I encourage you to repost your question on Stack Overflow, and I'm sure there are folks there that could help out and give more pointed advice. Have a great day!
