### ISSUE TITLE
source_files not support path like "../../xxx"

### ISSUE THREAD

**Issue by SylviaRu** [CocoaPods/CocoaPods#6466]
I write my podspec file in a sub directory. So the source_files I write as
```
s.source_files  = "../../React/**/*.{c,h,m,mm,S}"
```

But I find that the `..` not work. How to make it work?

**Comment by benasher44** [comment]
Hello! Thanks for bring this up! You should be able to make a symlink in your pod root directory that links to wherever you need to pull in source files from. I'm going to close this, since I believe this is a well-known work around. Please let us know if this doesn't fix your issue. Have a great day!

**Comment by SylviaRu** [comment]
@benasher44  I maked a symlink,  but it didn't work.

**Comment by benasher44** [comment]
Can you provide more details that include your updated `s.source_files`, the command you ran to create the symlink, and the error you encountered? Thanks!

**Comment by robertjpayne** [comment]
@benasher44 hey Ben I'm struggling with this a little bit too:

- `<ProjectDirectory>/<AppName>` (this is where the podfile/xcodeproj lives)
- `<ProjectDirectory>/Podspecs/Axis.podspec`
- `<ProjectDirectory>/Podspecs/Vendor` (symlink to ../Vendor)
- `<ProjectDirector>/Vendor/Axis/Sources/Axis/<swift files>`

I have `pod 'Axis', path: '../Podspecs`
I have `source_files` set to `Vendor/Axis/Sources/Axis/**/*.{swift}`

It seems to resolve the podspec just fine but it doesn't cope with the symlinked Vendor folder for some reason. If copy the Vendor folder rather than symlink it it works.
