### ISSUE TITLE
Can cocoapods be more friendly?

### ISSUE THREAD

**Issue by codesourse** [CocoaPods/CocoaPods#6525]
In china or other developing country,the network is very bad.When we run "pod install",waiting there.
we don't know installing percentage.Can cocoapods be more friendly as homebrew?

**Comment by segiddins** [comment]
Running `pod setup` first should show the git progress for the first clone of the specs repo -- a PR that improves the cloning experience would be very welcome, though!

**Comment by benasher44** [comment]
This would be a nice enhancement!

**Comment by adellibovi** [comment]
I would like to work on this, but I have a question, shouldn't the development to enable the progress be on the repo of cocoapods-downloader?

**Comment by benasher44** [comment]
@adellibovi awesome! Usually I think you'd be right, but in this case it looks like we run the git commands from `cocoapods/command/repo/add.rb`, and `cocoapods/command/setup.rb` calls into this with and includes the `--progress` argument. So, we should be showing download progress, and if we're not we should fix/improve that. Feel free to ask more questions!

**Comment by adellibovi** [comment]
@benasher44 I believe this issue is about "pod install"? Maybe @segiddins was just giving an example where we have a progress?

**Comment by adellibovi** [comment]
I'll have a look at pod setup though 😊

**Comment by benasher44** [comment]
Ah whoops! I suppose this issue is a bit unclear. Generally speaking, `pod setup` is the thing that takes the longest and gets the most complaints. This issue is unclear because it's not clear if `pod install` was also cloning the master repo for the first time or updating it. `pod install` could maybe have a `--progress` argument added to it as well though. I don't see why not, and then it could show the progress of updating the specs repos as well as fetching pods and maybe even always pass `--progress` to the git process in the case that the master specs repo is being cloned for the first time. In any case, I'm sure there are several easy-ish enhancements here's in the way of providing more feedback on slow networks. Have at it!

**Comment by adellibovi** [comment]
Hi @benasher44, thanks for your comments I had a look and this is what I found.

About pod setup:
on first setup, it does show the progress correctly.
on updating, it does NOT show the progress, I could do a PR to address this specific case. I was thinking of adding the flag into SourceManager, may I move on and submit it?
About pod install:
if called when Cocoapods is not setup, it will call the pod setup and show correctly the progress.
if called for updating the master specs, it will not show the progress, even with the change of what I was talking before. This is because the update get called via the analyser. which update the repositories without passing any show_output, so by default it's hidden. About this, do you think we should pass just a true, or maybe we could modified the analyser to support a property show_output, which would be set only in case of --verbose?
I would really appreciate your thoughts on this.

I left aside for now fetching pods, for which I think the cocoapods-downloader is responsible, please correct me in case I misunderstood.

**Comment by benasher44** [comment]
I think showing progress for updating the specs repo would be great!

**Comment by adellibovi** [comment]
Cool 😊, I'll prepare the PR for the first part.

About fixing it for the pod install, what do you think it's the best approach? Having a property for the analyzer for show_output, or just passing a true when calling the source's update method?

**Comment by benasher44** [comment]
I think it's fine to just pass true (I.e. Always show progress when updating the specs repo)

**Comment by adellibovi** [comment]
Thanks again for your help, I send a PR with both changes we discussed.

**Comment by benasher44** [comment]
Closing via #6550. @adellibovi thanks for your contribution!
