### ISSUE TITLE
pod install use :git=> :branch=>, can we select the git repo path for podspec .

### ISSUE THREAD

**Issue by huangcheng1** [CocoaPods/CocoaPods#6581]
when i use reactnative with pods , such as 
`pod 'React', :git => 'https://github.com/facebook/react-native.git', :tag => 'v0.42.3'`
now react-native has yoga podspec in react-native/ReactCommon/yoga/Yoga.podspec , so i can't use this way .

i want to know any way to use this way.

**Comment by benasher44** [comment]
Hi there! Thanks for the report! It's unclear to me what's going wrong here, and this may even be something to bring up with the pod author. I'm going to close this since there's not enough info for us to help. If you could please file a new issue when you're ready and fully fill out the issue template, then we'd be happy to help out. Have a great day!
