### ISSUE TITLE
Pod installation complete! There are 0 dependencies from the Podfile and 0 total pods installed.

### ISSUE THREAD

**Issue by WCrazyStone** [CocoaPods/CocoaPods#6583]
current pod version  1.2.1.beta.1

i make a private pod to learn, when using pod search  ,  i can find it below:

-> testPod (0.1.5)
   RBPodTest for learning how to using cocoaPods
   pod 'testPod', '~> 0.1.5'
   - Homepage: https://github.com/WCrazyStone/testPod
   - Source:   https://github.com/WCrazyStone/testPod.git
   - Versions: 0.1.5 [podTest repo]

I want to use this private pod  in an testing xcodeProject and add a podfile 

platform :ios, '8.0'
source 'https://github.com/WCrazyStone/testPod.git'  #我们自己的私有spec仓库的地址
source 'https://github.com/CocoaPods/Specs.git'
target 'testAlert’ do 

end

when I run  pod update --no-repo-update  , the result is below:

Crazy:testAlert crazy$ pod update --no-repo-update

Update all pods
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 0 dependencies from the Podfile and 0 total pods installed.

[!] Smart quotes were detected and ignored in your Podfile. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

[!] The Podfile does not contain any dependencies.
Crazy:testAlert crazy$ pod update --no-repo-update

================================================

when I change the podfie content:

platform :ios, '8.0'

target 'testAlert’ do 
pod 'testPod’, :git => ‘https://github.com/WCrazyStone/testPod.git’
end

success:

Crazy:testAlert crazy$ pod update --no-repo-update
Update all pods
Analyzing dependencies
Pre-downloading: `testPod` from `https://github.com/WCrazyStone/testPod.git`
Downloading dependencies
Installing testPod (0.1.5)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

[!] Smart quotes were detected and ignored in your Podfile. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

=========================================================

can yout tell me the first podfile why not suceessful ?

**Comment by WCrazyStone** [comment]
in the first podfile , I forget to add pod 'testPod’, '~0.1.5'

**Comment by sajibsaha4647** [comment]
i deleted pod file and again init pod . but there no dependency are added why ?

**Comment by JustAimz** [comment]
I solved this by using `pod deintegrate` and deleting `podfile` and `podfile.lock` and then starting debugging by VS Code on IOS Simulator.

**Comment by fahmidul** [comment]
Maybe your pod file is almost empty like below example.

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
end
```

There should be some necessary information. You can copy it from other project. Or you can use from this link. https://learnflutter.co/flutter-podfile-0-dependencies/

I found this answer from this youtube video https://www.youtube.com/watch?v=2s2JTEzHrlA

**Comment by muhammadarslannasr** [comment]
Hi I have used above all ways but unable to fix the issue below flow I followed and works fine.

Code for Podfile 0 dependencies. It happens because your Podfile is empty. Nothing is there. Put the code below and run pod install.

Pod installation complete! There are 0 dependencies from the Podfile and 0 total pods installed.

# Uncomment this line to define a global platform for your project
# platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
