### ISSUE TITLE
Parallelize `rsync` in 'Embed Pods Frameworks' stage script

### ISSUE THREAD

**Issue by tomj** [CocoaPods/CocoaPods#6621]
(This didn't seem like a good fit for the boilerplate ticket header, so I removed, apologies if that was the incorrect thing to do)

Following on from #6088 and suggestion by @orta I'm wondering if it's possible or worthwhile to parallelise the

`rsync -av --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "${source}" "${destination}"`

line in the `Pods-*-frameworks.sh`.  It seems to be taking up a large chunk of the build time on my local so any way to reduce that would be great.  I'm pretty time constrained atm but will have a poke around when I have some spare cycles.  Feel free to throw more ideas here if this is a silly path for me to be heading down && || this is the wrong place to be adding this.

Cheers! 😀

**Comment by tomj** [comment]
😄 thanks for triaging @benasher44 will report back with any findings

**Comment by benasher44** [comment]
No problem! We'd certainly appreciate a PR with any improvements that can be made here!

**Comment by tomj** [comment]
You bet!  Trying to recruit a friend right now with shell-fu better than mine right now to assist the effort! 😄

**Comment by aufflick** [comment]
This would open the way to solving #6252 also - once the pods are being `rsync-ed` as separate commands, we can use the `--itemized-changes` or `-stats` option on `rsync` to know whether codesign can be safely skipped (could be in the same parallel loop as if you enable the `PARALLEL_CODESIGN` option).

**Comment by dnkoutso** [comment]
I think this can be closed and and superseded by https://github.com/CocoaPods/CocoaPods/pull/6800. The scripts will no longer re-execute unless the inputs or outputs have changed.

There is something to be said that *when* the script actually needs to run it *could* run faster by parallelizing this effort but I don't think it will happen that often.

I am going to close this, feel free to re-open if you feel strongly for improving the script itself.

**Comment by jgavris** [comment]
I think this is still a valid issue, can we keep it open / think about it? I'm not sure 'Input Files' in Xcode will work with a directory as implemented in #6800 (because Xcode would have to track every file in that directory, since directories are not modified when their contents are).

I've been working with https://github.com/bazelbuild/bazel a bit lately, and one thing it's really good at is very quickly determining there is nothing to do (using a content-based comparison). Wanted to plant a seed to think about how we might make an podspec adapter that converts to a bazel build rule.

**Comment by siuying** [comment]
With Xcode bug #8073 this is relevant again.
