### ISSUE TITLE
Error on pod install

### ISSUE THREAD

**Issue by maheshpandian2k6** [CocoaPods/CocoaPods#6656]
Hi,

  Am getting error while executing pod install command. Please see the attached screenshot

![screen shot 2017-04-15 at 11 51 40 am](https://cloud.githubusercontent.com/assets/27403897/25061393/e317ba04-21d2-11e7-95c2-84ba450d02f4.png)

ℹ project link [https://github.com/layerhq/Atlas-Messenger-iOS](url)

**Comment by benasher44** [comment]
Hi there! Thanks for the report! You appear to be having some permissions issues in your ~/Downloads folder, as indicated in the error output. Since this is an environment issue that we can't provide support for via a patch to CocoaPods, I'm going to close this. Please feel free to reopen if you can provide more detail around why you expect CocoaPods to `pod install` correctly in this scenario after verifying that your folder/filer permissions are in good shape. Thanks!
