### ISSUE TITLE
Set file type for specific source files

### ISSUE THREAD

**Issue by Naituw** [CocoaPods/CocoaPods#6688]
# Report

## What did you do?

Writting podspec for a cross-platform project, which previous build with `Make`, the project contains some file with `NASM assembly` type.

## What did you expect to happen?

I expect there is a way to set the file type for specific sources. So my `.asm` files can compile with `NASM assembly` format.
Note the file type can be set manually in Xcode: 
- Select a file - `File Inspector` - `Identity and Type` - `Type`
(It is corresponding to `explicitFileType` in `PBXFileReference`)

## What happened instead?

I can't find a option to set the file type with `podspec`, all file with `.asm` extension compiled with type `Plain Text`

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.5 (16F67a)
       Xcode : 8.3.2 (8E2002)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /Users/wutian/.rbenv/versions/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9f8faa4a84eb9f9d7f84b71e7a88808970fb2897
```

### Installation Source

```
Executable Path: /Users/wutian/.rbenv/versions/2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/Naituw/DemoFileTypeFailure

Usage:
- Build `ProjectWithNASM/ProjectWithNASM.xcodeproj`, which will success.
- Build `PodUser.xcworkspace`, which will fail, because `x86inc.asm` has incorrect file type

**Comment by orta** [comment]
Sounds like it'll need to be added as a type of source file inside cocoapods-core, I think

**Comment by Naituw** [comment]
I'm currently set this in client `Podfile`, not sure if it's the best option for now

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'FFmpeg'
      target.build_phases.each do |phase|
        phase.files_references.each do |file|
          if File.extname(file.path) == '.asm'
            file.explicit_file_type = 'sourcecode.nasm'
          end
        end
      end
    end
  end
end
```

**Comment by dreampiggy** [comment]
What about this issue ?

I have a C++ lib, which use the `.cpp` as the headers to be used in `#include`, like this:

```
#include "flif-interface_dec.cpp"
#ifdef HAS_ENCODER
#include "flif-interface_enc.cpp"
#endif
```

See: https://github.com/FLIF-hub/FLIF/blob/v0.3/src/library/flif-interface.cpp

However, current I have no any idea how to bring this lib for CocoaPods, because the podspec syntax have no way to specify a file type used by Xcode. This file type will effect the clang compiler to treate this file as header to source files. If the `cpp` was treated as source files, it does not support something like `#pragma once` and cause the duplicate symbol.

![image](https://user-images.githubusercontent.com/6919743/54485183-38be8f00-48af-11e9-8848-e0a098eecae2.png)


However, I can use Carthage or Native Xcode framework to build the framework. See the native Xcode project here, succesfully build:

https://github.com/SDWebImage/libflif-Xcode

**Comment by dreampiggy** [comment]
This issue is still not been solved. I'm tied of CocoaPods's support for C++/C/Assembly Language. Use the pre-built library instead.
