### ISSUE TITLE
xcconfig in podspec not be set in other pod

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#6696]
CP 1.2.1

I write a podspec for a framework:
```
{
  "name": "libwebp",
  "version": "0.5.1",
  "license": "MIT",
  "xcconfig": {
    "USER_HEADER_SEARCH_PATHS": "$(inherited) \"$(SRCROOT)/Headers/Public/libwebp/libwebp\""
  }

 ...
}
```

When I use the `SDWebImage`, the SD will not find the header of the `libwebp`. I check the xcconfig of `SDWebImage`, I found the `USER_HEADER_SEARCH_PATHS` is not work in SDWebImage. The xcconfig will only work the `libwebp` and my host app target:

```
OTHER_LDFLAGS = -framework "ImageIO"
PODS_BUILD_DIR = $BUILD_DIR
PODS_CONFIGURATION_BUILD_DIR = $PODS_BUILD_DIR/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_ROOT = ${SRCROOT}
PODS_TARGET_SRCROOT = ${PODS_ROOT}/SDWebImage
PRODUCT_BUNDLE_IDENTIFIER = org.cocoapods.${PRODUCT_NAME:rfc1034identifier}
SKIP_INSTALL = YES
USER_HEADER_SEARCH_PATHS = $(inherited) $(SRCROOT)/libwebp/src
```

I think the libwebp's xcconfig paramter should be set to all pods that need libwebp. Why not?

**Comment by orta** [comment]
CocoaPods only provides hooks for [pod_target_xcconfig](https://guides.cocoapods.org/syntax/podspec.html#pod_target_xcconfig) and [user_target_xcconfig](https://guides.cocoapods.org/syntax/podspec.html#user_target_xcconfig) - I'm surprised that worked at all.

I'm also pretty sure we built this so that libraries could not disturb each other by re-writing their settings. I think the route you want to go here it to have a subspecies (or version) of SDWebImage that has these flags, rather than having your lib try modify SDWebImage at runtime.

**Comment by Whirlwind** [comment]
I don't think so. The libwebp will need some config when other pods use it. The config should be set by the libwebp rather than other pods. The webp will modify the config anytime.

eg. there are some macros will work the webp's header files, so webp will set the macro in the podspec's xcconfig. If there are not the macros, the webp will have some behaviors. 

I think the macro should not in the SDWebImage's subspec. They are not SDWebImage's config.
