### ISSUE TITLE
'Too Many Symbols' - Expected behaviour when one pod depends on a subspec of another pod?

### ISSUE THREAD

**Issue by kaosdg** [CocoaPods/CocoaPods#6819]
So I'm trying to resolve a `Too many symbol files - These symbols have no corresponding slice in any binary` warning I am getting from iTunes Connect.

Lets say for example if I have the following scenario:

__Application podfile:__

```
    # Framework A
    pod 'FrameworkA/SubSpecA', '1.0.0'
    pod 'FrameworkA/SubSpecB'
    pod 'FrameworkA/SubSpecC'

    # Framework B
    pod 'FrameworkB', '1.0.0'
```

__Framework B's Podspec:__

```
    # ... truncated for brevity, but Core is a default_subspec ...

    s.subspec 'Core' do |core|
        core.dependency 'CocoaLumberjack', '2.2.0'
        core.dependency 'JSONModel', '1.2.0'        
        core.dependency 'FrameworkA/SubSpecA', '~> 1.0'
    end
```

When I integrate this in my app, this results in CocoaPods creating 2 target frameworks in the Pods Project, one with a dynamic name, such as `FrameworkA-c174cac4`, and another `FrameworkA-SubSpecA`.

This is seemingly problematic because *both* of those frameworks define their resultant module name as `FrameworkA`. 

It seems as though Cocoapods is not recognizing that `FrameworkA/SubSpecA` has already been included and is available via `FrameworkA-c174cac4` and just defaults to creating a new uniquely named target, even though their resulting module names are the same.

What I see happen is at archive time, I'll get 2 dSYM outputs, `FrameworkA.framework.dSYM` and `FrameworkA.framework 1.dSYM`.  There is, however, only 1 framework file generated.

I *suspect* when I submit this app, this is what is causing me to get `Too Many Symbols` warnings from iTC, as when I look at the symbol files in question, they are both relating to `FrameworkA`.

Any pointers here?  I am not totally sure this is a bug, however it seems odd that a new framework target would be created for the Subspec, and odder still that 2 dSYMs are created but only 1 framework.

Thanks in advance, and if necessary I will try to put together a simple project demonstrating the issue.

**Comment by dnkoutso** [comment]
@kaosdg sample project would help for this.

**Comment by chefnobody** [comment]
@kaosdg FWIW, I'm having the same issue with iTunes, though I have a different CP set up. It might be helpful to take the UUIDs from the iTunes Connect warning email you got and see what Frameworks are including symbols for which you do not have a corresponding binary. I'm going to hazard a guess and say you're Framework comes shipped with `i386` and `x86_64` dSYMs and _they_ are not being stripped from the .ipa's Symbols directory during archive. I think you can do the following to find out w/ .framework's dSYMs are being included:

From Xcode create an .xcarchive by going to Product > Archive and then when the Organizer opens, right click on the archive and it choose “Open in Finder”. It should take you to a dir that looks roughly like this:
 
```
~/Library/Developer/Xcode/Archives/2017-10-06/
 ```
From there list the files in that directory:
```
ios-app $ cd ~/Library/Developer/Xcode/Archives/2017-10-06/
2017-10-06 $ ls -al
total 24
drwxr-xr-x   5 chump  CORP\Domain Users   170 Oct  6 12:38 .
drwxr-xr-x  27 chump  CORP\Domain Users   918 Oct  6 11:11 ..
-rw-r--r--@  1 chump  CORP\Domain Users  8196 Oct  6 12:38 .DS_Store
drwxr-xr-x@  6 chump  CORP\Domain Users   204 Oct  6 11:12 App-Release.3.6.32 2017-10-06 11.11.10.xcarchive
```
Next, `cd` into the `.xcarchive` because and then into its `dSYMs` dir. You should see some framework symbol files.
```
App-Release.3.6.32 2017-10-06 11.11.10.xcarchive $ cd dSYMs/
dSYMs $ ls -al
total 0
drwxr-xr-x  4 chump  CORP\Domain Users  136 Oct  6 11:12 .
drwxr-xr-x@ 6 chump  CORP\Domain Users  204 Oct  6 11:12 ..
drwxr-xr-x  3 chump  CORP\Domain Users  102 Sep 27 11:55 TealiumIOS.framework.dSYM
drwxr-xr-x  3 chump  CORP\Domain Users  102 Oct  6 11:12 App.app.dSYM
``` 
From there run the `dwarfdump` util like so:
 
```
dSYMs $ dwarfdump --uuid *
UUID: EA990B6D-CAF9-3B87-8D99-D04A4FA36537 (i386) TealiumIOS.framework.dSYM/Contents/Resources/DWARF/TealiumIOS
UUID: 1306BCB7-953D-3FC5-956E-40B85B8986A1 (x86_64) TealiumIOS.framework.dSYM/Contents/Resources/DWARF/TealiumIOS
UUID: CF845CCB-4E31-379F-8835-DA3B16734722 (armv7) TealiumIOS.framework.dSYM/Contents/Resources/DWARF/TealiumIOS
UUID: B353F154-B6B4-3FCA-AA18-C18E400EC139 (arm64) TealiumIOS.framework.dSYM/Contents/Resources/DWARF/TealiumIOS
UUID: 9EA964CB-58B8-32D4-9C28-E7569709073E (armv7) App.app.dSYM/Contents/Resources/DWARF/App
UUID: 2EB0C981-CD5F-313D-9E1F-ECA2C947CBA8 (arm64) App.app.dSYM/Contents/Resources/DWARF/App
```
In my case the two UUID’s mentioned by Apple are the ones that correspond to the slices of TealiumIOS framework that are build for `i386` and `x86_64` (which are commonly for the simulator) but are somehow getting bundled into our application’s Release config IPA.

In your case you might want to double-check that this is in-fact the issue rather than the dupe, similarly-named sub-spec Framework. These two things could be interrelated, as well. I'm still hunting!

**Comment by chefnobody** [comment]
Follow up. I just read the thread over here on mapbox: https://github.com/mapbox/mapbox-gl-native/issues/10137 that outlines this issue, exactly.

**Comment by dnkoutso** [comment]
Is this the same issue as https://github.com/CocoaPods/CocoaPods/issues/7111? If true then it should be fixed by https://github.com/CocoaPods/CocoaPods/pull/7112

**Comment by dnkoutso** [comment]
@kaosdg can you try latest master using Bundler and verify your issue is fixed?

**Comment by dnkoutso** [comment]
Closing for lack of inactivity.
