### ISSUE TITLE
RuntimeError - [Xcodeproj] Unknown object version.

### ISSUE THREAD

**Issue by 13553119978** [CocoaPods/CocoaPods#6991]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

> Before you start, are you using the latest CocoaPods release?
> A lot changes with Xcode releases that are not backwards compatible.
>
> Not an issue about the CocoaPods command line app? Please file an issue in the appropriate repo - https://github.com/CocoaPods
> Issues are for feature requests, and bugs; questions should go to Stack Overflow
>
> Using CocoaPods <= 0.39: http://blog.cocoapods.org/Sharding/
>
> Using Xcode 8: Requires CocoaPods 1.1.0 or above.
>
> Issue with Nanaimo not loading:
> Please run `[sudo] gem uninstall nanaimo` and remove all but the latest version.
>
> Issues with `pod search`? Try deleting your cache `rm -rf ~/Library/Caches/CocoaPods`first.

* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace this with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace this with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by infinZero** [comment]
Hi Tonshell 
I was also facing same problem since last three days, but its solution is pretty easy which Finally I configured within 5 minutes. 
lets move towards the solution.
Step 1. Open your Terminal.
and you are in your default users's Directory. 

Step 2. just write following command to update or install your pod
[sudo] gem install cocoapods

if that above command does not works, no needs to worry about, because you will be having sudo less gem in your mac machine. 

So after that try this command.

gem install cocoapods --user-install

this will install or updates latest version of pod in your current Users directory smoothly 

Remember, NO needs to step into or step out of any directory when you open your terminal very first time, because you'll be in your default user's directory very first time you open your terminal, 
Otherwise if you stepped in our stepped out any directory just close your terminal and reopen and to repeat step number 2.

Step 3.  Now move to your required project's directory and to install pod while using following command 
pod init

and after adding your required dependencies to your pod install it while using following command

pod install


please leave your comment if it works out....

**Comment by chaitanya-ramji** [comment]
Not working, I'm facing the same issues as above. Any fixes as yet?

**Comment by aodhol** [comment]
Same here

**Comment by parktimothy** [comment]
Has anyone found the fix for this.. I'm experiencing the same for 9.3 beta

**Comment by aodhol** [comment]
@segiddins are you able to use Cocoapods at all with Xcode 9.3 beta?

**Comment by segiddins** [comment]
@aodhol yes

**Comment by cochn** [comment]
@infinZero yes

**Comment by mattmega4** [comment]
I am still not able to use pods in my beta app

**Comment by aodhol** [comment]
Can you check that the Project Format of your Xcode project is set to Xcode
8.0-compatible rather than Xcode 9.3-compatible because I think Cocoapods
1.4.0 doesn't yet support that 'object version'.
