### ISSUE TITLE
Xcode Playground support "Couldn't lookup symbols"

### ISSUE THREAD

**Issue by emarashliev** [CocoaPods/CocoaPods#7371]
* [✅ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I have a playground in my project and trying to import a library installed through CocoaPods.
The playground is added into the target against I'm building.

## What did you expect to happen?
To execute playground code without errors.

## What happened instead?
The playground code is running and ends executing with the next error: 
```
Playground execution failed:

error: Couldn't lookup symbols:
  __T014ReceiptBankAPI16AllReceiptsQueryCACycfC
  __T014ReceiptBankAPI16AllReceiptsQueryC4DataV0A0V10__typenameSSfg
  __T014ReceiptBankAPI16AllReceiptsQueryC4DataV0A0VMa
  __T014ReceiptBankAPI16AllReceiptsQueryC6Apollo12GraphQLQueryAAWP
  __T014ReceiptBankAPI16AllReceiptsQueryCMa
  __T014ReceiptBankAPI16AllReceiptsQueryC4DataV8receiptsSayAE0A0VGSgfg
```
### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.3 (17D47)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-links       : 0.3.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
@emarashliev to my knowledge CocoaPods does not provide playground support.

**Comment by segiddins** [comment]
I'd have a look at https://github.com/neonichu/ThisCouldBeUsButYouPlaying

**Comment by emarashliev** [comment]
@dnkoutso why does not provide playground support?
Is there some serious reason for that?

**Comment by dnkoutso** [comment]
@emarashliev noone has spent the time to implement it! Luckily CocoaPods is open source so anyone should attempt to learn and try to implement new features or bug fixes.

You can start with this existing issue that discusses some proposed API https://github.com/CocoaPods/CocoaPods/issues/5334

I did not know Ruby or the CocoaPods codebase and learned it overtime to implement some of the latest features like test specs and script phases.

@emarashliev I am considering closing this issue as a dup of https://github.com/CocoaPods/CocoaPods/issues/5334 would you mind since its already tracked?

**Comment by emarashliev** [comment]
@dnkoutso sounds like a plan, thanks.
