### ISSUE TITLE
CocoaPods doesn't download Currency Library for me instead it downloads something else,

### ISSUE THREAD

**Issue by ABKasimy** [CocoaPods/CocoaPods#7400]
Last login: Sat Feb  3 12:29:42 on ttys000
ABs-Mac:~ ab$ cd /Users/ab/Desktop/Currency\ Converter 
ABs-Mac:Currency Converter ab$ ls
Currency Converter		Podfile
Currency Converter.xcodeproj
ABs-Mac:Currency Converter ab$ pod install
Analyzing dependencies
Setting up CocoaPods master repo
  $ /usr/bin/git clone https://github.com/CocoaPods/Specs.git master --progress
  Cloning into 'master'...

**Comment by orta** [comment]
CocoaPods needs to down the specs repo in order to resolve your dependencies, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
