### ISSUE TITLE
Counter-intuitive download strategy behavior when referencing a pod whose podspec resides in the library root

### ISSUE THREAD

**Issue by dmytrol** [CocoaPods/CocoaPods#7426]
🌈

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Installed a private pod containing a single vendored framework from a private podspec repo.
NB: The private pod's podspec specifies an http URL as the source of the pod contents.

Also FYI, "pod spec lint" did not report any errors about the spec except for a suggestion to use an https URL.

## What did you expect to happen?

The framework contained in the pod is copied to the xcode project after running "pod install" 

## What happened instead?

"pod install" did not report any errors besides a warning on defaulting to iOS 10 as the target platform.

The framework referenced in the podspec's "vendored_frameworks" attribute was **NOT** copied to the target xcode project. 

However, a readme file that resides in the pod's repository root but is **NOT** referenced by the podspec (the podspec does not contain any "source_files" entries at all - only a single "vendored_framework" entry) *does* get copied to the project's Pods/*pod_name* folder.

### My speculation about what happens

It looks like if a Podile references a pod by specifying its git repository URL and a branch name / commit ID, CocoaPods implicitly assumes that the pod contents should be retrieved from this very same repository (*effectively ignoring the podspec's "source" attribute*).

Then it could be that the download strategy CocoaPods applies in this case "sees" the readme file at the repository root and assumes this readme file is a part of the pod's contents (despite the podspec containing *no* "source_files" attributes at all). And, now that the vendored framework referenced by the podspec is stored elsewhere (namely, on a different Web server), the download strategy just skips it because it assumes that the whole pod contents should be downloaded from the specified repository's root.

I believe the Podfile guide does not explain this in sufficient detail, even if this is expected behavior.

## CocoaPods Environment

Will provide on Monday if relevant; not at my work Mac at the moment.

**Comment by orta** [comment]
CocoaPods' model is that the repo that holds the podspec contains the artifacts of the Pod. It's assumed that the Podspec is at the root of that project that contains the source/assets you're going to use. You can have many podspecs in that repo, which can cut up a project into many ways ( React Native does this for example ) but it's still the same assumption.

So to clarify, you'd want CocoaPods to first clone the repo that has a podspec, then to use the Podspec metadata which could declare the source code in another place? 

Personally, I don't think this is a good model to move to, mainly because it means if you fork any project you'd have to edit all the podspec metadata - I think that would be more confusing than this case.

**Comment by dnkoutso** [comment]
I also believe you can use `pod 'SomePod', :podspec => '...url/path'` that would accomplish what you want.

Your case is understood but as @orta said in the last paragraph.

Going to close as I do not think we will be changing something here and the potential workaround suggested above I think would do the trick for you.

Please feel free to respond here and we can re-open if the discussion proceeds into a change we can make.
