### ISSUE TITLE
“pod search --web «search text»” Command Pukes

### ISSUE THREAD

**Issue by capnslipp** [CocoaPods/CocoaPods#7702]
### Command

```
/usr/local/bin/pod search --web Funky
```

### Report

* What did you do?

Ran `pod search --web Funky`

* What did you expect to happen?

It would show me all available pods matching the search.

* What happened instead?

The error message came up with this template and links to search for pre-existing issues (didn't find any) and to create this issue.

### Stack

```
   CocoaPods : 1.5.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3 (9E145)
         Git : git version 2.17.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : macdownapp - https://github.com/MacDownApp/cocoapods-specs.git @ 3e095702c43af3cab55a5c843e23ca2022ae16ea
               master - https://github.com/CocoaPods/Specs.git @ a305cec4f0b3ad26cad3a433eab9382daa9b99a1
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Error

```
NoMethodError - undefined method `open!' for #<Pod::Command::Search:0x007f94f58ad180>
Did you mean?  open
/Library/Ruby/Gems/2.3.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:79:in `web_search'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:61:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by capnslipp** [comment]
Honestly, your “not my problem” attitude isn't appreciated.  And in this case, it's not my problem either— I don't use CocoaPods regularly _(Carthage is my jam)_ and whenever I do have to use CocoaPods for something, I'm reminded of the 2 main reasons why I'm better off without— CocoaPods has always been and still is buggy buggy buggy; and the CocoaPods developer community is fairly standoffish.

So… if you, as a project maintainer, want this issue fixed, then _you_ can go file an issue in the appropriate sub-project.  I've already done you a favor by following your tool's instructions and posting this here.  The only thing left for me to do is close this Terminal window where I was poking around in a CocoaPods-using project and get back to real work with tools that really work.

**Comment by orta** [comment]
Hey @capnslipp - thanks for the issue. Yeah, it can be tough to maintain a project with as many users as CocoaPods has in our spare time, and I'm sorry that we can tend to be curt occasionally. We get a lot of issues and comments per day, which can make it hard to take the time each deserves. 

In this case, I'll re-create your issue on the search repo.

**Comment by dnkoutso** [comment]
@capnslipp I'll admit I have become a bit "trigger happy" on closing issues, primarily because there are so many of them filed within this library. Apologies if this comes off harsh.

The ask to file the issue in the other repo is for organization purposes mostly. This repo is often used as a catch all for all issues related to CocoaPods. Second of all search is down which is a known issue (https://status.cocoapods.org/)

@capnslipp none of the maintainers gain anything from you using or not using CocoaPods. This is not a business and this is not a live customer support page.

**Comment by capnslipp** [comment]
I hear what you're saying, but I want to reiterate that I posted this issue as a courtesy to you, the maintainers.  I don't depend on this working, and I could've just shrugged off the error.

In terms of the maintainers not gaining anything from people using CocoaPods— I could not disagree with you more.  Sure, you're not gaining anything monetarily, but the continued use of CocoaPods by a community provides plenty of wealth to you in the forms of a sense of accomplishment, respect, appreciation, etc. _(roughly derived from a Ralph Waldo Emerson writing on the meaning of success)_.

Maintaining the project is a worthwhile pursuit to you, otherwise there would be no reason to do it.  I've unfortunately read many things from the CocoaPods maintainers over the years that have the opposite tone— that maintaining CocoaPods is a big, horrible chore and that you're doing the world this huge thankless favor.  So here's the deal: If you enjoy maintaining CocoaPods, keep doing it; if you don't, then don't.  But what ever you do, please don't try to guilt-trip users into thanking you profusely by complaining about the work you have the freedom to do or not to do.

**Comment by dnkoutso** [comment]
All that was asked was from you was to move this issue under a different repo, where it belongs, because of the fact that you as a user of any of these tools might not know the structure of the project. Nobody expects you to know them so I guided you on what to do. Do note that my initial comment has never been edited to make it appear more polite.

I think what mostly triggered you was the fact that the issue was actually closed to which I apologized for doing too fast and I should have waited until the issue was moved first. 

A more productive approach would have been for us to collaborate and discuss the issue together and get to the bottom of it so not only you and I benefit from a fix but the entire community. Maybe even help you grow into becoming a contributor or maintainer yourself.

Instead, a blown out of proportion reaction happened which was nearly insulting to all contributors of the project by calling out how their software sucks and your life is better without it.

This sort of one-way-benefit and convenient mentality of "I did you a favor for filing you an issue" is the exact opposite of what healthy open source collaboration should look like and this is exactly why you are receiving the "noone owes you anything" response. I think should read this: https://mikemcquaid.com/2018/03/19/open-source-maintainers-owe-you-nothing/

I am actually a very late state contributor to CocoaPods, I can attest to the fact that noone in the community I've met so far has had this grand impression of themselves that "they are doing the world a big favor". They are all very willing to help improve the library and introduce new features that help propel the community forward and they've done so in their own spare time.

I am curious, can you please describe your ideal scenario of what should have happened when you filed the issue? What would be different? It would be good for maintainers to learn from this.
