### ISSUE TITLE
Private pod with github private repo

### ISSUE THREAD

**Issue by ResulticksInc** [CocoaPods/CocoaPods#7764]
Hi, 
I have created podspec file which has private source url from github private repo. When i try to push this spec to cocoapods trunk i have got below error.

"Source code for your Pod was not accessible to CocoaPods Trunk. Is it a private repo or behind a username/password on http?"

I am Using CocoaPods 1.5.2 and Xcode 9.3.1. 

While validating the spec file i get only warning not an error. Later when i try to push then i get that error. 

Can anyone tell me how to solve this issue?

**Comment by zedixns** [comment]
Hi, you have to understand the difference between the private repo concept, and the trunk command(tool).

When you are using a private repo setup for personal development purposes, you have to use the ```
pod repo push REPO_NAME SPEC_NAME.podspec
```
More info in the docs: https://guides.cocoapods.org/making/private-cocoapods.html

But when you are ready to publish your project to the official CocoaPods repo, then you use trunk to publish and distribute your project. 

More info in the docs: https://guides.cocoapods.org/making/getting-setup-with-trunk.html

**Comment by zedixns** [comment]
Hi Siva,

The first link I gave you before tells you how to setup a private repo. And how to start using the private repo as your CocoPods Specs distribution. So please follow the instructions there.

Also, note that you can't hide the location of the framework files. Everything is public, so in order to enable your client to use your framework from your private repo, you have to give them a link, which they have to have access to in order to install the framework. And once they have access to the repo, they can install your framework and read the podspec file.

And finally, I must advise you to take this matter on to Stackoverflow, because this topic has nothing to do with actual CocaPods functionality in a sense of a bug report or an issue report.

**Comment by dnkoutso** [comment]
Private pods should be published using `pod repo push`. `trunk` command is used to publish to master repo.

This is not a CocoaPods library issue so far, so I am going to close. If it turns out to be then the issue will be re-opened.

**Comment by ResulticksInc** [comment]
Hi,

Thanks and we can close this issue.

**Comment by ResulticksInc** [comment]
Hi Vladimir,

I understand the problem. Thanks for resonse.

Thanks and Regards,

Siva
