### ISSUE TITLE
`pod lib lint` should warn if Swift files are included but swift_version isn't set

### ISSUE THREAD

**Issue by lilyball** [CocoaPods/CocoaPods#7778]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

As discussed in #7770 we should probably emit a warning during `pod lib lint` if the pod contains any Swift files but does not use the `swift_version` DSL.

**Comment by dnkoutso** [comment]
@kballard this might be covered by https://github.com/CocoaPods/CocoaPods/issues/7436 which was set in 2.0.0 because we want to delete the `.swift-version` file and the `lint` parameter

**Comment by dnkoutso** [comment]
I also think lint today warns and there is messaging to ask the author to use `swift_version` DSL but its not an error...as #7436 says it should be.

**Comment by kballard** [comment]
The current released version of CocoaPods does not warn on lint, otherwise I would have added `swift_version` to my existing Pods a while ago. I don't know about current master though.

**Comment by dnkoutso** [comment]
huh weird. I will check again, thanks.

**Comment by kballard** [comment]
I did have a `.swift-version` file, it's possible that there is a lint and it simply doesn't fire if you have that file (but if so, that should be changed).

**Comment by dnkoutso** [comment]
@jshier why are these two contingent? AFAIK this is just replacing using the file mechanism with the DSL mechanism and helping pod authors transition to the latter one.

**Comment by jshier** [comment]
The proposed warning would trigger a warning "if the pod contains any Swift files but does not use the `swift_version` DSL". This DSL isn't yet usable by any project that supports multiple versions of Swift, and so would create warnings for those projects (like Alamofire). So yes, I'm opposed to a warning I'd have to ignore when publishing Alamofire until `swift_version` is flexible enough.

**Comment by kballard** [comment]
What exactly would specifying multiple `swift_version`s do? Unless CocoaPods knows exactly what Swift versions are supported by what Xcode versions, CocoaPods wouldn't have any way of selecting the version to use for the `SWIFT_VERSION` build setting. And if you're suggesting that CocoaPods *should* know what versions of Swift are supported by what versions of Xcode, that seems like it would be rather problematic (not only would this be a maintenance burden, but it also means anyone who upgrades Xcode without updating CocoaPods would break this functionality).

**Comment by kballard** [comment]
Perhaps the pod itself could specify something like “with Xcode 9.2, use Swift version 3.2”. In that case we’d still have the top-level `swift_version` to define what to use if not otherwise overridden for the current Xcode.

**Comment by mxcl** [comment]
I deliberately removed `swift_version` from my Podfile since I support Swift 3.1 through 4.2 with PromiseKit and specifying this was preventing that support.

Like, you can force this, but maybe you should allow a range of swift-versions first. There's a ticket for that which I was trying to find when I found this. I'll edit when I find it.

**Comment by dnkoutso** [comment]
@lilyball is this an issue anymore with 1.7.0.beta.1 and multiple Swift version support?

**Comment by dnkoutso** [comment]
This is sufficiently covered in 1.7.x.

If a pod uses Swift but specifies no `--swift-version` or `swift_versions` DSL or `.swift-version` file then a warning is emitted that a default version was used and the user should specify the `swift_versions` DSL attribute in their podspec.

Additionally if the user is validating a pod with a `--swift-version` parameter or `.swift-version` file that is *not* present in the `swift_versions` DSL an error is presented that the version being validated must be specified in the list of `swift_versions` DSL.

Lastly users are warned if `.swift-version` file is used and no DSL is presented in order to help them migrate over.

For now going to close as sufficient coverage here.
