### ISSUE TITLE
error: property with 'retain (or strong)' attribute must be of object type

### ISSUE THREAD

**Issue by RPGLiker** [CocoaPods/CocoaPods#7837]
# Report

## What did you do?

I have packaged a tool class based on AFNetworking and YYCache. I want to upload it to cocoapods. When I execute `pod spec lint`, it generates an error. Here is my podspec file:
![2018-06-15 10 18 41](https://user-images.githubusercontent.com/20294470/41447206-afb350de-7086-11e8-9d98-0da6f7bdf657.png)

This is the error of the terminal:
![4a1ee04c-f63a-4a57-b582-2ed74c924738](https://user-images.githubusercontent.com/20294470/41447211-b4a962f4-7086-11e8-9668-51343699037b.png)

I looked at the AFNetworking source here, but I don't think it has any problems. What should I do? Thank you.

## What did you expect to happen?

I hope I can upload my tools to cocoapods.

## What happened instead?

As shown above

## CocoaPods Environment

cocoapods 1.5.0
xcode 9.3

## Project that demonstrates the issue

https://github.com/RPGLiker/UCNetworking

Thanks.

**Comment by dnkoutso** [comment]
It seems you have nested `Pods/` folder inside UCNetworking/UCNetworking which is picking up everything else including AFNetworking twice because your podspec has:
```ruby
  s.source_files  = "UCNetworking/**/*.{h,m}"
```

Please remove the remaining files or change your podspec.

Also these types of questions are better to be asked in StackOverflow under `cocoapods` tag.
