### ISSUE TITLE
Make library version text more visible

### ISSUE THREAD

**Issue by anjmao** [CocoaPods/CocoaPods#7996]
Hi, I'm new to CocaPods and I spent ~5min trying to find SwiftGrpc package version. Then I called other developer and showed him this "user friendly" page and he spent even more time trying to find it 😆 There are screens on which version is not visible at all. Make it at least `#555` color. Thanks 👍  

![image](https://user-images.githubusercontent.com/3028012/43944659-60be82d6-9c88-11e8-9c04-61db7a6258a9.png)

**Comment by orta** [comment]
Hi there, this is an issue that should be the cocoa pods website repo ( cocoapods/cocoapods.org ), this repo is only for CocoaPods the command line tool - and it only is for bug reports and feature requests. Please re-create your issue on the right repo so that the correct people will be highlighted to it 👍
