### ISSUE TITLE
Multiple Authors in PodSpec

### ISSUE THREAD

**Issue by Vinz1911** [CocoaPods/CocoaPods#8086]
I want to know what the correct podspec syntax is, to add multiple authors to the same podspec file ? I can't find any useful information about ?!

**Comment by amorde** [comment]
Hello @Vinz1911,

There is a guide for the Podspec (and this specific attribute) here: https://guides.cocoapods.org/syntax/podspec.html#authors

I am going to close this since I think the documentation for that attribute should fit your needs but if you think there's something that could be improved, please let us know :)

**Comment by amorde** [comment]
You can also see the source for that documentation here: https://github.com/CocoaPods/guides.cocoapods.org

**Comment by Vinz1911** [comment]
perfect! that's exact what i looking for, thanks 👍
