### ISSUE TITLE
pod update broken due to issue with Firebase/Core dependencies

### ISSUE THREAD

**Issue by jakubgs** [CocoaPods/CocoaPods#8110]
It seems like a bug was intrduced somewhere in this repo that breaks the dependency tree for `Firebase/Core`. Every time I run `pod update` I get the same error:
```
...
[!] CocoaPods could not find compatible versions for pod "Firebase/Core":
  In Podfile:
    Firebase/Core

Specs satisfying the `Firebase/Core` dependency were found, but they required a higher minimum deployment target.
CocoaPods could not find compatible versions for pod "GoogleUtilities/MethodSwizzler":
  In Podfile:
    Firebase/Core was resolved to 5.8.0, which depends on
      FirebaseAnalytics (= 5.1.2) was resolved to 5.1.2, which depends on
        GoogleUtilities/MethodSwizzler (~> 5.2.0)

Specs satisfying the `GoogleUtilities/MethodSwizzler (~> 5.2.0)` dependency were found, but they required a higher minimum deployment target.
```
This happens on many different machines.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by paulb777** [comment]
We're tracking a workaround for this Firebase repo at https://github.com/firebase/firebase-ios-sdk/issues/1845. It does look like the root cause is a CocoaPods issue of failing to properly consolidate subspec versions, since the workaround is to force a version that CocoaPods should determine on its own. I'll try to provide more CocoaPods specific info later.

**Comment by jakubgs** [comment]
Thanks for the response @paulb777 , I felt stupid for a second there.

**Comment by muthukrishnanOCS** [comment]
I have the same issue. please provide the solution

**Comment by paulb777** [comment]
@muthukrishnanOCS Do a `pod update`. Firebase worked prevented this bug from arising with the 5.8.1 release.

I still plan to investigate the CocoaPods issue, but in the meantime, it shouldn't impact Firebase usage with the latest releases.

**Comment by paulb777** [comment]
If I backup the master spec checkout (`git checkout ec42bc82c802211830f43a01f4243ca8357061e4`) and wipe some caches, I still reproduce the issue with 1.5.3.  

With CocoaPods master, the pod install succeeds with lots of duplicate UUID warnings since two versions of `GoogleUtilities` get installed.  Versions 1.3.2 and 5.3.0 are installed instead of the correct 5.2.3.

Any suggestions about how to debug?

**Comment by Carpemeid** [comment]
I may be mistaken with this, but maybe this https://github.com/CocoaPods/CocoaPods/issues/6540 is related. Excuse me if it's not.

Specifically "which means different versions of the pod were actually installed. Still don't understand how that's possible, as no other pod had a dependency on it, but probably a podspec has 10.0 requirement, while my Xcode targets have 10.2."
