### ISSUE TITLE
pod install fails without error when installing OpenSSL-OSX

### ISSUE THREAD

**Issue by rurza** [CocoaPods/CocoaPods#8152]
macOS: 10.14
Xcode 10
Cocoapods: 1.5.3

```
Installing OpenSSL-OSX (1.0.211)
[!] /bin/bash -c 
set -e
VERSION="1.0.2j"
 SDKVERSION=`xcrun --sdk macosx --show-sdk-version 2> /dev/null`
 MIN_SDK_VERSION="10.7"

 BASEPATH="${PWD}"
 CURRENTPATH="${TMPDIR}/openssl"
 ARCHS="i386 x86_64"
 DEVELOPER=`xcode-select -print-path`
 PLATFORM="MacOSX"

 mkdir -p "${CURRENTPATH}"
 mkdir -p "${CURRENTPATH}/bin"

 curl -L "https://www.openssl.org/source/openssl-${VERSION}.tar.gz" -o file.tgz
 cp "file.tgz" "${CURRENTPATH}/file.tgz"
 cd "${CURRENTPATH}"
 tar -xzf file.tgz
 cd "openssl-${VERSION}"

 for ARCH in ${ARCHS}
 do
 
   if [ "${ARCH}" == "i386" ];
   then
       CONFIGURE_FOR="darwin-i386-cc"
   elif [ "${ARCH}" == "x86_64" ];
   then
CONFIGURE_FOR="darwin64-x86_64-cc"
   fi
   export CROSS_TOP="${DEVELOPER}/Platforms/${PLATFORM}.platform/Developer"
   export CROSS_SDK="${PLATFORM}${SDKVERSION}.sdk"

   echo "Building openssl-${VERSION} for ${PLATFORM} ${SDKVERSION} ${ARCH}"
   echo "Please stand by..."

   export CC="${DEVELOPER}/usr/bin/gcc -arch ${ARCH} -mmacosx-version-min=${MIN_SDK_VERSION}"
   mkdir -p "${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk"
   LOG="${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk/build-openssl-${VERSION}.log"

   LIPO_LIBSSL="${LIPO_LIBSSL} ${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk/lib/libssl.a"
   LIPO_LIBCRYPTO="${LIPO_LIBCRYPTO} ${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk/lib/libcrypto.a"

   ./Configure ${CONFIGURE_FOR} --openssldir="${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk" > "${LOG}" 2>&1
   sed -ie "s!^CFLAG=!CFLAG=-isysroot ${CROSS_TOP}/SDKs/${CROSS_SDK} !" "Makefile"

   make >> "${LOG}" 2>&1
   make all install_sw >> "${LOG}" 2>&1
   make clean >> "${LOG}" 2>&1
 done


 echo "Build library..."
 rm -rf "${BASEPATH}/lib/"
 mkdir -p "${BASEPATH}/lib/"
 lipo -create ${LIPO_LIBSSL}    -output "${BASEPATH}/lib/libssl.a"
 lipo -create ${LIPO_LIBCRYPTO} -output "${BASEPATH}/lib/libcrypto.a"

 echo "Copying headers..."
 rm -rf "${BASEPATH}/opensslIncludes/"
 mkdir -p "${BASEPATH}/opensslIncludes/"
 cp -RL "${CURRENTPATH}/openssl-${VERSION}/include/openssl" "${BASEPATH}/opensslIncludes/"

 cd "${BASEPATH}"
 echo "Building done."

 echo "Cleaning up..."
 rm -rf "${CURRENTPATH}"
 echo "Done."

Building openssl-1.0.2j for MacOSX 10.14 i386
Please stand by...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5183k  100 5183k    0     0   752k      0  0:00:06  0:00:06 --:--:--  515k


 2018-10-02 16:54:49 ⌚  rurzabuk-pro in ~/Developer/NepTunes
```

**Comment by dnkoutso** [comment]
This does not appear to be a CocoaPods library issue, rather a network issue, potentially during the `prepare_command` of `OpenSSL-OSX` pod.

My recommendation is ask through StackOverflow under `cocoapods` tag or contact the author.

I will preemptively close this one as there isn't much to do but if we do identify this is a library issue *I will* re-open this.

**Comment by ClegeJJ** [comment]
i have same problem.

**Comment by ClegeJJ** [comment]
Installing OpenSSL-XM (1.0.210.1)
[!] /bin/bash -c
set -e
VERSION="1.0.2j"
SDKVERSION=`xcrun --sdk iphoneos --show-sdk-version 2> /dev/null`
MIN_SDK_VERSION_FLAG="-miphoneos-version-min=7.0"

BASEPATH="${PWD}"
CURRENTPATH="/tmp/openssl"
#CURRENTPATH="${PWD}/tmp"

ARCHS="i386 x86_64 armv7 armv7s arm64"
DEVELOPER=`xcode-select -print-path`


mkdir -p "${CURRENTPATH}"
mkdir -p "${CURRENTPATH}/bin"

cp -rf "${BASEPATH}/" "${CURRENTPATH}/openssl-${VERSION}"
#cp "file.tgz" "${CURRENTPATH}/file.tgz"
cd "${CURRENTPATH}"
#tar -xzf file.tgz
cd "openssl-${VERSION}"

for ARCH in ${ARCHS}
do
  CONFIGURE_FOR="iphoneos-cross"

  if [ "${ARCH}" == "i386" ] || [ "${ARCH}" == "x86_64" ] ;
  then
    PLATFORM="iPhoneSimulator"
    if [ "${ARCH}" == "x86_64" ] ;
    then
      CONFIGURE_FOR="darwin64-x86_64-cc"
    fi
  else
    sed -ie "s!static volatile sig_atomic_t intr_signal;!static volatile intr_signal;!" "crypto/ui/ui_openssl.c"
    PLATFORM="iPhoneOS"
  fi

  export CROSS_TOP="${DEVELOPER}/Platforms/${PLATFORM}.platform/Developer"
  export CROSS_SDK="${PLATFORM}${SDKVERSION}.sdk"

  echo "Building openssl-${VERSION} for ${PLATFORM} ${SDKVERSION} ${ARCH}"
  echo "Please stand by..."

  export CC="${DEVELOPER}/usr/bin/gcc -arch ${ARCH} ${MIN_SDK_VERSION_FLAG}"
  mkdir -p "${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk"
  LOG="${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk/build-openssl-${VERSION}.log"

  LIPO_LIBSSL="${LIPO_LIBSSL} ${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk/lib/libssl.a"
  LIPO_LIBCRYPTO="${LIPO_LIBCRYPTO} ${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk/lib/libcrypto.a"

  ./Configure ${CONFIGURE_FOR} --openssldir="${CURRENTPATH}/bin/${PLATFORM}${SDKVERSION}-${ARCH}.sdk" > "${LOG}" 2>&1
  sed -ie "s!^CFLAG=!CFLAG=-isysroot ${CROSS_TOP}/SDKs/${CROSS_SDK} !" "Makefile"

  make >> "${LOG}" 2>&1
  make all install_sw >> "${LOG}" 2>&1
  make clean >> "${LOG}" 2>&1
done


echo "Build library..."
rm -rf "${BASEPATH}/lib/"
mkdir -p "${BASEPATH}/lib/"
lipo -create ${LIPO_LIBSSL}    -output "${BASEPATH}/lib/libssl.a"
lipo -create ${LIPO_LIBCRYPTO} -output "${BASEPATH}/lib/libcrypto.a"

echo "Copying headers..."
rm -rf "${BASEPATH}/opensslIncludes/"
mkdir -p "${BASEPATH}/opensslIncludes/"
cp -RL "${CURRENTPATH}/openssl-${VERSION}/include/openssl" "${BASEPATH}/opensslIncludes/"

cd "${BASEPATH}"
echo "Building done."

echo "Cleaning up..."
rm -rf "${CURRENTPATH}"
echo "Done."

Building openssl-1.0.2j for iPhoneSimulator 12.1 i386
Please stand by...


[!] Smart quotes were detected and ignored in your Podfile. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

[!] Automatically assigning platform `ios` with version `9.0` on target `jyxb_app` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
➜  jyxb git:(examSwift) ✗ pod search OpenSSL-XM
Ignoring oj-3.6.4 because its extensions are not built. Try: gem pristine oj --version 3.6.4
Ignoring unf_ext-0.0.7.5 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.5
➜  jyxb git:(examSwift) ✗ podUpdate
Ignoring oj-3.6.4 because its extensions are not built. Try: gem pristine oj --version 3.6.4
Ignoring unf_ext-0.0.7.5 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.5
Updating spec repo `jiayouxueba-xyspecs`
  $ /usr/bin/git -C /Users/kougakushou/.cocoapods/repos/jiayouxueba-xyspecs fetch origin --progress
  $ /usr/bin/git -C /Users/kougakushou/.cocoapods/repos/jiayouxueba-xyspecs rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/kougakushou/.cocoapods/repos/jiayouxueba-xyspecs reset --hard origin/master
  HEAD is now at 8dcca84 [Update] XQSRegLoginModule (2.4.5.2)
Ignoring oj-3.6.4 because its extensions are not built. Try: gem pristine oj --version 3.6.4
Ignoring unf_ext-0.0.7.5 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.5
Update all pods
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `ReactComponent/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `ReactComponent/node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `GLog` from `ReactComponent/node_modules/react-native/third-party-podspecs/GLog.podspec`
Fetching podspec for `JYXBConfigCenter-swift` from `~/component/JYXBConfigCenter-swift`
[!] No podspec found for `JYXBConfigCenter-swift` in `~/component/JYXBConfigCenter-swift`

[!] Smart quotes were detected and ignored in your Podfile. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

[!] Automatically assigning platform `ios` with version `9.0` on target `jyxb_app` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.



This is logs.

**Comment by IntractableQuery** [comment]
Agree that it is probably a network issue. I ctrl+c'd out of the `pod install` process, then subsequent attempts to install failed in this way. On Mac OS X.

To fix, I deleted `/tmp/openssl`, which I spotted when running `pod install --verbose`. This seems to be a caching directory that I probably corrupted by ending installation early. Deleting allowed me to reinitiate `pod install` without this error.

**Comment by ilter** [comment]
Hey, I faced with the issue. In my case selection of Command line tools from Xcode preferences solved. 

```
SDKVERSION=xcrun --sdk macosx --show-sdk-version 2> /dev/null
 MIN_SDK_VERSION="10.7"
```
 
If you check this part, open ssl needs to have `xcrun` thats why you should select **command line tools.** It can be unselected after some XCode updates or packages etc

```
Xcode > Preferences > Locations > Command Line Tools -> Select the Xcode version
```
