### ISSUE TITLE
Siri Intent support

### ISSUE THREAD

**Issue by 0x5e** [CocoaPods/CocoaPods#8183]
Hi guys, we are trying to implement siri shortcuts and create a pod what import `XXXIntent.intentdefinition` as source_files and resources.
During the compile, Xcode generated a `XXXIntent.h` to use. But I can't import this header file from app or app extension or other pod.
Is there any solution? Thanks :)

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by 0x5e** [comment]
@orta Sorry I didn't make it clear, I'm requesting a feature for Xcode 10 Siri Intent support. At present `. intentdefinition` can't be used in pod correctly. The automatically generated header file can't be specified in `.podspec` so there's no way to import it. I have to copy it from derived data folder manually every time intentdefinition edited.

**Comment by dnkoutso** [comment]
@0x5e is it adding that here https://github.com/CocoaPods/Xcodeproj/pull/598/files#diff-2fbe57544f33c804869fe7b12f1728eaR419?

**Comment by 0x5e** [comment]
@dnkoutso .intentdefinition is not a header file, it is a xml

[SimpleApp.zip](https://github.com/CocoaPods/CocoaPods/files/2475101/SimpleApp.zip)

Here's a simple example include 2 intentdefinition file, one in app and one in pod. without `use_frameworks!` in Podfile, the intentdefinition file in pod can't import.

**Comment by dnkoutso** [comment]
@0x5e I am not sure what you are trying to do works. I just created a sample static library in your project that does not use CocoaPods and moved the `Intents.intentdefinition` file into it and removed it from `SampleApp`. I was unable to `#import "GoHomeIntent.h"` again which is the same as happens when you use the one from a pod.

I don't think what you are asking is supported by Xcode but I am not very familiar with `*.intentdefinition` files so I am unsure if Xcode provides any ways to access those generated files from other targets.

**Comment by dnkoutso** [comment]
See this https://forums.developer.apple.com/thread/106899 which you can achieve with `user_target.xcconfig` or `pod_target_xcconfig`

**Comment by niyaoyao** [comment]
Have you solve this problem? @0x5e 

I've had a similar problem in mixed swift+objc project with cocoapods.
