### ISSUE TITLE
Feature request: Specify depth while firing pod setup

### ISSUE THREAD

**Issue by annanay25** [CocoaPods/CocoaPods#8343]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
pod setup 

ℹ Please replace these two lines with what you expected to happen.  
When cloning the git repo `https://github.com/CocoaPods/Specs.git`, the cli should give an option to specify 'depth' of the repo. Unnecessarily downloading the entire repo for a developer seems overkill.

ℹ Please replace these two lines with of what happened instead.  
The CLI downloads the repo with its full history.

ℹ Please replace these two lines with the output of `pod env`.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G2112)
       Xcode : 10.1 (10B61)
         Git : git version 2.18.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : 
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

**Comment by amorde** [comment]
We intentionally clone the entire repo as it results in less server load for Github - we used to do shallow clones, but that made subsequent fetches much more taxing on their servers.

You can read more details about that here: https://blog.cocoapods.org/Master-Spec-Repo-Rate-Limiting-Post-Mortem/ and here: https://github.com/CocoaPods/CocoaPods/issues/4989

There is work being done to improve this so that CocoaPods users don't have to download the entire spec repo - you can check it out here: https://github.com/CocoaPods/CocoaPods/issues/8268

Given that, I think it's unlikely we would add this feature to `pod setup` but I'm not against it

**Comment by igor-makarov** [comment]
PRs #8280 & [Core#469](https://github.com/CocoaPods/Core/pull/469) were merged into master on both repos.  
To take advantage of CDN-based spec repo do the following:
* Use a Gemfile and get the latest `cocoapods` and `cocoapods-core` gems from master.
* On command line: `bundle exec pod repo add-cdn jsDelivr-Specs "https://cdn.jsdelivr.net/cocoa/" `
* In your Podfile: `source "https://cdn.jsdelivr.net/cocoa/" `
* If you already have a Podfile.lock replace the `SPEC REPOS` key there as well - there's a bug that prevents it from auto-updating.
