### ISSUE TITLE
Header search paths aren't handled well when new generate_multiple_pod_projects: true specified

### ISSUE THREAD

**Issue by igor-makarov** [CocoaPods/CocoaPods#8525]
* [💚] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Made a demo repo build [here](https://travis-ci.org/igor-makarov/DemoPodHeaderSearchPaths/builds/495001421)  

## What did you expect to happen?

Build success

## What happened instead?

Build failed

## CocoaPods Environment

See build

## Project that demonstrates the issue

https://travis-ci.org/igor-makarov/DemoPodHeaderSearchPaths/builds/495001421

**Comment by igor-makarov** [comment]
I've updated the description above with a more current demo build that includes a comparison between `generate_multiple_pod_projects=true` and `generate_multiple_pod_projects=false` runs.

**Comment by sebastianv1** [comment]
The issue is actually due to bad header imports in the `BraintreeDropIn` library.
The xcconfigs with `generate_multiple_pod_projects` on or off is the exact same:

```
CONFIGURATION_BUILD_DIR = ${PODS_CONFIGURATION_BUILD_DIR}/BraintreeDropIn
FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_CONFIGURATION_BUILD_DIR}/Braintree"
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
OTHER_LDFLAGS = $(inherited) -framework "UIKit" -weak_framework "Contacts" -weak_framework "SafariServices"
PODS_BUILD_DIR = ${BUILD_DIR}
PODS_CONFIGURATION_BUILD_DIR = ${PODS_BUILD_DIR}/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_ROOT = ${SRCROOT}
PODS_TARGET_SRCROOT = ${PODS_ROOT}/BraintreeDropIn
PRODUCT_BUNDLE_IDENTIFIER = org.cocoapods.${PRODUCT_NAME:rfc1034identifier}
SKIP_INSTALL = YES
```

If we look at one of the compiler errors, we can see that it was working without multiple pods projects because it was picking up the quote imports through the Xcode generated project header map.
```objective-c
#if __has_include("BraintreePaymentFlow.h")
#import "BraintreePaymentFlow.h"
#else
#import <BraintreePaymentFlow/BraintreePaymentFlow.h>
#endif
```
The import `#import <BraintreePaymentFlow/BraintreePaymentFlow.h>` is actually incorrect as there is no framework named `BraintreePaymentFlow` but instead just `Braintree` since that is the root spec name. `BraintreePaymentFlow` is just a subspec.

It doesn't appear to be an issue with the `generate_multiple_pod_projects` option, but I imagine many projects might run into this issue as well when flipping the flag. Do you think we should call this out in the blog post or some other documentation @dnkoutso ?

**Comment by dnkoutso** [comment]
We can yes!

**Comment by dnkoutso** [comment]
@igor-makarov seems like we should close this?

**Comment by igor-makarov** [comment]
There are lots of pods that have these issues. I'm not sure this sort of compatibility break is a good idea.

Loose header importing is the norm in iOS development, however flawed the practice may be.

I think that this can be solved in CP by adding some search paths to the target config and nobody will be hurt by it.

**Comment by dnkoutso** [comment]
I believe we discussed this offline and we added a note in the blog post about expecting this to happen. 

Should this be closed?

**Comment by igor-makarov** [comment]
I suppose so, I'm still not sure FB would fix their SDK 😕
