### ISSUE TITLE
[Feature] generate lockfile  without download and install pods

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#8579]
I need a service to get the dependency in my project. And I must run the `pod install` to update the lockfile, but the `pod install` will cost very long time to download and generate the project.

Have any way to only generate the lockfile without download and install dependencies? NOTE: not just show the dependency graph.

**Comment by dnkoutso** [comment]
Do not know from top of my head but please ask StackOverflow for this under `cocoapods` tag.

**Comment by viceice** [comment]
@dnkoutso We need such a functionallity for our [renovate](/renovatebot/renovate) bot.

Currently we will run `pod install` to update the lockfile, which works most of the time.
But now we have a problem (see linked issue).
We can't update the lockfile any longer, because a [realm](https://github.com/realm/realm-cocoa) dependency needs xcode in prepare_command, which is not available on our linux based docker containers.
So we are looking for a solution to only update the lockfile without regenerating the `Pods` directory.
I also didn't find any solution on [StackOverflow](https://stackoverflow.com/search?tab=Relevance&pagesize=50&q=cocoapods%20lockfile)

**Comment by jpolo** [comment]
I agree with @viceice . We identified this issue as a great time saver if it was solved. Launching the pod install manually on each MR, validate, push, etc can take around 10min. Multiplied by the number of MR  each day and it is possible to see the potential of this feature.
