### ISSUE TITLE
Hide subproject dependencies from main app

### ISSUE THREAD

**Issue by inforeqd512** [CocoaPods/CocoaPods#8656]
This is more of a question 
if I have an xcode project for the main app, with a sub project for the dynamic Xcode framework Framework1. Framework1 is embedded in MainApp (General section)

     MainApp.xcodeproj
          |-subproject Framework1.xcodeproject
               |-Framework1.framework
                    |-pod Shimmer

How can i make the podfile that only Framework1 can use the Shimmer pod and not the MainApp? That way the dependencies of framework are hidden from main app

**Comment by sebastianv1** [comment]
I don't believe this is possible since the final app executable (`MainApp`) must link and embed all dynamic framework dependencies, including transitive.

**Comment by inforeqd512** [comment]
thanks for the reply. Looks like there is no way of hiding dependencies if the dependencies are dymanic frameworks.

Was wondering if the dependencies are static libraries, would the hiding be possible?

**Comment by sebastianv1** [comment]
@inforeqd512 It wouldn't. Every dependency needs to be linked, but with static libraries you wouldn't need to embed anything.

**Comment by mmdock** [comment]
@sebastianv1 since this hasn't been closed, i am gonna just jump right in and ask something. 

I believe this is the exact same question, but just confirming.

I want to update SDWebImage from 4.4.6 to a 5.x.x release.

However, because I use another pod, AppBoy, that has dependency on SDWebImage/GIF that has to be a 4.x.x release, there is no way for me to update my personal usage of SDWebImage to 5.x.x until that third party pod update's its' dependency.   Is that correct?
