### ISSUE TITLE
ERROR | [iOS] unknown: Encountered an unknown error (Pod::DSLError) during validation.

### ISSUE THREAD

**Issue by VishalVerve** [CocoaPods/CocoaPods#8789]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ I'm trying to update my pod but i encountered this error  
e.g. Run `pod repo push FirebasePod FirebaseUtility.podspec --verbose --allow-warnings`

## What did you expect to happen?

ℹ Expected the pod to be updated with a success message indicating the new version in the terminal.

## What happened instead?

ℹ Update failed with this stack trace
```
 -> FirebaseUtility (1.0.2)
    - ERROR | [iOS] unknown: Encountered an unknown error (Pod::DSLError
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.rc.1/lib/cocoapods-core/specification.rb:794:in `rescue in _eval_podspec'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.rc.1/lib/cocoapods-core/specification.rb:785:in `_eval_podspec'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.rc.1/lib/cocoapods-core/specification.rb:695:in `block in from_string'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.rc.1/lib/cocoapods-core/specification.rb:692:in `chdir'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.rc.1/lib/cocoapods-core/specification.rb:692:in `from_string'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.rc.1/lib/cocoapods-core/specification.rb:675:in `from_file'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/sandbox/podspec_finder.rb:15:in `block in podspecs'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/sandbox/podspec_finder.rb:14:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/sandbox/podspec_finder.rb:14:in `podspecs'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/downloader.rb:82:in `download_request'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/downloader/cache.rb:171:in `download'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/downloader/cache.rb:154:in `block in uncached_pod'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/downloader.rb:42:in `download'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/installer/pod_source_installer.rb:109:in `download_source'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/installer/pod_source_installer.rb:62:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/installer.rb:545:in `install_source_of_pod'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/installer.rb:496:in `block (2 levels) in install_pod_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/installer.rb:495:in `block in install_pod_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/installer.rb:478:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/installer.rb:478:in `install_pod_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/installer.rb:235:in `block in download_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/installer.rb:234:in `download_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/validator.rb:550:in `block in download_pod'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/validator.rb:550:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/validator.rb:550:in `download_pod'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/validator.rb:383:in `block in perform_extensive_analysis'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/validator.rb:377:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/validator.rb:377:in `perform_extensive_analysis'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/validator.rb:128:in `validate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/command/repo/push.rb:142:in `block in validate_podspec_files'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/command/repo/push.rb:132:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/command/repo/push.rb:132:in `validate_podspec_files'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/command/repo/push.rb:77:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
) during validation.

[!] The `FirebaseUtility.podspec` specification does not validate.

/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/command/repo/push.rb:147:in `block in validate_podspec_files'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/command/repo/push.rb:132:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/command/repo/push.rb:132:in `validate_podspec_files'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/command/repo/push.rb:77:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.rc.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```
## CocoaPods Environment

ℹ Here is the CocoaPods Environment.

### Stack

```
   CocoaPods : 1.7.0.rc.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 10.1 (10B61)
         Git : git version 2.10.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : FirebasePod - https://gitlab.com/vishaln.verve/firebasepod.git @ 4695f8b20c4ca509be467a774f4161e2a0d6f31c
               master - https://github.com/CocoaPods/Specs.git @ ffa6d6424c4d208f416702cb90025c291c509f41
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

ℹ Here is my podspecs file
```
#
# Be sure to run `pod lib lint FirebaseUtility.podspec' to ensure this is a
# valid spec before submitting.
#
# Any lines starting with a # are optional, but their use is encouraged
# To learn more about a Podspec see https://guides.cocoapods.org/syntax/podspec.html
#

Pod::Spec.new do |s|
  s.name             = 'FirebaseUtility'
  s.version          = '1.0.2'
  s.summary          = 'This is a firebase chat with some structure base FirebaseUtility.'

# This description is used to generate tags and improve search results.
#   * Think: What does it do? Why did you write it? What is the focus?
#   * Try to keep it short, snappy and to the point.
#   * Write the description between the DESC delimiters below.
#   * Finally, don't worry about the indent, CocoaPods strips it!

  s.description      = <<-DESC
This is a firebase chat own separate classes with some structure base FirebaseUtility.
                       DESC

  s.homepage         = 'https://gitlab.com/vishaln.verve/FirebaseUtility'
  # s.screenshots     = 'www.example.com/screenshots_1', 'www.example.com/screenshots_2'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'vishal' => 'vishaln.verve@gmail.com' }
  s.source           = { :git => 'https://gitlab.com/vishaln.verve/FirebaseUtility.git', :tag => s.version.to_s }
  # s.social_media_url = 'https://twitter.com/<TWITTER_USERNAME>'

  s.ios.deployment_target = '8.0'
  s.requires_arc = true
  s.static_framework = true
  s.swift_version = '4.2'
  
  s.frameworks = 'UIKit','Foundation', 'AssetsLibrary', 'Photos'
  #s.source_files = 'FirebaseUtility/Classes/**/*'

  s.dependency 'Firebase', '~> 6.0.0'
  s.dependency 'FirebaseCore', '~> 6.0.0'
  s.dependency 'FirebaseDatabase', '~> 6.0.0'
  s.dependency 'FirebaseFirestore', '~> 1.3.0'
  s.dependency 'FirebaseAuth', '~> 6.0.0'
  s.dependency 'FirebaseMessaging', '~> 4.0.0'
  s.dependency 'FirebaseStorage', '~> 3.2.0'
  s.dependency 'OneSignal', '~> 2.10.0'
  
  
  s.subspec 'Collection' do |cs|
      cs.source_files = 'FirebaseUtility/Classes/Collection/**/*.{swift}'
  end
  

  s.subspec 'DataSource' do |ds|
      ds.source_files = 'FirebaseUtility/Classes/DataSource/**/*.{swift}'
     
  end
  
  s.subspec 'Extensions' do |es|
      es.source_files = 'FirebaseUtility/Classes/Extensions/**/*.{swift}'
  end
  
  s.subspec 'FirebaseModel' do |fs|
      fs.source_files = 'FirebaseUtility/Classes/FirebaseModel/**/*.{swift}'
  end
  
  s.subspec 'Others' do |os|
      os.source_files = 'FirebaseUtility/Classes/Others/**/*.{swift}'
  end
  
  s.subspec 'PresentableProtocols' do |ps|
      ps.source_files = 'FirebaseUtility/Classes/PresentableProtocols/**/*.{swift}'
  end
  
  s.subspec 'SelfHandlingStuff' do |shs|
      shs.source_files = 'FirebaseUtility/Classes/SelfHandlingStuff/**/*.{swift}'
  end
  
  s.subspec 'Firebase' do |fss|
      fss.source_files = 'FirebaseUtility/Classes/Firebase/**/*.{swift}'
  end
  
  
  # s.resource_bundles = {
  #   'FirebaseUtility' => ['FirebaseUtility/Assets/*.png']
  # }

  # s.public_header_files = 'Pod/Classes/**/*.h'
  # s.frameworks = 'UIKit', 'MapKit'
  # s.dependency 'AFNetworking', '~> 2.3'
end
```

**Comment by paulb777** [comment]
It's not a very good error message, but the problem looks like the source repo `https://gitlab.com/vishaln.verve/FirebaseUtility.git` is not accessible.

**Comment by VishalVerve** [comment]
It is private.

**Comment by hiimtmac** [comment]
Did you end up finding a fix for this? Im having the same error when trying to push an update for a private pod to a private spec repo. Nothing has changed in the podspec since last time (which worked) besides `s.version`, `s.tag` & `s.swift_version`. Same error both on CocoaPods 1.6.1 & 1.6.2

**Comment by dnkoutso** [comment]
Please upload a sample repo/podspec for us to diagnose.

**Comment by hiimtmac** [comment]
Tried updating to 1.7.0 and having same problem. The project is only 2 files and no changes have been made to it since the last release besides swift version update (4.2 to 5.0).

Podspec is
```ruby
Pod::Spec.new do |s|
    
    s.name                    = 'ARCKitHelpers'
    s.version                 = '0.0.2'
    s.summary                 = 'Helper methods & extensions for ARC apps'
    s.homepage                = 'http://www.mycompanyname.ca'
    s.author                  = { 'hiimtmac' => 'me@mycompanyname.ca' }
    s.license                 = { :type => 'TOPSECRET', :file => 'ARCKitHelpers/LICENSE' }
    s.platform                = :ios
    s.source                  = {
        :git => 'https://github.com/mycompanyname/ARCKit.git',
        :tag => 'Helpers/' + s.version.to_s
    }
    s.source_files            = 'ARCKitHelpers/ARCKitHelpers/**/*.swift'
    s.requires_arc            = true
    s.ios.deployment_target   = '11.0'
    s.swift_version           = '5.0'
    
end
```

`pod lib lint` seems to work fine
```shell
hiimtmac$ pod lib lint ../ARCKitHelpers.podspec

 -> ARCKitHelpers (0.0.2)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description

ARCKitHelpers passed validation.
```
`pod spec lint` does not
```shell
hiimtmac$ pod spec lint ../ARCKitHelpers.podspec --private

 -> ARCKitHelpers (0.0.2)
    - ERROR | [iOS] unknown: Encountered an unknown error (Pod::DSLError) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.
```
`pod repo push` also does not
```shell
hiimtmac$ pod repo push mycompanyname ../ARCKitHelpers.podspec

Validating spec
 -> ARCKitHelpers (0.0.2)
    - ERROR | [iOS] unknown: Encountered an unknown error (Pod::DSLError) during validation.

[!] The `../ARCKitHelpers.podspec` specification does not validate.
```

**Comment by dnkoutso** [comment]
Can you share the repo? Please also see where the tag `0.0.2` is pointing to. `pod spec lint` will clone that tag.

We really need more information here.

**Comment by VishalVerve** [comment]
I've remove all subspec and it is working fine.

**Comment by hiimtmac** [comment]
In case anyone is interested, it validates properly with `:tag => 'Helpers-0.0.2'` as opposed to the previous `:tag => 'Helpers/0.0.2'`

So something with the `/` in the tag is causing the problem. I just started changing the tags to use the `/` cause it makes nice folders in Xcode. But I can revert back to the `-` 😊

**Comment by amorde** [comment]
Not handling `/` in tags sounds like a bug to me

**Comment by dnkoutso** [comment]
We have plenty of pods with a tag that includes `/`. I honestly think there was a typo or syntax error int he podspec under the 0.0.2 tag.

Without the repo and the subspec we can't do much about it so it remains closed.

**Comment by ARIEnergy** [comment]
@dnkoutso  The issue is still existing ,now I found this error, but earlier it went well.

This is my info I can offer 

Mac M1 12.3.1

`ERROR | [iOS] unknown: Encountered an unknown error (Pod::DSLError
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification.rb:841:in `rescue in _eval_podspec'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification.rb:832:in `_eval_podspec'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification.rb:742:in `block in from_string'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification.rb:741:in `chdir'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification.rb:741:in `from_string'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification.rb:722:in `from_file'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/sandbox/podspec_finder.rb:15:in `block in podspecs'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/sandbox/podspec_finder.rb:14:in `each'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/sandbox/podspec_finder.rb:14:in `podspecs'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/downloader.rb:84:in `download_request'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:256:in `download'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:239:in `block in uncached_pod'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:266:in `in_tmpdir'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:238:in `uncached_pod'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/downloader.rb:42:in `download'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/pod_source_installer.rb:118:in `download_source'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:563:in `install_source_of_pod'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:514:in `block (2 levels) in install_pod_sources'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:86:in `titled_section'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:513:in `block in install_pod_sources'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:496:in `each'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:496:in `install_pod_sources'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:255:in `block in download_dependencies'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:254:in `download_dependencies'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/validator.rb:577:in `block in download_pod'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/validator.rb:577:in `each'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/validator.rb:577:in `download_pod'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/validator.rb:399:in `block in perform_extensive_analysis'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/validator.rb:393:in `each'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/validator.rb:393:in `perform_extensive_analysis'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/validator.rb:130:in `validate'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command/spec/lint.rb:87:in `block in run'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command/spec/lint.rb:69:in `each'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command/spec/lint.rb:69:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `<main>'
) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error and 1 warning.

/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command/spec/lint.rb:104:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `<main>'
➜  ARIBaseKit git:(main) ✗`
