### ISSUE TITLE
pod install doesn't include the same source file in different development pods

### ISSUE THREAD

**Issue by sirghi** [CocoaPods/CocoaPods#8953]
* [ x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I'm developing 2 pods, one for apps and one for NSE app extensions, each having it's own podspec. I have an example project in the same repo that imports the pods via `:path` in the podfile.
- At one point the NSE pod needed to include some source files that are already included in the main pod.
- I updated the `source_files` entry in the NSE podspec to reflect that.
- Ran 'pod install'

## What did you expect to happen?

Those files should appear both under the main pod and under the NSE pod in the project explorer in Xcode.

## What happened instead?

Those files don't show up under the NSE pod. If I however, push the changes to the remote, update the podfile to reference these pods via `:git`, then those files do appear in the project. So I assume that's a problem specifically when using development pods via `:path`.

## CocoaPods Environment

Cocoapods 1.7.3

**Comment by dnkoutso** [comment]
Need a sample app with this. We are unable to diagnose/debug this without one. Please upload one.

**Comment by sirghi** [comment]
[Here](https://github.com/sirghi/common-pod-source) it is. Actually I noticed that the files do get picked up. Only they don't show up separately under the NSE pod in the Xcode project explorer. So I guess it's sort of a UI issue.

**Comment by dnkoutso** [comment]
<img width="1512" alt="Screen_Shot_2019-07-02_at_8_39_40_AM" src="https://user-images.githubusercontent.com/310370/60513341-fde93700-9ca4-11e9-8b13-b3eb158e949e.png">

Yes the files are there. The reason `Common.swift` is added part of `Library` it's because both pods point to this file and it gets added by the first pod processed alphabetically.

I do not see a bug here. Going to preemptively close and I will re-open if we find an 100% reproducible case.

Thanks for the sample also.

**Comment by sirghi** [comment]
Makes sense. Thanks for the screenshot. Cheers
