### ISSUE TITLE
Import ObjC private pod in Swift project gives 'No such module' error.

### ISSUE THREAD

**Issue by iBolom** [CocoaPods/CocoaPods#8998]
Hi,

i created private pod in ObjC language and want to import in Swift project.

My Podfile:
platform :ios, '9.0'

source 'https://github.com/iBolom/cocoapods-spec.git'

target 'TestPods' do
  use_frameworks!
  pod 'TestPodFramework'
end

When i want to import in Swift project it gives me 'No such module' error. Also in Pods project i see my framework and only TestPodFramework.h file and .xcconfig file and don't see .framework file which cocoapods needs to generate.
Cocoapods version: 1.7.3.

Can you help me somehow with this issue?

**Comment by dnkoutso** [comment]
Unfortunately we cannot help with this issue. There is no sample app and at first glance its impossible to tell if CocoaPods library is at fault here.

Please provide a sample app with clear instructions on why this is a CocoaPods library issue. 

Otherwise recommend asking this question in StackOverflow under `cocoapods` tag.

I will re-open once a sample app is provided showing a bug or perhaps an enhancement that can be made. In the meantime we can also continue discussion here.

**Comment by iBolom** [comment]
Here is the framework i made in Objective C: https://github.com/iBolom/TestPodFramework.git.
Here is the cocoapods spec repo where are .podspec files: https://github.com/iBolom/cocoapods-spec
Here is the sample app which use framework above: https://github.com/iBolom/TestPods.git.

If you try to import in ViewController.swift like: import TestPodFramework it gives 'No such module' error.

**Comment by dnkoutso** [comment]
thanks will re-open and can look for time to diagnose.
