### ISSUE TITLE
Support For Multiple Swift Versions in vendored framework

### ISSUE THREAD

**Issue by vitor-gyant** [CocoaPods/CocoaPods#9018]
Hi,

Is there any recommendation to support multiple swift versions in a precompiled iOS framework ? 

My understanding is that spec.swift_versions is only for source code pods. Is this correct ?

Thanks in advance,

**Comment by dnkoutso** [comment]
What specific issue are you seeing? Is it the same as https://github.com/CocoaPods/CocoaPods/issues/8649?

**Comment by vitor-gyant** [comment]
I'm not seeing any issue I just don't know exactly how a precompiled binary swift framework could be released for multiple swift versions in Cocoapods. 

To my understanding I'd need to compile the framework using different toolchain versions like Xcode 10.1 , Xcode 10.2. In the end I'd have two different frameworks for each toolchain. 

Looking at how pods work I'd need to create different podspecs for each binary framework and release them separately. 

My question was if there is support for doing this differently for closed source precompiled frameworks.

**Comment by dnkoutso** [comment]
I do not know how multiple-Swift version pre-compiled frameworks work exactly. How would you do it in "pure" Xcode without CocoaPods? Is it a single `.framework` with each executable in a folder inside or multiple `.framework` files?

For CocoaPods if its multiple files you will need a different `podspec` for it _or_ a single podspec with multiple subspecs one for each Swift version.

**Comment by vitor-gyant** [comment]
In "pure" Xcode it would be different framework files so I think that we would need one podspec for each file.

**Comment by dnkoutso** [comment]
That might be a rather large task for CocoaPods. There are possible ways to achieve that with today's functionality but yes I'd recommend multiple podspecs.

Keep in mind there is still this issue https://github.com/CocoaPods/CocoaPods/issues/8649 open that we aim to land for 1.8.0.

If we did a single podspec with multiple subspecs we would need to update the `swift_version` DSL not to be root only and could be set in subspecs so that expands the scope even further.

**Comment by dnkoutso** [comment]
@vitor-gyant for now I am going to close let me know how it goes and we can re-open or add to #8649
