### ISSUE TITLE
Upgrade from 0.16.2 to 0.17.1 Results in [!] Unsupported version requirements

### ISSUE THREAD

**Issue by tlomenda** [CocoaPods/CocoaPods#922]
I am working on In House CocoaPods and have been using the :local => syntax in my podspec to reference pods as local dependencies until I am ready to officially release it to my private pod spec repository.

This worked great in 0.16.2 and is a very useful feature.  Now I receive the Unsupported version requirements error.

As documented in "https://github.com/CocoaPods/CocoaPods/wiki/Dependency-declaration-options" this syntax to reference a dependency should be accepted.

Thanks.

**Comment by amolloy** [comment]
Now that Cocoapods supports generating frameworks, listing the local dependency in the podfile is no longer adequate to solve this problem since a pod's framework will fail to link if it doesn't know about its dependencies. Any possibility of reconsidering this issue with that in mind? Maintaining a podspec repo just to solve this issue is really a significant burden during development.
