### ISSUE TITLE
Wire up test-spec-defined targets to the app target scheme as well as (or instead of) the library target

### ISSUE THREAD

**Issue by objectmethod** [CocoaPods/CocoaPods#9332]
This is a request for CocoaPods to wire up test-spec-defined targets to the app target as well as (or instead of) the library target.

**Comment by amorde** [comment]
Are you saying you want the dependencies of test specs to be linked and/or embedding into the app target that hosts them?

I don't think we would want to do this, because test specs often contain dependencies only meant for use while running tests, and shouldn't be included in the app itself. If I've misunderstood could you provide some more details on what you're asking for?

**Comment by dnkoutso** [comment]
I think the request is to be able to CMD+U from the app host target that is generated.

**Comment by objectmethod** [comment]
That's correct, @dnkoutso. Sorry, @amorde, I wasn't clear in my initial request.

**Comment by objectmethod** [comment]
It looks like this was resolved in #9539. This is great!  Is there anything we need to do to get this?

I ran `pod gen` and generated the app, opened it, but none of the tests are linked.

**Comment by dnkoutso** [comment]
@objectmethod you need to bump cocoapods in your project. This was merged to master so you can use Bundler to point to a branch or specific SHA of this project since it has not been released officially yet.
