### ISSUE TITLE
Inhibit all warnings for specific dependencies in podspec

### ISSUE THREAD

**Issue by NickyWeber** [CocoaPods/CocoaPods#9506]
Hello there,
I don't know a better place than Issues to ask my question. I did a bit of research but could not find anything. I am developing a pod which naturally depends on other pods. So dependencies are declare in the podspec file. Contrary to a podfile it seems impossible to add an option like `, :inhibit_warnings => true` to a dependency. 

Is there any way to turn off warnings for specific dependencies when developing your own pod?

Thx in advance

**Comment by amorde** [comment]
The only way to do this would be to re-declare the dependencies in the Podfile and manually inhibit the warnings that way.

I don't think we would want to add support for this on the Podspec level, because the consumer of the pod should be in control of how to handle warnings.

Going to close this as it doesn't seem to be an issue but we can continue discussion here 👍

**Comment by NickyWeber** [comment]
Thanks for getting back to me. Makes sense.
