### ISSUE TITLE
how to contain .o file

### ISSUE THREAD

**Issue by wanglelewang** [CocoaPods/CocoaPods#9756]
In my private repos

spec.ios.vendored_frameworks = 'Classes/**/*.{framework, o}'

or

  spec.vendored_libraries = 'Classes/**/*.o'

but  in a project pod install    error  not found xxxx.o

**Comment by dnkoutso** [comment]
CocoaPods will not pickup the `.o` files since they are object files and are not considered source files that Xcode can parse.

Can you specify a case in which you'd want that?

**Comment by samdmarshall** [comment]
to handle `.o` files, the object files should be packaged in an archive (`.a`) file. typically one would call this a static library, as the object files of the library are going to be packaged into the target binary instead of as a separate executable binary file (as with a dynamic library). that is the proper approach for handling any number of additional object files (`.o`s) that you are vendoring. that is the expected behavior for this use case.

**Comment by dnkoutso** [comment]
@samdmarshall so I dont think there is something for CocoaPods to do here?
