### ISSUE TITLE
Default Xcode 12 settings fail to build CocoaPods-generate umbrella headers

### ISSUE THREAD

**Issue by paulb777** [CocoaPods/CocoaPods#9902]
In Xcode 12 default options, `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` is set to Yes. This causes CocoaPods generated umbrella header files to fail with errors like:

`Double-quoted include "FBLPromise+All.h" in framework header, expected angle-bracketed instead`

Reported and additional discussion at https://github.com/firebase/firebase-ios-sdk/issues/5987

Reproducible project:
[testProject.zip](https://github.com/CocoaPods/CocoaPods/files/4886003/testProject.zip)

**Comment by dnkoutso** [comment]
Should we set `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` to `NO` for all Pods build settings?

**Comment by paulb777** [comment]
Yes, that should be safer and easier than generating different content for the umbrellas.

**Comment by amorde** [comment]
Is Xcode 12 now expecting umbrella headers to use `<>` imports?

**Comment by paulb777** [comment]
Yes.

**Comment by amorde** [comment]
Interesting - makes sense I guess. Apple does that in their own frameworks

**Comment by jackguo709** [comment]
I just updated to Xcode 12 and am experiencing this issue. How should I resolve it? After the update, the project can initially be successfully built, with a lot of `The iOS Simulator deployment target is set to 8.0` warnings. So I updated all of their targets to 12.0. Then this quoted imports error appeared. 

I did the following in order, but still get the error.

gem install cocopoads, 
rm -rf ~/Library/Developer/Xcode/DerivedData/
pod deintegrate
pod update

**Comment by swisscheesy** [comment]
> I just updated to Xcode 12 and am experiencing this issue. How should I resolve it? After the update, the project can initially be successfully built, with a lot of `The iOS Simulator deployment target is set to 8.0` warnings. So I updated all of their targets to 12.0. Then this quoted imports error appeared.
> 
> I did the following in order, but still get the error.
> 
> gem install cocopoads,
> rm -rf ~/Library/Developer/Xcode/DerivedData/
> pod deintegrate
> pod update

Just upgraded x-code and am unable to run my flutter app on Ios now as well.  Looking for a fix

**Comment by DavePilksEnt** [comment]
Yeah I didnt mean to reopen this, I just pasted a link for reference. Apologies.

**Comment by Bowzthefirst** [comment]
Thanks Paul

**Comment by libyasdf** [comment]
<img width="1440" alt="Screen Shot 2021-02-02 at 11 51 43 AM" src="https://user-images.githubusercontent.com/26648844/106554611-b1d43780-6556-11eb-9b52-58e86b13619f.png">
<img width="1440" alt="Screen Shot 2021-02-02 at 11 51 51 AM" src="https://user-images.githubusercontent.com/26648844/106554614-b4369180-6556-11eb-85a3-0a566acc407a.png">
<img width="1440" alt="Screen Shot 2021-02-02 at 11 52 03 AM" src="https://user-images.githubusercontent.com/26648844/106554617-b4cf2800-6556-11eb-8e2f-2c5352198f31.png">

pod --version 
1.10.1

but can't fixed this issue.

**Comment by paulb777** [comment]
@libyasdf Make sure to run `pod deintegrate`. See the stackoverflow link above.

**Comment by libyasdf** [comment]
> @libyasdf Make sure to run `pod deintegrate`. See the stackoverflow link above.

problem solved

1. this time I used `pod deintegrate` 

2. `pod install` successes. (A few days ago, due to network reasons, there was a problem in this step. It's not true success before)

3. This project must run on true iPhone.

4. Actually, `pod --version` under the project directory is 1.9.3. I don't know why it's 1.10.1 outside. But it didn't affect the final result.

5. I  run `pod repo-art add cocoa-remote https://....` to make a local repo, below the directory `~/.cocoapods/repos-art`. But when I `pod install`, It's don't download using local resource —— it's cause the `pod install` frequent failures.

**Comment by ynyyn** [comment]
I wonder if there has any option or flag in spec or config to instruct CocoaPods to auto generate the umbrella header in angle-bracketed style `#import`s, to better support Modular Framework? 

As suggested by guidance article from Apple: https://developer.apple.com/documentation/xcode/identifying-and-addressing-framework-module-issues, 

>  | Error message | Error resolution |
>  | ---- |  ---- |
> | double-quoted include “MyObject.h” in framework header, expected angle-bracketed instead | Replace quoted includes with angle-bracketed includes. Change `#import "MyObject.h"` to `#import <ExampleModule/MyObject.h>`. |

Modular Framework seems to use angle-bracketed includes instead of quoted includes.

So I'm curious, apart from suppressing warnings or disabling module, is there a proactive migration or adaptation solution for this issue?
